### ISSUE TITLE
Cannot apply any settings Csrf token fail

### ISSUE THREAD

**Issue by Betawolf1213** [cloudflare/Cloudflare-WordPress#101]
I read on your other post about the IWP but I don't have that installed, yet I'm still dealing with this issues I understand it could be a number of under plugins but I'm not really sure which is could be. 

Help

**Comment by thellimist** [comment]
> @Betawolf1213 Do you have any other plugins installed? If so you should try to turn them on and off one by one to figure out which of those is causing the issue.

**Comment by Betawolf1213** [comment]
Alright so I disabled everything on the site and still having the same issue.

**Comment by jwineman** [comment]
So the root cause is that we read the JSON body from the request with 
```
file_get_contents('php://input');
```

The problem is versions of PHP lower than 5.6 (I think) php://input can only be read once.  Something is reading the JSON request body before our plugin executes, which causes php://input to be null when we do the CSRF check.

Is there anything custom about your setup that reads JSON from a request?

**Comment by Betawolf1213** [comment]
^^ Yea I know of this problem I didn't say anything to avoid sounding like I know when I clearly don't know how to fix the problem. Also to the best of my knowledge no. I checked and the only times the token is being called for is when Cloudflare asks for it but nothing is stopping it from going through it just request it and then nothing happens. I know you guys can't legally login to my site either... But this is kinda a drag. oh also idk if you'd know but has it taken longer than 24 hours to get your ssl cert?

**Comment by jwineman** [comment]
Can you tell us the other plugins you're currently running?  
Where are you hosting your WordPress blog?
Is there anything else "non standard" about your blog set up?

**Comment by Betawolf1213** [comment]
Hosting on Domain.com 

plugins 

Accesspress twitter autopost
Akismet
BBpress
Buddypress
*Cloudflare*
Essential grid
Jet pack 
Mailchimp forms by mailmunch
MO core
Slider rev
W3 total cache
Wordfence security
WPsmush
WP theme optimizer
visual composer 
Yoast SEO

**Comment by thellimist** [comment]
@Betawolf1213 I tried installed (almost) all of your plugins, Cloudflare plugin seems to work. What is your PHP version?

**Comment by Betawolf1213** [comment]
5.5.22

**Comment by Betawolf1213** [comment]
I can't update to 5.6 cause it breaks my site.

**Comment by Betawolf1213** [comment]
I recently through my Myphpadmin disabled everything and only enabled Cloudflare and still had the same issue.

**Comment by thellimist** [comment]
> Is there anything else "non standard" about your blog set up?

**Comment by Betawolf1213** [comment]
Not to my knowledge.

**Comment by jwineman** [comment]
Maybe an obvious question but have you searched all the code on your wordpress blog (core + themes, plugins, etc) for `php://input`?
