### ISSUE TITLE
Site icons are not https

### ISSUE THREAD

**Issue by BinaryMoon** [cloudflare/Cloudflare-WordPress#109]
I have added a site icon through the customizer and it's still http

Everything else is working fine as https but the site icons are http so I am getting mixed content warnings.

**Comment by jwineman** [comment]
Hi, 

Can you be more specific by what you mean when you mention "site icons"?

Thanks,
John

**Comment by BinaryMoon** [comment]
Absolutely - I'm referring to the site icon you can upload through the customizer. It's like a favicon but slightly different.

https://codex.wordpress.org/Creating_a_Favicon#WordPress_Version_4.3_or_later

I've been experimenting some more and I have a feeling the problem may only be in the WordPress admin and not on the frontend.

**Comment by jwineman** [comment]
In 1.x of the plugin we had protocol rewrite which converted `http://` and `https://` to `//`.  3.x uses [Automatic HTTPS Rewrites](https://blog.cloudflare.com/fixing-the-mixed-content-problem-with-automatic-https-rewrites/) which works a little differently.   Instead of converting everything to `//` it only converts `http://` links which we know can be loaded over `https://` to `https://`.  This is also done at the network level now instead of the application (plugin) level.  

Do you have Automatic HTTPS rewrites turned on?

**Comment by BinaryMoon** [comment]
well that explains why I couldn't find the code for this in the plugin :)

I've just checked and I do have automatic https rewrites switched on however - the plugin added a page rule that disables optimisation in the admin. Could this have anything to do with it?

**Comment by BinaryMoon** [comment]
For reference - the site is here: https://masterwp.co

You can see the issue by viewing the source on the homepage, and on the wp-admin login page. The homepage is correct - the wp-admin is loading http content.

I should note that I have successfully used cloudflare with https on other sites running on the same server so I am not sure why it's not working this time.

**Comment by jwineman** [comment]
According to [this](https://support.cloudflare.com/hc/en-us/articles/218411427) "disable performance" doesn't disable automatic https rewrites.  I haven't tested though.  

If you disable the page rule does it work?
You can also create a page rule for /wp-admin/* to enable automatic https rewrites.  Does that fix it?

**Comment by BinaryMoon** [comment]
Just tried disabling the rule and it doesn't make any difference. These are the rules I have enabled:
https://cloudup.com/chO4w9MhFOk

**Comment by jwineman** [comment]
Alright let me investigate a little bit more and get back to you.

**Comment by jwineman** [comment]
What if you modify the first page rule to also turn "Automatic HTTPS rewrites" on?

**Comment by jwineman** [comment]
So a couple things:

Right now Automatic HTTPS rewrites is only rewriting assets from "known" (Sites included in the EFF's [https everywhere rule set](https://github.com/EFForg/https-everywhere/)).  The ability to rewrite assets on Cloudflare sites is still being tested.

Given that it looks like WordPress is loading it over http regardless of whether the request is routed over Cloudflare or not.

Direct to origin:
`$ curl -kvs --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" http://masterwp.co/ --resolve masterwp.co:80:72.52.246.125 | egrep "link rel=\"icon"
* Added masterwp.co:80:72.52.246.125 to DNS cache
* Hostname masterwp.co was found in DNS cache
*   Trying 72.52.246.125...
* TCP_NODELAY set
* Connected to masterwp.co (72.52.246.125) port 80 (#0)
> GET / HTTP/1.1
> Host: masterwp.co
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 14 Oct 2016 02:27:22 GMT
< Server: Apache
< Link: <http://masterwp.co/wp-json/>; rel="https://api.w.org/", <http://wp.me/803jW>; rel=shortlink
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
{ [3747 bytes data]
* Curl_http_done: called premature == 0
* Closing connection 0
<link rel="icon" href="http://masterwp.co/wp-content/uploads/2016/10/favicon-192-50x50.png" sizes="32x32" />
<link rel="icon" href="http://masterwp.co/wp-content/uploads/2016/10/favicon-192.png" sizes="192x192" />`

Through Cloudflare:
`$ curl -kvs --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" http://masterwp.co/ | egrep "link rel=\"icon"
*   Trying 104.24.127.177...
* TCP_NODELAY set
* Connected to masterwp.co (104.24.127.177) port 80 (#0)
> GET / HTTP/1.1
> Host: masterwp.co
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 13 Oct 2016 22:27:40 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d4f86f4f47377fead5af6f92f38e2a7531476397660; expires=Fri, 13-Oct-17 22:27:40 GMT; path=/; domain=.masterwp.co; HttpOnly
< Link: <http://masterwp.co/wp-json/>; rel="https://api.w.org/", <http://wp.me/803jW>; rel=shortlink
< Server: cloudflare-nginx
< CF-RAY: 2f16385f53a8440e-SFO-DOG
<
{ [15934 bytes data]
* Curl_http_done: called premature == 0
<link rel="icon" href="http://masterwp.co/wp-content/uploads/2016/10/favicon-192-50x50.png" sizes="32x32"/>
<link rel="icon" href="http://masterwp.co/wp-content/uploads/2016/10/favicon-192.png" sizes="192x192"/>
* Connection #0 to host masterwp.co left intact`

**Comment by BinaryMoon** [comment]
Ok - thanks for the explanation - I think I understand.

So could I suggest that in a future update you transform sites that are hosted on cloudflare and include support for https? Since you host them you know they are secure so it makes sense that they get changed as well.

Also - I've since realised that there are settings in WordPress itself (in Settings > General) where you set the WordPress Address and Site Urls. These were set to http://.

Perhaps you could add a check to the plugin and if they are set to http warns users that they are insecure and suggests they change them?

**Comment by jwineman** [comment]
Yeah eventually it will rewrite sites that are on Cloudflare.  Luckily the transformation happens at the edge, not in the plugin, so when it is released you won't need to update in order to take advantage of it.

Thanks for telling me about the Settings > General fix.  We'll definitely add in functionality to future releases to detect/warn about this.

Thanks,
John
