### ISSUE TITLE
Use WP_HTTP instead of Guzzle to make API requests

### ISSUE THREAD

**Issue by brandomeniconi** [cloudflare/Cloudflare-WordPress#113]
Hi,
we have a lot of WP websites behind CF and running on Google AppEngine. GAE uses his own library (URLFetch) to make external HTTP calls and hasn't cURL available by default.

We have also few corporate WP installation that doesn't have direct access to internet and they must send requests through a proxy.

The AppEngine Plugin and the `define('WP_PROXY_HOST', '0.0.0.0');` config rules allows WP to manage these situations, but because this plugin use Guzzle instead of the WP_HTTP class, it will not work out of the box in this environments and requires manual patches.

Could this plugin be updated to use the WP_HTTP Class to better follow the WP guidelines?

Thanks for the great work.

**Comment by jwineman** [comment]
You mean [wp_remote_request()](https://developer.wordpress.org/reference/functions/wp_remote_request/) right?

This is something we've been meaning to test but haven't gotten around to yet.  My main concern is whether it will support request types other than GET/POST.

**Comment by jwineman** [comment]
Ah I see [WP_HTTP](https://developer.wordpress.org/reference/classes/wp_http/) now.

**Comment by brandomeniconi** [comment]
As far as I know it supports all the standard HTTP methods via the wp_remote_request() function. I've used it for lot of complex request and it never failed. You can find proof of it in https://www.sitepoint.com/the-wordpress-http-api/

The only time it failed is when I tried to issue a (non-standard) PURGE request while ago, but I think it has been fixed: https://github.com/Ipstenu/varnish-http-purge/issues/19

It will be great for restricted environments :)

**Comment by jwineman** [comment]
I don't have a timeline on this but I have a ticket tracking it internally.

**Comment by brandomeniconi** [comment]
Thanks!
