### ISSUE TITLE
Proxy not Found

### ISSUE THREAD

**Issue by ben29** [cloudflare/Cloudflare-WordPress#126]
when i press "Apply Default Settings" on the plugin
it's stuck..
i try to enable "Automatic Cache Management"
when i do refresh it's return back to off

also i see on the console 
"http://www.sites.com/wp-admin/admin-ajax.php?action=cloudflare_proxy Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by thellimist** [comment]
Do you have any plugin which doesn't allow the blog to retrieve PATCH method http requests?

**Comment by jwineman** [comment]
@ben29 Are there any errors in your PHP error log?

**Comment by ben29** [comment]
@thellimist no. i don't have.
@jwineman i don't see php errors

**Comment by jwineman** [comment]
What other plugins does you're blog have installed currently?

**Comment by ben29** [comment]
now i see error logs on the apache:
[Fri Nov 18 17:51:20.557559 2016] [authz_core:error] [pid 23066] [client 77.138.247.142:54178] AH01630: client denied by server configuration: /home/testuser/domains/site.com/public_html/wp-admin/admin-ajax.php, referer: http://www.site.com/wp-admin/options-general.php?page=cloudflare
[Fri Nov 18 17:51:25.723581 2016] [:error] [pid 23056] [client 77.138.247.142:54177] [CloudFlare] ERROR: [CLIENT API] Array\n(\n    [type] => request\n    [method] => GET\n    [path] => zones/5aafdb9284b6d135aae2b0689d2b8390/analytics/dashboard\n    [headers] => Array\n        (\n            [X-Auth-Key] => 01426d432823416ab8e786718c374182c1adc\n            [X-Auth-Email] => benbaruch1@gmail.com\n            [Content-Type] => application/json\n        )\n\n    [params] => Array\n        (\n            [since] => -43200\n            [action] => cloudflare_proxy\n        )\n\n    [body] => Array\n        (\n            [cfCSRFToken] => \n        )\n\n)\n , referer: http://www.site.com/wp-admin/options-general.php?page=cloudflare
[Fri Nov 18 17:51:25.723701 2016] [:error] [pid 23056] [client 77.138.247.142:54177] [CloudFlare] ERROR: [CLIENT API] Array\n(\n    [type] => response\n    [reason] => Bad Request\n    [code] => 400\n    [body] => Analytics service returned an error\n    [stacktrace] => #0 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\\Http\\Exception\\BadResponseException::factory(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Response))\n#1 [internal function]: Guzzle\\Http\\Message\\Request::onRequestError(Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#2 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#3 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\Common\\Event))\n#4 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('request.error', Object(Guzzle\\Common\\Event))\n#5 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\\Http\\Message\\Request->processResponse(Array)\n#6 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\\Http\\Message\\Request->setState('complete', Array)\n#7 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\\Http\\Curl\\CurlMulti->processResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)\n#8 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\\Http\\Curl\\CurlMulti->processMessages()\n#9 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\\Http\\Curl\\CurlMulti->executeHandles()\n#10 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\\Http\\Curl\\CurlMulti->perform()\n#11 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\\Http\\Curl\\CurlMulti->send()\n#12 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\\Http\\Curl\\CurlMultiProxy->send()\n#13 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/API/AbstractAPIClient.php(79): Guzzle\\Http\\Client->send(Object(Guzzle\\Http\\Message\\Request))\n#14 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Router/DefaultRestAPIRouter.php(64): CF\\API\\AbstractAPIClient->callAPI(Object(CF\\API\\Request))\n#15 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Router/RequestRouter.php(59): CF\\Router\\DefaultRestAPIRouter->route(Object(CF\\API\\Request))\n#16 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/src/WordPress/Proxy.php(62): CF\\Router\\RequestRouter->route(Object(CF\\API\\Request))\n#17 /home/testuser/domains/site.com/public_html/wp-content/plugins/cloudflare/src/WordPress/Hooks.php(95): CF\\WordPress\\Proxy->run()\n#18 [internal function]: CF\\WordPress\\Hooks->initProxy('')\n#19 /home/testuser/domains/site.com/public_html/wp-includes/plugin.php(524): call_user_func_array(Array, Array)\n#20 /home/testuser/domains/site.com/public_html/wp-admin/admin-ajax.php(91): do_action('wp_ajax_cloudfl...')\n#21 {main}\n)\n , referer: http://www.site.com/wp-admin/options-general.php?page=cloudflare
[Fri Nov 18 17:51:25.723775 2016] [:error] [pid 23056] [client 77.138.247.142:54177] [CloudFlare] ERROR: Analytics service returned an error , referer: http://www.site.com/wp-admin/options-general.php?page=cloudflare

**Comment by thellimist** [comment]
@ben29 I've deleted your logs since it contained information which you shouldn't have posted to a public forum. Please send sensitive information through support.cloudflare.com mentioning this issue.

Thanks

**Comment by thellimist** [comment]
This is the error of  @ben29 

```
[Fri Nov 18 17:51:25.723775 2016] [:error] [pid 23056] [client 77.138.247.142:54177] [CloudFlare] ERROR: Analytics service returned an error , referer: http://www.site.com/wp-admin/options-general.php?page=cloudflare
```

**Comment by jwineman** [comment]
```
[Fri Nov 18 17:51:20.557559 2016] [authz_core:error] [pid 23066] [client 77.138.247.142:54178] AH01630: client denied by server configuration: /home/testuser/domains/site.com/public_html/wp-admin/admin-ajax.php
```
It looks like your server permissions are incorrect according to [this](https://wiki.apache.org/httpd/ClientDeniedByServerConfiguration).
