### ISSUE TITLE
Cloudflare plugin stuck on settings page

### ISSUE THREAD

**Issue by roroco** [cloudflare/Cloudflare-WordPress#132]
see my stackoverflow [question](http://stackoverflow.com/questions/40692078/cloudflare-wordpress-is-stuck-on-refresh-settings-page?noredirect=1#comment68613772_40692078)

**Comment by thellimist** [comment]
When it gets stuck could you post 

- PHP error logs
- Browser error logs 

Thanks

**Comment by roroco** [comment]
I'm sure not php error, and when it stuck, my chrome show:

```
 action @ 20:23:44.660 CONFIG_FETCH 
compiled.js?ver=3.1.1:28  action @ 20:23:44.842 CONFIG_FETCH_SUCCESS 
compiled.js?ver=3.1.1:28  action @ 20:23:44.845 CONFIG_UPDATE_BY_KEY 
compiled.js?ver=3.1.1:28  action @ 20:23:44.849 INTL_FETCH_TRANSLATIONS 
compiled.js?ver=3.1.1:28  action @ 20:23:44.856 USER_LOGIN_SUCCESS 
compiled.js?ver=3.1.1:28  action @ 20:23:44.860 ZONES_FETCH 
compiled.js?ver=3.1.1:28  action @ 20:23:44.864 @@router/TRANSITION 
compiled.js?ver=3.1.1:28  action @ 20:23:44.866 @@router/UPDATE_LOCATION 
compiled.js?ver=3.1.1:28  action @ 20:23:45.259 INTL_FETCH_TRANSLATIONS_SUCCESS 
compiled.js?ver=3.1.1:28  action @ 20:23:45.262 APPLICATION_INIT 
compiled.js?ver=3.1.1:28  action @ 20:23:45.951 ZONES_FETCH_SUCCESS 
compiled.js?ver=3.1.1:28  action @ 20:23:45.976 ZONE_SET_ACTIVE_ZONE 
```

**Comment by roroco** [comment]
I just now down wordpress, not other plugin installed except cloudflare

**Comment by roroco** [comment]
Are you sure cloudflare plugin 3.1.1 work in wordpress-4.6.1?

**Comment by thellimist** [comment]
> I just now down wordpress, not other plugin installed except cloudflare

Did this work?

**Comment by roroco** [comment]
I just now down wordpress, not other plugin installed except cloudflare, the problem still exist

**Comment by thellimist** [comment]
The plugin should work on wordpress-4.6.1. The issue is not that. You probably have PHP error. 

Could you post PHP error logs?

**Comment by roroco** [comment]
see my [screencast](https://www.youtube.com/watch?v=qhxXF5r1yeQ)
here is my [vbox export](https://drive.google.com/open?id=0B08GAyjqgToLR2pERVlrZ3BHY1U)
I use new linux mint 18 xfce(ubuntu 16.04) and new wordpress-4.6.1 and just install cloudflare-3.1.1, the problem still exist

**Comment by jwineman** [comment]
If you look in the network tab of the browser console do all of the AJAX requests complete successfully?

**Comment by roroco** [comment]
@jwineman all requests is finish, and no request response status is 4xx or 5xx

**Comment by roroco** [comment]
If I don't use cloudflare plugin, can i use cloudflare web instead?

**Comment by jwineman** [comment]
Yes, every setting in the plugin is also available at http://cloudflare.com

**Comment by thellimist** [comment]
@roroco In your screencast you've `localhost` selected. That's the reason it isn't working. You need a real zone which is added to your cloudflare account. 

Followed internally PI-906
