### ISSUE TITLE
Document minimum PHP version requirement

### ISSUE THREAD

**Issue by XhmikosR** [cloudflare/Cloudflare-WordPress#138]
For example is PHP 5.4 supported? If not, that's OK but it should be documented.

Otherwise, personally, I'd like to remove short tags and `<?=`. I can make a PR if needed.

**Comment by XhmikosR** [comment]
After looking at the source, I see `CLOUDFLARE_MIN_PHP_VERSION` is 5.3.10. Since, `<?=` was controled by the `short_open_tag` option up to v5.4, we definitely need to replace those. PR incoming.

**Comment by thellimist** [comment]
I've tested with PHP `5.3.10` and the plugin was working. This may be causing unexpected problems. I agree with you. It needs to be changed.

**Comment by XhmikosR** [comment]
I made #140 for the replacement.

I still believe the requirements should be documented for both WP and PHP, including php5-curl and anything other that might be needed.

**Comment by thellimist** [comment]
https://github.com/cloudflare/Cloudflare-WordPress/pull/134 is removing php5-curl. 

If there are any missing requirements in the documentation feel free to send a PR.

**Comment by XhmikosR** [comment]
Nah, I'm not so good with words, so I'd rather one of you guys sorted this out.

The fact is that at the moment, it's nowhere documented what is the minimum WordPress or PHP version.

**Comment by thellimist** [comment]
https://en-gb.wordpress.org/plugins/cloudflare/installation/

**Comment by XhmikosR** [comment]
All right, I'm just used to using GitHub only that I didn't even look there ;)

Anyway, feel free to close this then.
