### ISSUE TITLE
Set up a CI system like Travis CI

### ISSUE THREAD

**Issue by XhmikosR** [cloudflare/Cloudflare-WordPress#143]
Now, there is no automated way as far as I can tell, so adding Travis CI will make sure things work all the time.

**Comment by jwineman** [comment]
Yeah we have a git pre push hook which runs the test but it only fires if you run `composer install`.

I'm in favor of setting up CI, need approval from some people internally first.  I'll comment again after I talk to them.

**Comment by XhmikosR** [comment]
Only a CI can guarantee that things keep working on all supported versions, without you guys, going through a lot of trouble ;)

Still, we'll need to solve the issue with PHP < 5.5.
