### ISSUE TITLE
add "Purge" button to admin bar

### ISSUE THREAD

**Issue by mike503** [cloudflare/Cloudflare-WordPress#160]
Related to #94 - this was in my code (and one of the main reasons I still keep my plugin running at the moment, I think your team has implemented most of what I had in mine) but it's very useful to have in the admin bar.

There was a comment that "we don't want to do this, you can do it if you want" - I was looking into leveraging the more robust/reliable caching purging you have in the official plugin, but it looks a little too purpose-built to simply reference inside of my own plugin. It is a lot more advanced than being able to hit a URL or even a simple JavaScript call.

Is there any way (or idea) to "deep link" directly to the purge full site option? Bonus points if it could draw up the bottom bar (on success or error) - but at the moment it looks pretty in-depth and not the simple solution I had hoped to implement.

Currently I am sending a "blind" request to:
DELETE https://api.cloudflare.com/client/v4/zones/ZONE_ID/purge_cache with the JSON params purge_everything = TRUE and the X-Auth-Key and X-Auth-Email headers. I attempt to catch an error response but it doesn't seem to be reliable.

It seems to purge as desired... but not always, and I was thinking that piggybacking on your method would be the more official and reliable way. However I'm finding it difficult to do that. Ideas?

**Comment by thellimist** [comment]
The way to do it is in `cloudflare.loader.php` add an action `add_action('wp_cloudflare_purgecache', array($cloudflareHooks, 'purgeCacheEverything')))`. Other plugins may call this action to purge cache.

The action should direct to this [function](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php#L119-L132). The function will need a bit modification. 

```
if ($this->isPluginSpecificCacheEnabled() || CLOUDFLARE_ALLOW_PURGECACHE_BY_EXTERNAL) {
```

and [here](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/cloudflare.php#L18) `CLOUDFLARE_ALLOW_PURGECACHE_BY_EXTERNAL` should be defined.

as for the return value of [zonePurgeCache](https://github.com/cloudflare/Cloudflare-WordPress/blob/0bb6931d4666e4ae6f16147ef1c30c34cbb1fa27/src/WordPress/WordPressClientAPI.php#L33-L44) currently the hook doesn't care about this. Only for `CLOUDFLARE_ALLOW_PURGECACHE_BY_EXTERNAL` you may want to get the return value which is `boolean` to show an error. The bar on the bottom is a custom UI and would only work for `wp-admin/options-general.php?page=cloudflare` page. You can popup a normal WP error saying the purge failed or succeeded.

**Comment by mike503** [comment]
Anyone want $50 from me to do this? :p

**Comment by thellimist** [comment]
I wrote a bit of the feature [here](https://github.com/cloudflare/Cloudflare-WordPress/pull/179). This feature doesn't give value to the majority of the plugin users and there is no good way to hide it from them. You can use the bases I wrote in the PR and use a forked version of the plugin. 

To sum, we won't be supporting this feature officially. PR's related with Admin Bar Purge Cache button will **not** be accept

Let me know if you have questions. 

Thanks

**Comment by michacassola** [comment]
@thellimist Why not?
