### ISSUE TITLE
simplyadmire submodule missing

### ISSUE THREAD

**Issue by XhmikosR** [cloudflare/Cloudflare-WordPress#164]
```
C:\Users\xmr\Desktop\Cloudflare-WordPress>git submodule init
fatal: No url found for submodule path 'vendor/simplyadmire/composer-plugins' in .gitmodules
```

It seems .gitmodules is missing in https://github.com/cloudflare/Cloudflare-WordPress/commit/46b721f8da44c935be413ef4aa8eb996e27819f2

Is that even needed? Tests seem to pass.

/CC @jwineman @thellimist

**Comment by XhmikosR** [comment]
Is that even needed? Tests seem to pass.

**Comment by thellimist** [comment]
`vendor/simplyadmire/composer-plugins` is not a necessity. It can be removed.

**Comment by XhmikosR** [comment]
Can you remove it and any references from composer files too?

**Comment by thellimist** [comment]
Correction: `simplyadmire/composer-plugins` is used by `wimg/PHPCompatibility`

For more info check: 
https://github.com/wimg/PHPCompatibility/

I don't know the issue with `git submodule init` though. We'll need to discovered that.

**Comment by jwineman** [comment]
If we remove wimg/PHPCompatibility as part of the [deployment process](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/scripts/deployment/trim_code_for_release.sh#L29) we can just update `trim_code_for_release.sh` to remove this too if PHPCompatibility is the only thing that depends on it.

**Comment by XhmikosR** [comment]
@jwineman: My main concern is **how** is it needed? When one clones the repo, they end up with an empty submodule. So, I can't see how it is really needed...

**Comment by jwineman** [comment]
Yeah I agree.  Its a dependency of wimg/PHPCompatibility but since we remove wimg/PHPCompatibility during the deployment process we can also remove simplyadmire/composer-plugins.

**Comment by thellimist** [comment]
Closing the issue since trim_code_for_release already has the removal code for deployment
