### ISSUE TITLE
Set a `Cache-Control: no-cache` header on all frontend pages for logged in users

### ISSUE THREAD

**Issue by brandomeniconi** [cloudflare/Cloudflare-WordPress#167]
Can the plugin set a `Cache-Control: no-cache` (or similar) header on all frontend pages for logged in users? Does the "Cache Everything" option in Cloudflare Page Rules ignores it?

There are some elements in WP that are shown only to logged in users or contain user info (Edit buttons, Comment forms, etc). Some popular Analytics plugins disable the tracking code for logged in users.

If this works, the plugin can also keep the admin bar visible, as requested in #112

**Comment by thellimist** [comment]
> Does the "Cache Everything" option in Cloudflare Page Rules ignores it?
Yes, it would override Cache-Control headers unless "Respect Existing Headers" is set.

For cache everything page rule to work with WP [here](https://support.cloudflare.com/hc/en-us/articles/236166048-Caching-Static-HTML-with-WordPress-WooCommerce) is a good post. We've included [Bypass Cache By Cookie](https://github.com/cloudflare/cloudflare-plugin-frontend/pull/86 ) card. I'll do a beta-release today with the new changes.

**Comment by thellimist** [comment]
I'm closing the issue. Let me know if you have more questions.

Thanks
