### ISSUE TITLE
Server Push is not working with subdomains

### ISSUE THREAD

**Issue by thegulshankumar** [cloudflare/Cloudflare-WordPress#199]
Hello,

Server push is working only for the primary domain. When I activate cdn.example.com for serving static resources, below code doesn't push. Instead, it still relies on the main domain. 

define('CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE', true);

Is there any way update host name at HTTP header? 

Thanks & Regards,
Gulshan

**Comment by thellimist** [comment]
HTTP Server Push is written to work as generally as possible. There are lots of unsupported edge cases.

The header is set [here](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/HTTP2ServerPush.php#L37) in the code. You might want to dig in the code.
