### ISSUE TITLE
Does not work with Flexible SSL and Nginx when restoring original visitor IPs

### ISSUE THREAD

**Issue by tholu** [cloudflare/Cloudflare-WordPress#201]
Plugin does not work when using Flexible SSL and Restoring Original Visitor IPs with Nginx (https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-).

It cannot detect Cloudflare Requests properly anymore, since Nginx already restored the original IP and `isCloudFlare()` in `IpRewrite.php` returns false then.

Any ideas how to fix this?

**Comment by thellimist** [comment]
That is interesting. Are you rewriting `HTTP_CF_CONNECTING_IP` variable anywhere?

https://github.com/cloudflare/cf-ip-rewrite/blob/master/src/CloudFlare/IpRewrite.php#L50-L52

Could you try `real_ip_header X-Forwarded-For;` rather than `real_ip_header CF-Connecting-IP;` in your nginx configuration?

**Comment by tholu** [comment]
`HTTP_CF_CONNECTING_IP` is still present.

The problem seems to be here:
https://github.com/cloudflare/cf-ip-rewrite/blob/master/src/CloudFlare/IpRewrite.php#L92

Since `REMOTE_ADDR` is already rewritten by nginx to the original visitors IP, it is not a CloudFlare IP anymore and the subsequent check (https://github.com/cloudflare/cf-ip-rewrite/blob/master/src/CloudFlare/IpRewrite.php#L76) fails.

**Comment by thellimist** [comment]
Ohh I see the problem. The fastest fix for you would be using [Cloudflare Flexible SSL](https://en-gb.wordpress.org/plugins/cloudflare-flexible-ssl/) plugin along side Cloudflare Plugin. The plugins use different ways to figure out if the requet if from Cloudflare.

I'll keep this issue open. [cf-ip-rewrite](https://github.com/cloudflare/cf-ip-rewrite) repo needs to be updated to fix this issue.

**Comment by tholu** [comment]
Thanks for your suggestion on how to fix it fast! I'd rather only use one Cloudflare plugin - to release a fix faster I can prepare a pull request, if you are not already working on it.

**Comment by thellimist** [comment]
Currently I'm working on different tasks. It'd be great if you could do a PR. Thanks!

**Comment by tholu** [comment]
My PR is here: https://github.com/cloudflare/cf-ip-rewrite/pull/14 
Thanks for a review as soon you find some time for it!

**Comment by thellimist** [comment]
The PR looks good. I'll need time to test it before doing a release. For now you can manually update the vendor folder in your WordPress server. When the WordPress plugin updates it'll overwrite the changes you made locally so it should be fine. Will let you know when we release

Thanks!

**Comment by thellimist** [comment]
I'll close the issue when we release a new version of the plugin.

**Comment by tholu** [comment]
@thellimist Any estimate for the release yet?

**Comment by thellimist** [comment]
@tholu we don't have any release schedule in the upcoming couple months.

**Comment by tholu** [comment]
Can you schedule one? 😉 What is the process behind it?
Would be nice not having to manually update the vendor folder on all the different sites I use this plugin.

**Comment by thellimist** [comment]
Hi @tholu, I can schedule one however I'm focusing on high priority projects atm. I've added on my TODO list. If I haven't released a new version by next week, I probably will not have time till 2018.

**Comment by tholu** [comment]
@thellimist Thank you very much already 👍

**Comment by thellimist** [comment]
https://github.com/cloudflare/Cloudflare-WordPress/releases/tag/v3.3.2. I'm uploading to WordPress SVN. 

Changes will appear on en-gb.wordpress.org/plugins/cloudflare/ with new version number
