### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by piscis** [cloudflare/Cloudflare-WordPress#205]
Hi we've noticed that this:

https://github.com/cloudflare/Cloudflare-WordPress/commit/44e430ca34baa82d2f930edc9fd967ded9b5f0f5

Is not released yet.

When do you think this will land in the the wordpress plugin repository?

Thanks,

Alex

**Comment by thellimist** [comment]
I'm closing this issue. Let's follow the release from https://github.com/cloudflare/Cloudflare-WordPress/issues/201

Thanks for following.
