### ISSUE TITLE
Class 'CF\WordPress\Hooks' not found

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/Cloudflare-WordPress#209]
Hello!

This plugin suddenly started throwing an error. I'm installing it via Composer on Heroku.

Plugin version: `3.3.2`
PHP version: `7.2.1`
Composer version: `1.6.0`

I'm getting the following error:

```
Class 'CF\WordPress\Hooks' not found
```

<img width="838" alt="screen shot 2018-01-05 at 12 24 30 pm" src="https://user-images.githubusercontent.com/665029/34626908-6e82462a-f213-11e7-901c-57ec7ffef20d.png">

**Comment by tillkruss** [comment]
The WordPress installation is running on Heroku, so it's hard to debug.

**Comment by corbanb** [comment]
I just started getting this in my last deploys as well. Haven't seen it before.

**Comment by tillkruss** [comment]
@corbanb: On Heroku as well?

**Comment by corbanb** [comment]
I just removed the plugin. never found a way to uninstall it since it was keeping me from getting into the admin. :/

**Comment by thellimist** [comment]
The plugin is designed to work from installing from WordPress website. Please try to install it from there

**Comment by tillkruss** [comment]
@thellimist: I'm afraid that's not possible, we can only install plugins using Composer.

**Comment by tillkruss** [comment]
>The plugin is designed to work by installing from WordPress website. You can try to install it from there.

This plugin doesn't even work without Composer, so I don't see why it shouldn't be installable via it.

**Comment by tillkruss** [comment]
I think this might be an issue with Composer itself. Looks like there were some autoloader regressions in 1.6.0.

**Comment by corbanb** [comment]
@tillkruss did you find a solution in some Composer updates or changes you made?

**Comment by tillkruss** [comment]
@corbanb The issue was Composer 1.6.0-1.6.1. It's working fine with Composer 1.6.2. Heroku updated their PHP buildpack today.
