### ISSUE TITLE
Can't solve Error: "CSRF Token not found. It's possible another plugin is altering requests sent by the Cloudflare plugin."

### ISSUE THREAD

**Issue by whatinthenameofgod** [cloudflare/Cloudflare-WordPress#215]
I've disabled all my plugins and still can't get this error, **CSRF Token not found. It's possible another plugin is altering requests sent by the Cloudflare plugin,** to resolve.

On version 4.9.4.

Here are what I have installed. Disabling each of these hasn't helped and the error persists:

Advanced Custom Fields
Tracking Code Manager
Bookify
Cloudflare
Faq Responsive
Intergeo - Google Maps Plugin - Lite
MailChimp for WordPress
Max Mega Menu
Ninja Forms
Tracking Code Manager

**Comment by dslyoga** [comment]
I've got a similar problem with same Error Message. [ CSRF Token not found. It's possible another plugin is altering requests sent by the Cloudflare plugin .] But in this kind of stuff, like implementing Cloudflare, I'm only an *Advanced Newbie,* so not really sure where to go on this from here. The six websites I went with SSL via Cloudflare display okay, but mail server on ONE site is not working. 

Cloudflare forum is not much help, so far.

I do know pretty well how to get around most problems with my Wordpress sites, but I'm not even sure what questions to ask here.

Thank You Very Much,
David Scott Lynn

**Comment by seanmc0** [comment]
I have this error, too.  I get it when I try to apply any of the plugin settings (optimize Cloudflare for wordpress; purge cache; automatic cache management...)  I have a number of plugins, but deactivating them all (except made no difference.  Still the error persisted.
The plugin is version 3.3.2 and the WP version is 4.9.6.

**Comment by Kr4ntz** [comment]
Same error here. 
plugins:

Advanced Custom Fields PRO
Akismet Anti-Spam
Coming Soon by Supsystic
Contact Form 7
Easy Google Fonts
Fusion Builder
Fusion Core
LayerSlider WP
Login LockDown
Slider Revolution
UpdraftPlus - Backup/Restore

WP version 4.9.8

**Comment by scharli** [comment]
CMS Commander has a problem too

**Comment by scharli** [comment]
The issue its about that if another plugin do file_get_contents('php://input');
Seems like "php://input" it's only readable once
