### ISSUE TITLE
API key invalid

### ISSUE THREAD

**Issue by mike503** [cloudflare/Cloudflare-WordPress#219]
The WP plugin reports Email address or API key invalid, for multiple sites and accounts and servers (to rule out all variables) - did something change with the API now that dash.cloudflare.com is in place?

I enabled debugging and see this.

```
[12-Jun-2018 17:38:18 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => request
    [path] => https://api.cloudflare.com/client/v4/user/
    [timeout] => 30
    [method] => GET
    [headers] => Array
        (
            [X-Auth-Key] => GLOBAL API KEY
            [X-Auth-Email] => VALID EMAIL
            [Content-Type] => application/json
        )

)
 
[12-Jun-2018 17:38:18 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => response
    [reason] => Forbidden
    [code] => 403
)
 
[12-Jun-2018 17:38:18 UTC] [Cloudflare] ERROR: Forbidden 
[12-Jun-2018 17:38:18 UTC] [Cloudflare] ERROR: Email address or API key invalid. 
```

**Comment by puntogap** [comment]
I have the same problem.

**Comment by mike503** [comment]
After deactivating another couple plugins and reactivating CF first it started working. Don’t have any information how to reproduce or any specifics, I wasn’t doing it in a controlled manner. I just tried it again and it worked. Which is good for my client, but not useful here.

**Comment by puntogap** [comment]
Just test the plugin in a clean installation with the latest version of WP, and everything worked OK.

**Comment by mufatcha** [comment]
I am getting [Email address or API key invalid.] as well. I tried changing my API key and a fresh plugin install and deactivated all plugins

**Comment by zackproser** [comment]
Hi @mike503 and @mufatcha, 

Could you please provide additional info to help me reproduce this issue? 

What type of Cloudflare account do you have (free, pro, enterprise?) 

When did you encounter this error? What action were you attempting? 

Your Wordpress and PHP versions as well. 

I see the example you posted occurred when requesting the user endpoint - is there any other way to reliably trigger this error?

Thanks!

**Comment by mufatcha** [comment]
I have no idea what this is pertaining to.

**Comment by zackproser** [comment]
Please reopen a new issue if this occurs again, and include detailed repro steps. Thanks!

**Comment by tungnd2002** [comment]
same problem.
anybody can help?

**Comment by mojniknam** [comment]
disable all other plugin
then working correctly :)
