### ISSUE TITLE
GDPR text in Privacy Policy guide?

### ISSUE THREAD

**Issue by jonasskafte** [cloudflare/Cloudflare-WordPress#222]
Hi there,

Firstly, thanks for providing so a great plugin to the WP community!

Secondly, I'd like to suggest that CloudFlare provides a simple (or as simple as possible) text explaining my obligations to my visitors, as they might be affected through my use of Cloudflare, rather than Cloudflare’s obligations to me (as outlined [here](https://www.cloudflare.com/privacypolicy/)).

Others have shown an interest in this as well and there's a thread in the WordPress support forum about the issue: [https://wordpress.org/support/topic/gdpr-99/#post-10667752](https://wordpress.org/support/topic/gdpr-99/#post-10667752) – there is also a conversation about it on CloudFlare's community page: [https://community.cloudflare.com/t/gdpr-and-cloudflare/18736](https://community.cloudflare.com/t/gdpr-and-cloudflare/18736).

I'd suggest to add such a text directly to the plugin so that it automatically appears in the Privacy Policy generator/guide found at ../wp-admin/tools.php?wp-privacy-policy-guide=1

Hope to see this improvement and many thanks!

**Comment by garrettgalow** [comment]
Hey, we at Cloudflare cannot tell you what your obligations are to your visitors (regardless of whether you are a Cloudflare customer or not). You can find an overview of information about our [GDPR compliance here](https://www.cloudflare.com/gdpr/introduction/), or if you log into your account on Cloudflare you can accept and/or view our DPA.

We prefer to keep this information fairly centralized as to ensure it stays up to date and is commonly referable, so I don't think we are going to post anything directly regarding our Wordpress plugin.
