### ISSUE TITLE
PHP Warning:  count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by abdusfauzi** [cloudflare/Cloudflare-WordPress#224]
It seems at this line, the value of $wpDomain is not an array, but a string.

https://github.com/cloudflare/Cloudflare-WordPress/blob/7285d0ebc07999cf0721920345b5b47468250808/src/WordPress/Hooks.php#L133

I keep on getting this error:
```PHP Warning:  count(): Parameter must be an array or an object that implements Countable```

**Comment by Laurentiu-Andronache** [comment]
I'm having the same issue.

**Comment by AiratHalitov** [comment]
https://wordpress.org/support/topic/php-warning-count-parameter-must-be-an-array-or-an-object-3/

**Comment by AiratHalitov** [comment]
Fixed in #231
