### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by tralci** [cloudflare/Cloudflare-WordPress#225]
When I install this plugin, in config appears a blank screen for me.
Any tips ?

**Comment by spaskovich** [comment]
I'm experiencing the same thing on Wordpress 5.1 (PHP 7.2)

**Comment by zackproser** [comment]
Hi @tralci and @spaskovich, 

Are you still experiencing this issue with the latest plugin (currently v3.3.3) ? 

If so, could you please provide detailed repro steps.

Thanks

**Comment by zackproser** [comment]
Please check your Wordpress / server logs for errors and reopen a separate issue with detailed reproduction steps if this should occur again. Thanks!
