### ISSUE TITLE
How do you handle the (free?) 30 items limit constraint when purging URLs?

### ISSUE THREAD

**Issue by john-bonachon** [cloudflare/Cloudflare-WordPress#236]
There's some Cloudflare documentation, and [mentioned](https://api.cloudflare.com/#zone-purge-files-by-url) in API docs, regarding a 30 limit on URLs purged per request (for free accounts only?). How do you handle this in the plugin?

**Comment by zackproser** [comment]
The plugin is a client for the Cloudflare API, which will reject purge requests after the 30 item limit has been reached.

**Comment by john-bonachon** [comment]
Ok, in that case, it would be better if the first urls purged are homepage and the post itself. Changing the order the [urls](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php#L171) array items are pushed.
