### ISSUE TITLE
Database corruptions reported on wp.org forum

### ISSUE THREAD

**Issue by galbaras** [cloudflare/Cloudflare-WordPress#238]
There are now some scary threads about v3.3.3 messing up databases and stopping sites on the wp.org forum for this plugin, but no replies from the development team.

Could you either monitor the support forum (better) or create a sticky thread advising people to create issues on Github instead?

For now, I've replied with this information to 3 threads and I hope they will use it to report their issues in detail, but given that several different people have reported issues with their database after updating the plugin, maybe someone from the team can take a look at the thread they've already posted?

**Comment by AiratHalitov** [comment]
I agree. 
https://wordpress.org/support/plugin/cloudflare/ forum contain a lot of duplicates and resolved issues. You can answer them and mark as resolved.

**Comment by galbaras** [comment]
Really? No response in 11 days for a plugin with 200,000+ active installations?

**Comment by galbaras** [comment]
@AiratHalitov you're a contributor to this plugin. When you write "You can answer", who are you referring to? Who actually takes care of the plugin?

Can you at least address the database corruption thread(s) in the forum?

**Comment by AiratHalitov** [comment]
In this repository @zackproser have write access permissions. 

I do not know who is responsible for the support forum, but I think you can find them in "Contributors & Developers" list on plugin's page https://wordpress.org/plugins/cloudflare/
![image](https://user-images.githubusercontent.com/4050715/55814394-d94b4c00-5b07-11e9-8040-fd9046519e84.png)

Or you may independently ask the authors to close topics that have already been solved.

**Comment by garrettgalow** [comment]
thanks for the heads up. I replied to the folks on the forums to try and get more info

**Comment by Tommy0412** [comment]
tested 3.3.3 on 
wordpress 4.9.10
php 7.1.28
mariadb 5.5.60
im now using 3.3.2 and it work fine. 
3.3.3 messed my database and i was unable to login to wp admin.

**Comment by Tommy0412** [comment]
tested again in another website only differrence is php php 7.1.28 and everything work fine

**Comment by Tommy0412** [comment]
now plugin work on both sites. look like problem was coz i was using auto update. manualy work fine.

**Comment by garrettgalow** [comment]
Both tests were with php 7.1.28?

What do you mean by auto update versus manual?

**Comment by Tommy0412** [comment]
on one website im using php 7.1.27 and on another one 7.1.28 and now on both plugin work fine, by manualy i mean i was uplaoding new plugin files into /wp-content/plugins/ 
previously i was using auto update going here /wp-admin/update-core.php  in browser

**Comment by garrettgalow** [comment]
Can you describe what behavior you saw a bit more? Also what database errors or issues did you see?

**Comment by Tommy0412** [comment]
NO!

**Comment by garrettgalow** [comment]
We need more information to be able to reproduce this to find a fix. We haven't been able to reproduce this ourselves yet.
