### ISSUE TITLE
It looks like your domain is not provisioned with Cloudflare

### ISSUE THREAD

**Issue by scottwpspeedfix** [cloudflare/Cloudflare-WordPress#240]
I get this error before I can even put in my email and API key. The site is already on cloudflare so I'm not sure what the problem is.

**Comment by gsusI** [comment]
I saw that error because I had WP_HOME and WP_SITEURL in my wp-config.php corrupted. Correcting those fields solved the issue.

**Comment by garrettgalow** [comment]
gsusl's comment is correct, we use the urls in WP to determine if there is a zone to use with the plugin and where to change settings.
