### ISSUE TITLE
Update tested version to 5.1

### ISSUE THREAD

**Issue by garrettgalow** [cloudflare/Cloudflare-WordPress#241]
https://github.com/cloudflare/Cloudflare-WordPress/blob/f3c0dae3a3b258557639d93b46c8307ac057a3f0/readme.txt#L5

The last release we did put us at 5.1 of wordpress. We are getting a warning on https://wordpress.org/plugins/cloudflare/ that is incorrect.

**Comment by barryhughes** [comment]
Yes please, note also [this conversation](https://wordpress.org/support/topic/tested-only-up-to-version-wordpress-4-9-9/) on the community forums where many others are requesting the same.
