### ISSUE TITLE
No way to use a non-global API key

### ISSUE THREAD

**Issue by g2p** [cloudflare/Cloudflare-WordPress#243]
If I use the "WordPress" template to generate an API token specific to one domain from my Cloudflare dashboard, disable and re-enable the official plugin from my WordPress site, and try to authenticate, I get "email address or API key invalid".
Please provide a way to handle tokens besides the global API key.

**Comment by josephrocca** [comment]
Very much looking forward to this plugin supporting the new scoped API keys also! Far too risky to use a global API key on one of my little wordpress projects. I've considered using the [worker edge cache plugin](https://github.com/cloudflare/worker-examples/tree/master/examples/edge-cache-html/WordPress%20Plugin) in the mean time, but if there's a chance that this plugin will be updated in the next couple of months I might just wait it out.

**Comment by garrettgalow** [comment]
PR #245 will allow for API Tokens to be used in the plugin

**Comment by josephrocca** [comment]
Thanks! I didn't realise that the plugin doesn't support caching HTML unless the user is on a business plan, so it turns out I'll need to use the worker edge cache in any case.

**Comment by saward** [comment]
Hi!  I'm having trouble finding this in docs anywhere -- which permissions should the API token be given for the proper functioning of this plugin?

**Comment by garrettgalow** [comment]
https://developers.cloudflare.com/api/tokens/create 
You can use the `wordpress` api token template which should simplify this process.
