### ISSUE TITLE
No way to re-authenticate after rolling / changing an API key

### ISSUE THREAD

**Issue by g2p** [cloudflare/Cloudflare-WordPress#244]
When the API key is changed from Cloudflare's dashboard, the WordPress plugin fails to authenticate, but doesn't provide a way to change the saved credentials.
The only workaround is to disable and re-enable the plugin.

**Comment by brandomeniconi** [comment]
I faced this problem many times and another workaround, without reinstalling the plugin is to change the key in `yoursite.com/wp-admin/options.php` by searching "cloudflare"..

**Comment by manatarms** [comment]
Unfortunately, there is no way to log out of the plugin yet. You can either uninstall the plugin or delete cloudflare options like @brandomeniconi mentioned
