### ISSUE TITLE
Unneeded Symfony/Yaml dependency? (and bundled dev dependencies)

### ISSUE THREAD

**Issue by pjeby** [cloudflare/Cloudflare-WordPress#247]
I've been running into some problems with a wp-cli command that needs a newer version of Symfony/Yaml than is vendored with this plugin, and this plugin ends up blocking it from being loaded because of autoloader precedence.

However, I can't seem to find where the Yaml component is actually *used* by anything within the Cloudflare plugin, so the dependency appears redundant.  (In addition, the bundled vendor/ directory appears to have been built with development dependencies, meaning the distribution is unnecessarily large and prone to overriding other packages with outdated versions as well.)

Perhaps symfony/yaml can now be removed from composer.json and the vendor tree rebuilt with just the non-development dependencies?  Thanks.

**Comment by pjeby** [comment]
Further activity such as?

**Comment by jenkoian** [comment]
I think it's only used in a single test (https://github.com/cloudflare/Cloudflare-WordPress/blob/52541ea21a81c11109b222ea7a27fbf0c401f45b/vendor/symfony/yaml/Tests/ParserTest.php#L18) ...please consider at the very least to move into a dev dependency. Order of preference:

- Use https://github.com/10up/action-wordpress-plugin-deploy and include `composer.json` in `.distignore`
- Remove YAML dependency (although appreciate may be a pain to rewrite that test without it)
- Update to latest version 
- Move to dev dependency 

This relates to https://github.com/cloudflare/Cloudflare-WordPress/issues/304 a little but this yaml dep is causing us a few problems which I think can be easily resolved. Thanks!

**Comment by jenkoian** [comment]
Every time I want to clear the object cache I have to disable this plugin due to this issue...obviously it's not all about me, but any movement on this seemingly small change would be greatly appreciated 🙏 . 

If you specify which is your favoured approach I'm more than happy to provide a PR 😇

**Comment by jenkoian** [comment]
> - Use https://github.com/10up/action-wordpress-plugin-deploy and include `composer.json` in `.distignore`

I actually don't think this will help because the autoloader won't change which is where the problem lies, so can rule that one out

Another option though is to use https://github.com/coenjacobs/mozart this is used by some [major](https://github.com/woocommerce/woocommerce/pull/28147) [plugins](https://github.com/wp-media/wp-rocket/pull/3008) already,

**Comment by jacobbednarz** [comment]
if i understand the issue correctly here, i think this has been fixed since 4.1.0. feel free to let me know if it isn't addressed for you and we can revisit.

**Comment by pjeby** [comment]
While 4.10 removed the other bundled dev dependencies, `symfony/yaml` is still listed in `require` rather than `require-dev`, still vendored by the plugin, and still autoloaded by it.   So the original problem still exists.

**Comment by jacobbednarz** [comment]
thanks for confirming! do you want to take a pass at addressing this?

**Comment by pjeby** [comment]
I took a shot at it in #374.
