### ISSUE TITLE
IpRewrite doesn't work

### ISSUE THREAD

**Issue by timofey-drozhzhin** [cloudflare/Cloudflare-WordPress#253]
I noticed that Cloudflare plugin attempts to set `$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP']`, however it doesn't work because the function executes too late. This function needs to be executed before the plugins are loaded.

Working example:
```
add_action( 'plugins_loaded', function () {
	if (!empty($_SERVER['HTTP_CF_CONNECTING_IP'])) {
		$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];
		$_SERVER['HTTP_X_FORWARDED_FOR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];
	}
}, 1 );
```

Additionally, I think it would be beneficial to set `$_SERVER['HTTP_X_FORWARDED_FOR']` also to the IP address, as many websites are behind a load balancer and default to `$_SERVER['HTTP_X_FORWARDED_FOR']`.

**Comment by manatarms** [comment]
This issue was fixed as part of v3.7.0. Thanks for reporting and proposing a fix.
