### ISSUE TITLE
"Upgrade" buttons shown within plugin window lead to 404 pages

### ISSUE THREAD

**Issue by dotmanish** [cloudflare/Cloudflare-WordPress#254]
The "Upgrade to Business/Pro" plan buttons shown within the plugin settings lead to 404 pages at the moment.

![cloudflare-wordpress-temp-1](https://user-images.githubusercontent.com/2811377/81509686-45772100-92c1-11ea-9c15-b82de7f28862.png)

**Comment by manatarms** [comment]
This issue was fixed as part of v3.7.0. Thanks for reporting the issue.
