### ISSUE TITLE
Purges Silently Failing on CF Breaking Change

### ISSUE THREAD

**Issue by gramorris** [cloudflare/Cloudflare-WordPress#268]
On the 30th June CF introduced a 30 url limit to purge requests (https://api.cloudflare.com/#zone-purge-files-by-url). Currently the plugin makes no provision for that limit and by and large fails relatively silently. We've put a temporary fix on our sites by removing http urls using the purge filter but in a https site it is relatively easy to hit the 30 purge limit if a post contains 5 or so terms.

**Comment by olegcarguy** [comment]
Is this related to: https://github.com/cloudflare/Cloudflare-WordPress/issues/266

**Comment by gramorris** [comment]
yes, apologies, it is. it's the same issue.

**Comment by gramorris** [comment]
Closing as a duplicate, I'll add notes to #266
