### ISSUE TITLE
Abaondoned plugin? I find errors in the debug log

### ISSUE THREAD

**Issue by BIG1** [cloudflare/Cloudflare-WordPress#274]
Hello. Is the cloudflare plugin abandoned? It havent been updates for a while. Using newest wordpress and php 7.4.
In my error log I find this:

Trying to access array offset on value of type null in /home/username/public_html/wp-content/plugins/cloudflare/src/WordPress/Proxy.php on line 62

**Comment by patryk** [comment]
Hi @BIG1.
The plugin is not abandoned, but currently we are unable to give it much attention it deserves. Therefore, the development slowed down, but I hope it'll go back to normal eventually.

**Comment by BIG1** [comment]
Thank u. Is there  quick fix for the issue mention in debuglog I can edit myself?

**Comment by garrettgalow** [comment]
@BIG1 are you seeing any issues in the plugin or its behavior because of the error?

**Comment by BIG1** [comment]
Not that I am aware of... but when seeing this error in the debug it concerns me.
