### ISSUE TITLE
Feature request: Purge Cache from Toolbar

### ISSUE THREAD

**Issue by bozzmedia** [cloudflare/Cloudflare-WordPress#277]
It would be really helpful to have a Purge Cache option on the WordPress toolbar. This is pretty standard for most WP caching plugins and would really help end users who have trouble finding the cache clear option under Settings. Thanks for your consideration!

Image example of toolbar with both Autoptimize and WP Fastest Cache clear options. (Same for other widely used plugins like WP Super Cache and W3 Total Cache)
![image](https://user-images.githubusercontent.com/4435114/93135514-4cf37000-f68f-11ea-92ad-065ad3ee9531.png)

**Comment by orenwolf** [comment]
Auto optimize is a one-time-use thing, no? I don't think that would need a toolbar option?

**Comment by bozzmedia** [comment]
@orenwolf this is just an example of a common site toolbar with two different caching plugins Autoptimize and WP Fastest Cache (not cloudflare). It would be really helpful workflow-wise to have Purge Everything as a toolbar item alongside these server-side caches.

**Comment by TheOneWizard1** [comment]
+1 right now the auto-purge feature hasn't been perfected. Elementor header is a good example if you edit the header it doesn't purge for all pages.

**Comment by lkraav** [comment]
This sounds like an integration system with other caching plugins is a thing. We'd like to trigger CF URL purge when clicking WP Super Cache admin bar button.

**Comment by yogeshbeniwal** [comment]
Can also integrate with [Nginx Helper](https://wordpress.org/plugins/nginx-helper/) plugin.
