### ISSUE TITLE
APO feature real ip resolve issue

### ISSUE THREAD

**Issue by MertcanGokgoz** [cloudflare/Cloudflare-WordPress#296]
When we activate the APO feature, the real ip is not resolved on the server side and We only see the 2a06:98c0:3600::103 

Real ip module loses its functionality on the server side. but why? When I turn off the APO feature, the IP addresses are resolved, the problem disappears. I cannot actively use the APO feature yet because the IP addresses have not been resolved.

Do you have a solution to this situation?

**Comment by garrettgalow** [comment]
closing this as a dupe in favor of #297 - please watch that issue for updates
