### ISSUE TITLE
Wordpress plugin tied to apex domain even for subdomain installs ?

### ISSUE THREAD

**Issue by centminmod** [cloudflare/Cloudflare-WordPress#298]
Is it an oversight to have Wordpress plugin tied to apex main domain even if Wordpress is installed on subdomains ? Can't the cache key be targetted at the Wordpress settings URL so that it can be unique? Can't the Wordpress API token template permissions include page rule access outside of page rule CF account quotas to add specific page rules for subdomain specific optimisations enabled via the plugin?

![cf-wp-plugin-subdomain-notice2](https://user-images.githubusercontent.com/5899584/95070886-24b9d700-074c-11eb-9b4b-27b11e9274f7.png)

**Comment by garrettgalow** [comment]
There are some limitations to controlling settings at the subdomain vs apex domain. The plugin does come with an assumption that the entire zone is being used for WP, which is obviously not always the case. I don't see this fundamentally changing soon. We may do better detection of the domain for specific features like APO, but the zone settings changes pretty much have to be zone wide.

**Comment by centminmod** [comment]
cheers @garrettgalow in the context of Wordpress plugin triggered zone while changes would they take priority over CF page rules and other CF Workers configured to do something different from what Wordpress plugin zone changes make?

For instance from https://support.cloudflare.com/hc/en-us/articles/227342487-What-settings-are-applied-when-I-click-Apply-Default-Settings-in-Cloudflare-s-WordPress-plugin-

If i setup CF Worker to configure via fetch the `cf` object to disabled auto minify HTML = false or via page rule but the Wordpress applied default sets zone whide auto minify HTML = true

**Comment by lkraav** [comment]
I have the same question wrt multiple sub-directory installs. "Everything the same" is actually fine, but could use a confirmation on "is it safe / OK?".

**Comment by sejoker** [comment]
We have updated warning to [mention APO](https://github.com/cloudflare/cloudflare-plugin-frontend/commit/5541afb74881c994cc886f7fff51fc4b47f80d85), I'm closing the issue as fixed.
