### ISSUE TITLE
No option to reset API/Email credentials ?

### ISSUE THREAD

**Issue by centminmod** [cloudflare/Cloudflare-WordPress#299]
Once you enter your Global API Key and email to log into your account via the Wordpress plugin, there is no option to reset those credentials in the Wordpress plugin itself ??? How are you meant to reset it and try different credentials i.e. API Tokens ?

Only way I have been able to is by editing wp option database settings via wp-cli command line to empty out `cloudflare_api_key ` and `cloudflare_api_email ` option values

i.e.

```
vhostname=yourdomain.com
wppath="/home/nginx/domains/${vhostname}/public"
wp option update cloudflare_api_key "" --allow-root --path=$wppath
wp option update cloudflare_api_email "" --allow-root --path=$wppath
wp option list --allow-root --path=$wppath | grep cloudflare
```

**Comment by manatarms** [comment]
@centminmod see https://github.com/cloudflare/Cloudflare-WordPress/issues/244
