### ISSUE TITLE
APO conflict with VaultPress

### ISSUE THREAD

**Issue by kevinlisota** [cloudflare/Cloudflare-WordPress#303]
Turning on APO in the new version of the plugin disrupts communication with VaultPress.

With APO off, VaultPress works fine on our site. Turning APO gives VaultPress errors. Trying to re-register VaultPress also does not work with APO turned on.

Turning APO off solves these issues. Our web server is configured to forward the real IP addresses from Cloudflare, so that isn't the issue.

**Comment by garrettgalow** [comment]
Can you provide some more detail on what disruption you are seeing?

It might be IP related as we are tracking a fix in order to ensure we send the correct IPs to WordPress when using APO. I'd like to be sure its IP related or if something else we can investigate as needed.

**Comment by kevinlisota** [comment]
It is likely related to IP address, as I know VaultPress has an "internal firewall" for its IP addresses. I also know that Cloudflare put those IP address on its allow list like 5 years ago or so.

I have not contacted Automattic to diagnose further. The only log entries I see on my end on the ones mentioned in my [other issue submission](https://github.com/cloudflare/Cloudflare-WordPress/issues/302).

With the APO button turned off, VaultPress works properly. With the APO button turned on, backups do not succeed and VaultPress throws an error that says there are communications problems.

**Comment by kevinlisota** [comment]
The exact error I get from VaultPress when APO is turned on is this:

VaultPress is having trouble connecting to your site. Please make sure your site is online with the VaultPress plugin installed and activated.

**Comment by garrettgalow** [comment]
hm we (Cloudflare) aren't going to be able to diagnose what that might mean. Unless you can pull further info out of VaultPress as to the issue, I'm going to assume its probably the IP issue and we can see if this resolves once we fix that.

**Comment by garrettgalow** [comment]
We just finished rolling out a fix, so please verify that IPs are correctly being populated now. This was a change to the service on the edge, so no plugin changes or update.

**Comment by kevinlisota** [comment]
Seems to be working now. Must have been an IP issue. I have some other caching issues with APO. I'll submit a report request
