### ISSUE TITLE
PHP warnings with wp-cron.php invoked with crontab

### ISSUE THREAD

**Issue by dobacco** [cloudflare/Cloudflare-WordPress#305]
Stack trace
    E_WARNING: Cannot modify header information - headers already sent
    in header called at /var/www/testsite.com/data/wp-content/plugins/cloudflare/src/WordPress/Hooks.php (312)
    in CF\WordPress\Hooks::initAutomaticPlatformOptimization called at /var/www/testsite.com/data/wp-includes/class-wp-hook.php (287)
    in WP_Hook::apply_filters called at /var/www/testsite.com/data/wp-includes/class-wp-hook.php (311)
    in WP_Hook::do_action called at /var/www/testsite.com/data/wp-includes/plugin.php (478)
    in do_action called at /var/www/testsite.com/data/wp-settings.php (546)
    in require_once called at /var/www/testsite.com/data/wp-config.php (120)
    in require_once called at /var/www/testsite.com/data/wp-load.php (37)
    in require_once called at /var/www/testsite.com/data/wp-cron.php (44)

Looking at the code I believe the `public function initAutomaticPlatformOptimization()` function needs to be made aware of the DOING_CRON variable and not send headers?

If I disable APO this warning continues so I hope it isn't just a configuration issue on my side.

**Comment by jb510** [comment]
Same.   Also see #302 which is probably the same thing but hasn't identified this is happening on WP CRON (which it is for me)

**Comment by Log1x** [comment]
Any chance this can get assigned and addressed ASAP please?

**Comment by manatarms** [comment]
Hey, we're looking into this issue. Will keep you updated. Sorry about the log noise.

**Comment by kevinmrl** [comment]
Hello, same here can confirm:

Warning: Cannot modify header information - headers already sent
![image](https://user-images.githubusercontent.com/45454204/95855094-8d164300-0d60-11eb-94fa-1fab6cbd2e0e.png)

**Comment by manatarms** [comment]
This was released with v3.8.4. Let us know if it fixes the issue for you.
