### ISSUE TITLE
One Click Page Rules

### ISSUE THREAD

**Issue by nasiralamreeki** [cloudflare/Cloudflare-WordPress#306]
The Cloudflare WordPress Plugin says "One-click WordPress-optimized settings" and to a degree it does this. It would be nice to see this taken a notch further by adding WordPress optimized page rules when using the plugin to apply one click optimization.

**Comment by garrettgalow** [comment]
`adding WordPress optimized page rules` what page rules do you mean exactly?

**Comment by nasiralamreeki** [comment]
> `adding WordPress optimized page rules` what page rules do you mean exactly?

I'm not sure why but the Cloudflare Documentation recommended page rules for WordPress no longer exist but generally for page rules the following was recommended in the past and is generally used by people using Cloudflare with WordPress today:
1. *example.com/wp-admin*
    Cache Level: Bypass
    Security Level: High
    Disable Apps
    Disable Performance
2. *.example.com/wp-includes/*
    Cache Level: Cache Everything, Edge Cache TTL: 1 week, Browser Cache: 1 week
3.  *.example.com/wp-content/* 
    Cache Level: Cache Everything, Edge Cache TTL: 1 week, Browser Cache: 1 week

**Comment by nasiralamreeki** [comment]
I'd add also maybe implementing these: https://support.cloudflare.com/hc/en-us/articles/228503147-Speed-Up-WordPress-and-Improve-Performance

In reality a lot of the WordPress Cloudflare documentation is outdated so maybe going over current and pass best practices surrounding page rules and setting and just adding some page rules to the one click experience of the plugin? Ultimately without page rules things like the backend are cached and that's not good generally.

**Comment by sejoker** [comment]
The recommended setup is to use Automatic Platform Optimization instead of the page rules with "Cache Everything". I'm going to close the issue as we don't plan to add automatic Page Rules any time soon.

**Comment by nasiralamreeki** [comment]
This isn't a great result for those using who don't want APO and use the Cloudflare plugin. Cloudflare and its plugin should be a world class experience without steering free plan users to paid plans which is what it seems like its come to. Page rules have become stripped down over time with options moving from free to paid. Wordpress support used actually be much better.
