### ISSUE TITLE
Does APO even works?

### ISSUE THREAD

**Issue by kevinmrl** [cloudflare/Cloudflare-WordPress#310]
Hello,

Not sure if it is the right place to ask, but seems that APO does not work?

Using WP v.5.4.2
CF plugin for WP v.3.83

1. Enabled APO
2. Cleared CF cache (all)
3. Opened incognito window (to be sure no cookies present etc)
4. Opened web, visited homepage

I see headers are:
![image](https://user-images.githubusercontent.com/45454204/95858065-29dadf80-0d65-11eb-8a76-5670943c6fcf.png)

Doing multiple refreshes, getting the same headers. The PAGE/doc initial request is almost always the same **700-800ms**

![image](https://user-images.githubusercontent.com/45454204/95858260-7c1c0080-0d65-11eb-9600-3d748a832ad2.png)

Meaning, it seems no-cache is ever applied. Compared to - if I just set a page rule (which was disabled when testing APO), for the homepage to be like: 

```Browser Cache TTL: 4 hours, Cache Level: Cache Everything, Origin Cache Control: Off```

I would get a cf-cache-status: HIT in header and PAGE/doc initial request would be like **60-80**ms

Is it really enough just to enable APO, or it is needed to add some Page Rules extra or so. Tried to find more info about that, but didn't get any luck.

Thank you!

**Comment by sejoker** [comment]
Hi, 

you should check x-via response header, most certainly it has value `speedwp/origin,no-cache`. In Chrome when DevTools are open browser add request cache-control: no-cache header. It could be disabled in Browser settings. I recommend using curl:

```
curl -svo /dev/null 'https://example.com' -H 'accept: text/html' 2>&1 | grep '< cf-cache-status'
```

or webpagetest.org.

**Comment by kevinmrl** [comment]
Are you try to say that if someone would use Chrome with DevTools open, or would use no-cache header, then the cache would be ignored from CF? Oouuchh...

**Comment by garrettgalow** [comment]
In chrome, at least, there is a toggle in network tools called "Disable cache" if you uncheck that then you will see cached behavior with APO. Otherwise yes, APO will respect the no cache header that the request makes and bypass the cache to the origin.
