### ISSUE TITLE
Adjust Edge Cache TTL?

### ISSUE THREAD

**Issue by thekendog** [cloudflare/Cloudflare-WordPress#313]
The documentation says that the HTML will be cached on the edge for 30 days.  How do I change this?  What about nonces that are only valid for certain periods of time?

Is there a way to disable certain pages from being cached?

**Comment by sejoker** [comment]
There is no way for customers to change Edge caching TTL when APO is activated, I'm curious to know you use case.
>> Is there a way to disable certain pages from being cached?
the only way I know is to hack around this code path: https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php#L319-L321 and serve `cf-edge-cache: no-cache` for pages you want to exclude from caching with APO.

**Comment by thekendog** [comment]
I have a plugin that makes an Ajax request to a REST endpoint.  It uses a nonce for a security check.  That nonce is going to be invalid after a day.

Another use case...

I have a page with data that updates every hour.  Obviously 30 days is way too long.

It doesn't seem like this APO functionality is very flexible, which is a bummer.

**Comment by sejoker** [comment]
> I have a page with data that updates every hour. Obviously 30 days is way too long.

WP plugin allows you to purge cache on each page publish, you can call Cache Purge API manually as well


> It doesn't seem like this APO functionality is very flexible, which is a bummer.

It's not as flexible as other caching plugins on the market, we aim for simplicity of use. It trumps flexibility in our view.

**Comment by kevinlisota** [comment]
Do Page Rules allow you to change the Edge Cache TTL? We have dynamic content (popular & recently published posts) on each post in WordPress that changes frequently but at a slow pace. It changes slowly enough that caching works, but 30 days for that section of the page is way too long.

The WP plugin does not purge when these changes take place because there is no publish or update action that takes place on the post itself.

I understand the goal for simplicity, but locking customers into a 30 day TTL is highly restrictive when there are dynamic elements on the posts.

**Comment by thekendog** [comment]
> I understand the goal for simplicity, but locking customers into a 30 day TTL is highly restrictive when there are dynamic elements on the posts.

This.

I believe most contact forms use nonces as well.  I'm pretty sure Gravity Forms and Contact Form 7 does.  So 30 days is going to cause those to not work.

**Comment by sejoker** [comment]
> I believe most contact forms use nonces as well. I'm pretty sure Gravity Forms and Contact Form 7 do. So 30 days is going to cause those to not work.

Interesting use case. I looked into Contact Form plugin source code, according to the Changelog:

5.1.4
- Creates a nonce only when the submitter is a logged-in user.

So we will bypass cache for logged-in user.

In general we can detect contact forms by inspecting urls (I suspect it will have `contact` or `form` as part of url). For those pages theoretically we can analyze html  for nonce tokens. By combining those 2 factors we can set TTL to 8 hours on the pages. 

Please let me know if someone has an existing page I can play with.

**Comment by sejoker** [comment]
@kevinlisota for dynamic content which is a part of cacheable page I think [Edge-Side-Include](https://blog.cloudflare.com/edge-side-includes-with-cloudflare-workers/) is the perfect answer. Please let us know if you would be interested in wrapping  "popular & recently published posts" into esi block, so we could apply transformation on those pages automatically.

**Comment by sejoker** [comment]
We added puge rules integration with APO, now it's possible to set custom Edge TTL or bypass APO caching altogether. https://community.cloudflare.com/t/apo-release-2020-11-6/221663?u=yevgen

**Comment by sejoker** [comment]
I think it's safe to close the ticket.
