### ISSUE TITLE
Enrol Cloudflare plugin in a Wordpress site on a subdomain using API Token fails.

### ISSUE THREAD

**Issue by vsnine** [cloudflare/Cloudflare-WordPress#316]
Hello,

I think this may be somewhat related to #255. I've also written about this issue [here](https://wordpress.org/support/topic/error-adding-subdomain/#post-13565599). When I try to enrol a wordpress site which sits at a subdomain, using an API Token, ie: wp1.test.com, it fails. Global API key works but is not my preference as the wordpress site admins may not be the same as the Cloudflare admins. API Token is strongly preferred.

Drilling down the logs, I observed the API call is made like this: 
https://api.cloudflare.com/client/v4/zones/?name=wp1.test.com

If I replicate this in Postman I get this error:
            "message": "Actor 'com.cloudflare.api.token.xxxxxxx' requires permission 'com.cloudflare.api.account.zone.read' to list zones"

If I change the name filter to the actual zone name, it succeeds.

Searching the code base I identified that the login routine is handled in the file [AbstractPluginActions.php](https://github.com/cloudflare/Cloudflare-WordPress/blob/1a45c986892d1f9c8f4f98e7e1c9ad8e06447f12/vendor/cloudflare/cloudflare-plugin-backend/src/API/AbstractPluginActions.php#L95), and the API call is made on line 95. The function getOriginalDomain() used returns the site URL hostname but this is not the Cloudflare zone name, its just a DNS record. If I replace the function call and hard code the zone name (ie: test.com instead of wp1.test.com), it succeeds and the plugin is able to load and then manage things as expected.

Perhaps an advanced feature could be to allow the zone name to be specified manually? We will not always be able to position the Wordpress site at the apex record.

Thanks. Please let me know if I could provide any more information.
-Josh

**Comment by vsnine** [comment]
To add, I had opened case 2002281 with Cloudflare Support, I updated them with this information as well.

**Comment by garrettgalow** [comment]
Currently our plugin expects to operate at the apex given that all setting changes will affect the entire zone not just the subdomain wordpress runs on, so some issues can occur when using subdomains. I think we likely need to do a bit better job supporting subdomains before we change this otherwise we give folks the wrong conclusion.

**Comment by vsnine** [comment]
Understood. The primary factor the customer is interested in at the moment is cache purge, as there are other apps in the domain which may not play well with enabling all of the performance features available. It would be nice to have more specific failure messaging depending on what's going on.

**Comment by sejoker** [comment]
please follow https://support.cloudflare.com/hc/en-us/articles/360049822312#h_01EQVCQBMEVE37SXPD26ZD168A.

**Comment by timnolte** [comment]
@sejoker why was this closed when it doesn't seem like the issues was actually addressed/fixed.

**Comment by garrettgalow** [comment]
@timnolte You will need to activate the wordpress plugin on the zone as it is named in Cloudflare. We don't support running the plugin for a non-zone subdomain as its not possible to control zone settings for a subdomain of a zone unless it is a [standalone subdomain zone](https://support.cloudflare.com/hc/en-us/articles/360026440252-Understanding-Subdomain-Support).

If you are looking to use APO then you can enable APO for only the relevant subdomain.

**Comment by timnolte** [comment]
> @timnolte You will need to activate the wordpress plugin on the zone as it is named in Cloudflare. We don't support running the plugin for a non-zone subdomain as its not possible to control zone settings for a subdomain of a zone unless it is a [standalone subdomain zone](https://support.cloudflare.com/hc/en-us/articles/360026440252-Understanding-Subdomain-Support).
> 
> If you are looking to use APO then you can enable APO for only the relevant subdomain.

@garrettgalow I'm not quite clear on this as the situation is that the main domain and the subdomain are were configured with their own zones. I'll take a look at that article but when you say a "standalone subdomain" are you referring to a subdomain zone where the primary domain doesn't have it's own zone?

**Comment by timnolte** [comment]
> > @timnolte You will need to activate the wordpress plugin on the zone as it is named in Cloudflare. We don't support running the plugin for a non-zone subdomain as its not possible to control zone settings for a subdomain of a zone unless it is a [standalone subdomain zone](https://support.cloudflare.com/hc/en-us/articles/360026440252-Understanding-Subdomain-Support).
> > 
> > If you are looking to use APO then you can enable APO for only the relevant subdomain.
> 
> @garrettgalow I'm not quite clear on this as the situation is that the main domain and the subdomain are were configured with their own zones. I'll take a look at that article but when you say a "standalone subdomain" are you referring to a subdomain zone where the primary domain doesn't have it's own zone?

@garrettgalow I just read through that subdomain article and we are trying to do exactly what that article describes with ensuring that the root domain and the subdomain each have their own full setup. The WordPress plugin doesn't seem to support this setup.
