### ISSUE TITLE
Breaks Divi builder opt in

### ISSUE THREAD

**Issue by thelanj** [cloudflare/Cloudflare-WordPress#320]
The javascript powering the DIVI theme's email opt in does not work when APO is activated.  As soon as the cache is purged or turned off, it works fine.

**Comment by sejoker** [comment]
The plugin is closed source, I can't see how it works. The recommendation: 
- either disable APO caching on the pages with the plugin using Page rules: https://support.cloudflare.com/hc/en-us/articles/360049822312#h_01ER098Z0DRS95ERCMZRV3022S
- or trigger cache purge manually after you make changes in the builder.
