### ISSUE TITLE
APO on Subdirectory Installs

### ISSUE THREAD

**Issue by BIueRich** [cloudflare/Cloudflare-WordPress#321]
This may be a similar issue to this: [316](https://github.com/cloudflare/Cloudflare-WordPress/issues/316) but figured it was not quite the same.

Wordpress may exist on a subdirectory of a site, such as:
www.domain.com/blog

Meanwhile the rest of the site on the root and other subdirs may be separate dynamic content. We see that with APO turned on in this situation, everything will get cached and controlled by the Wordpress plugin for the domain. We could certainly add our own no-cache headers to the rest of the site, but wondered if the plugin will eventually support the "wordpress install directory" to cache and purge only under that path, leaving anything not wordpress above it to be standard Cloudflare caching.

Along those same lines, I believe there is a roadmap to having Page Rules work with APO so that we could do our own explicit exclusions?

**Comment by sejoker** [comment]
APO integration with Page Rules is explained [here](https://support.cloudflare.com/hc/en-us/articles/360049822312-Understanding-Automatic-Platform-Optimization-APO-with-WordPress#h_01ER098Z0DRS95ERCMZRV3022S). We don't have plans to support APO running in the subdirectory as a standalone feature.

**Comment by BIueRich** [comment]
I think that actually handles the issue of using APO on a domain for subdirectories. As we've seen APO take over the whole site acting like it's wordpress even if it's just under a subdirectory, we can use page rules to bypass APO for all other parts of a site besides the Wordpress subdir. I'll do some testing to confirm this is works as it seems it is intended. Thanks

**Comment by sejoker** [comment]
Please let me know if it worked, in the meantime I'm closing the issue as fixed.
