### ISSUE TITLE
Auto Purge With Elementor Header/Footer 

### ISSUE THREAD

**Issue by TheOneWizard1** [cloudflare/Cloudflare-WordPress#322]
Hi,

Love the most recent update however the is currently an issue with auto purging. 

Using elementor when you update either the header or the footer it doesn't clear the cache for all related pages.

Not sure if this would be possible if not an admin toolbar flush cache would be great.

Thanks much

**Comment by sejoker** [comment]
please join the conversation https://github.com/cloudflare/Cloudflare-WordPress/issues/275#issuecomment-804823964, closing as a duplicate.
