### ISSUE TITLE
Recommended Setting with WP-Rocket? 

### ISSUE THREAD

**Issue by TheOneWizard1** [cloudflare/Cloudflare-WordPress#323]
Wp-rocket on of the most popular wordpresss caching/speed optimization plugins had a Cloudflare integration option.

My question is what is the recommended configuration with wp-rocket. Should we use there default integration or yours?

Have looked around quite a bit for documentation on this nothing really to be found.

Some guidance here would be great.

**Comment by colinmcdermott** [comment]
This is the number 1 result when you Google [wp rocket cloudflare]... https://docs.wp-rocket.me/article/18-using-wp-rocket-with-cloudflare
