### ISSUE TITLE
Preloading Downloaded Google Fonts

### ISSUE THREAD

**Issue by TheOneWizard1** [cloudflare/Cloudflare-WordPress#324]
Hi,

Love to downloading google fonts to the local server this was a nice feature.

However, preloading fonts is huge like Trump Daddy HUGGGE.  If possible the additional option to preload these fonts would be great.

Not sure if the local font's url are dynamic, or expire, otherwise I would just do it locally.

Clarification here would be great.

Thanks

**Comment by sejoker** [comment]
We have better solution with APO: https://blog.cloudflare.com/building-automatic-platform-optimization-for-wordpress-using-cloudflare-workers/#moving-optimizations-to-the-edge. We don't plan to add support for Google Fonts any time soon.
