### ISSUE TITLE
Purge cache when post status changes from Publish to Draft

### ISSUE THREAD

**Issue by janvitos** [cloudflare/Cloudflare-WordPress#325]
When a post is at the Publish status and you change it to Draft, the cache is NOT currently purged and the post remains on the Home Page, Categories, Tags and Archives.

I believe the normal behavior of the plugin should be to purge the cache when a published post is changed back to draft as it effectively disappears from the site like when a post is trashed.

Thanks.

**Comment by weezer311** [comment]
In researching this issue https://github.com/cloudflare/Cloudflare-WordPress/issues/331 I found some hooks that could catch this status change.
https://codex.wordpress.org/Post_Status_Transitions

**Comment by sejoker** [comment]
this is now fixed.
