### ISSUE TITLE
Purge Category and Tag feed cache

### ISSUE THREAD

**Issue by janvitos** [cloudflare/Cloudflare-WordPress#326]
Right now, the plugin purges the cache of various feeds, like Home Page feed and Archives feed, but it doesn't purge the cache of Category feeds or Tag feeds.

It would be really helpful if the plugin purged the Category feeds and Tag feeds cache whenever a post is published, updated, trashed, etc.

**Comment by sejoker** [comment]
@janvitos totally agree, it's one of the top reported issues with APO. I'm more than happy to review and publish your PR.

**Comment by janvitos** [comment]
Awesome.

Just so you know, I already applied my PR to my own fork and it is working perfectly.

**Comment by sejoker** [comment]
@janvitos I can confirm this change works for tags invalidation. Unfortunately I can't make it work for category pages (cache is not purged). I also don't see cache invalidation for tags and categories when post is moved to trash or deleted. Do you have similar issues in your setup?

**Comment by janvitos** [comment]
That's strange @sejoker, it seems to be working fine on my end. All Cateogies are purged at least when a post is created or updated. I have to admit I did not test for trash or deletion, but I assumed that would also work since it seemed to be working for normal taxonomy pages.

I will investigate and get back to you.

**Comment by janvitos** [comment]
Hi @sejoker, as you can see from this screenshot (https://imgur.com/DSk7zza), all tags and categories are purged when a post is published or updated.

This post in particular was only assigned to a single category, so only that specific category was purged. I did not test with a post assigned to multiple categories, but it should work as well since the logic in the code was already doing that for normal category purges.

**Comment by janvitos** [comment]
I confirm that purging Categories / Category feeds and Tags / Tag feeds WORKS as expected when trashing or restoring a post.

**Comment by janvitos** [comment]
Any news on this @sejoker? Thanks!

**Comment by sejoker** [comment]
@janvitos I was able to make it work on my test environment, changes look good, we will release changes on Monday.
