### ISSUE TITLE
Scheduled Wordpress Posts + WPMU

### ISSUE THREAD

**Issue by BIueRich** [cloudflare/Cloudflare-WordPress#331]
We have a client that is a WPMU site AND also is on the Business plan, that we are continuing to have issues with full page caching, not clearing, and caching URLs that are 404s.

The issue we are seeing is this:
a) APO apparently is not technically able to be used with WPMU sites currently, correct?
We have tested with it on and off, and of course prior to this feature being in the Cloudflare plugin for WP, it was not being used.
b) We have used the standard Page Rule feature for the Business account to Cache Everything, Bypass on Cookie.

What we've seen happen is that our client will create a Post in wordpress for any of the multisite domains. They may save it as a draft, as they like to create posts and then "schedule" it to go live at a later date.. sometimes days later.

So what we believe happens is that the URL of the draft post as seen by an admin user (with cookie bypass) is able to see the post. Somehow the actual URL that is not visible to the public, gets into Cloudflare's full page cache as a 404 page at that time. It is possible that the client is making the post live at some point, then puts back into draft mode (perhaps)... and that is how the unpublished URL is getting a 404 cached.

However, what we would expect wordpress to do is once the post goes live on schedule, that the URL gets purged thru the Cloudflare plugin/API. Does that functionality exist?

As a workaround, I've also attempted to add my no-cache header to 404s from apache, but it doesn't seem that Cloudflare is honoring that... is there a recommended way of adding no-cache to 404s to ensure Cloudflare bypasses cache with APO?

I think a lot of this stems from the mix of APO vs Business level WP Page Rules method + a WPMU setup. And then of course the fact that 404'd URLs aren't getting purged by API properly.

**Comment by sejoker** [comment]
can you provide an example of cached 404 page?

**Comment by BIueRich** [comment]
https://laltoday.6amcity.com/florida-water-taste/#Poll

**Comment by BIueRich** [comment]
We may have sent a manual purge to that page before you had a chance to look at it.
We also have noticed just today that the plugin/APO now seems to recognize multiple domains under the WPMU which it wasn't there before.
i.e.
WordPress plugin successfully detected on redacteddomain.com, www.redacteddomain.com, site1.redacteddomain.com, site2.redacteddomain.com, site3.redacteddomain.com, site4.redacteddomain.com, site5.redacteddomain.com, site6.redacteddomain.com, site7.redacteddomain.com.

So we've now turned back on APO and turned off the business plan method Page Rules of cache everything/bypass on cookie. We will monitor this further to confirm if that aspect now works to purge. 

Just to confirm, is the plugin supposed to handle a scheduled post going live on it's own? We're going to watch the API call now to see if that's happening, but I wanted to confirm that is intends to work that way.

thanks

**Comment by weezer311** [comment]
I think adding 'future_to_publish' to the  $cloudflarePurgeURLActions array will trigger the purge on a scheduled post going live.

**Comment by garrettgalow** [comment]
The related issue sounds like a good candidate fix for us to add support for.

It should be said that this plugin does not officially support multi-site setups. While anecdotally I know of some customers that have been able to use the plugin with multi-sites without issue, we don't officially support it in that we don't do validation testing on Multi-site setups before releasing new versions.

**Comment by BIueRich** [comment]
Great.. we'll track with the issue when it gets added.

**Comment by sejoker** [comment]
https://github.com/cloudflare/Cloudflare-WordPress/pull/397 should have fixed the issue, please reopen if it doesn't work in the latest version of the plugin.
