### ISSUE TITLE
Reporting a security concern

### ISSUE THREAD

**Issue by sitedart-studio** [cloudflare/Cloudflare-WordPress#338]
I feel there is a severe security issue with this plugin, but I need to know how to report it. No need to display what I am seeing except to the authors.

Thank you

**Comment by deuill** [comment]
Hi, you can submit a vulnerability report via our [HackerOne](https://hackerone.com/cloudflare/reports/new) page, more information [here](https://www.cloudflare.com/disclosure/). Thank you!
