### ISSUE TITLE
403 errors

### ISSUE THREAD

**Issue by dodgecountyfairgrounds** [cloudflare/Cloudflare-WordPress#340]
I get two 403 errors when activating (enter email address & key) Cloudflare plugin in Wordpress

I have deactivated all plugins and still no luck.

My host is asking if there are any PHP modules which need to be enable under Cpanel servers to resolve these issues.

Any help would be appreciated

Thanks,
Rochelle

**Comment by sejoker** [comment]
Please [raise support ticket](https://support.cloudflare.com/hc/en-us/articles/200172476-Contacting-Cloudflare-Support).
