### ISSUE TITLE
Browser TTL

### ISSUE THREAD

**Issue by adamzr** [cloudflare/Cloudflare-WordPress#341]
My Wordpress site uses Cloudflare APO. I want it to send a `Cache-Control` header to ensure that the browser maintains a short cache for the HTML (PHP) pages, so that my users see updates quickly. But, I have no easy way to do so. Wordpress does not send caching headers. I have not figured out how to do it with Nginx. **Cloudflare Browser TTL and Page Rules that send Browser TTL doesn't work with APO**.

Please fix it so that Cloudflare default browser TTL and Page Rules Browser TTL should work even with Wordpress APO or alternatively have APO set its own short TTL Cache-Control header.

Ideally, APO should allow for Last-Modified-Since headers. Since the Wordpress plugin knows when every page is modified from the Wordpress database, you could support Last-Modified-Since and just tell the browser to always revalidate. If you store the last modified date in Workers KV this would mean that the browser cache would be used after just getting a quick 304 from Cloudflare.

**Comment by sejoker** [comment]
> Please fix it so that Cloudflare default browser TTL and Page Rules Browser TTL should work even with Wordpress APO or alternatively have APO set its own short TTL Cache-Control header.

There is technical limitation why Browser TTL Page rule doesn't work with APO, I would love to support this in the future, but we can't provide this at the moment.

> Ideally, APO should allow for Last-Modified-Since headers. Since the Wordpress plugin knows when every page is modified from the Wordpress database, you could support Last-Modified-Since and just tell the browser to always revalidate. If you store the last modified date in Workers KV this would mean that the browser cache would be used after just getting a quick 304 from Cloudflare.

Thanks for idea, the complexity of making it work for all cases makes it quite hard to do. We will evaluate all the feature requests next quarter, so far it's not high on our priority list.

**Comment by sejoker** [comment]
I'm going to close the issue, as we don't have any plans to support custom Browser TTL Page Rule for APO.
