### ISSUE TITLE
Wordpress 5.6 with Cloudflare Plugin 3.8.7 unable to install

### ISSUE THREAD

**Issue by munibahmad** [cloudflare/Cloudflare-WordPress#342]
Unable to install the plugin on WP version 5.6. Wait sign keeps rotating but nothing happens. Cloudflare portal still says no Wordpress site detected.

**Comment by michacassola** [comment]
Yes, same issue for me!

**Comment by rsimplicio** [comment]
I, too, have been bitten by this.

**Comment by rsimplicio** [comment]
> I, too, have been bitten by this.

So, I managed to get this to work; I was on a new Flywheel site and hadn't yet setup the real domain and pointed Cloudflare to the origin IP, etc. - Just wanted to loop back in case that helps anyone else.

**Comment by sejoker** [comment]
2 clarification questions:
- did you sign in with API token or Global Key?
-  was plugin installed on the root domain or subdomain?

If it was API token could you try login with Global Key and report back the resutls? At the moment API token can' be used on subdomain https://github.com/cloudflare/Cloudflare-WordPress/issues/316.

**Comment by jacobbednarz** [comment]
closing this off as PHP 5.6 is [no longer supported](https://wordpress.org/support/topic/cloudflare-wordpress-plugin-4-0-deprecating-php-ver-7-2/) as of 4.x. if this is still an issue on the latest version, please let me know and we can revisit.

**Comment by michacassola** [comment]
@jacobbednarz It was WP 5.6 not PHP 5.6.

**Comment by jacobbednarz** [comment]
doh! 🤦 thanks for the heads up.

once #332 lands, you could look at setting the values as in your configuration file as well.

**Comment by jacobbednarz** [comment]
closing this off now as [v4.2.0](https://github.com/cloudflare/Cloudflare-WordPress/releases/tag/v4.2.0) has the ability to define `CLOUDFLARE_DOMAIN` which will allow you to tell Cloudflare which site to use this on if you haven't yet setup the domain in Cloudflare yet.

**Comment by sejoker** [comment]
@jacobbednarz that's great, would be great to add this know-how to https://github.com/cloudflare/Cloudflare-WordPress#faq

**Comment by michacassola** [comment]
@jacobbednarz Would you please be so kind and elaborate more on this or point to the detailed documentation on this?
Does this mean I can setup the plugin from the command line and do not have to have an API key setup in the plugin for HTTP/2 PUSH to work?

**Comment by jacobbednarz** [comment]
> [..] would be great to add this know-how to https://github.com/cloudflare/Cloudflare-WordPress#faq

We can definitely add it to the FAQ but it is there somewhere else that we could put it to make it easily discoverable? WordPress doesn't seem to have great options for this and usually each plugin rolls it's own approach.

> Would you please be so kind and elaborate more on this or point to the detailed documentation on this?

As @sejoker mentioned, this isn't documented outside of the PR that implemented it however to use it, you need to add the `define` to your `wp-config.php`

```php
define('CLOUDFLARE_DOMAIN_NAME', 'example.com');
```

This then overrides the hostname sent to Cloudflare to configure against the plugin.
