### ISSUE TITLE
Enable HTTP/2 Server Push through BASH without API Key or API Email

### ISSUE THREAD

**Issue by michacassola** [cloudflare/Cloudflare-WordPress#344]
Is there a way to enable HTTP/2 Server Push through BASH without API Key or API Email?
Thanks in advance!

**Comment by jacobbednarz** [comment]
Do you mean via WordPress/hosting instance for your Cloudflare zone? If so, I'm afriad not. The WordPress plugin still uses the API which in turn requires credentials to perform the operation.
