### ISSUE TITLE
Hooks called to early for themes

### ISSUE THREAD

**Issue by marcwieland95** [cloudflare/Cloudflare-WordPress#345]
Hey there

I think a couple of hooks are called too early to be able to alter them via a theme.

`cloudflare_purge_everything_actions` and `cloudflare_purge_url_actions` should be called within an `init` action.

Can someone proof that?
Thanks and cheers
Marc

**Comment by markjaquith** [comment]
Correct... it's bad practice to apply filters or do actions as your plugin code is loaded. I even consider it a bad practice to add actions or hooks directly as your code is loaded. Deferring everything to `plugins_loaded` is much better. It gives others one place to completely short-circuit your code, and it ensures that they can reliably interact with your hooks.

**Comment by marcwieland95** [comment]
For now, most hooks are not working at all.

This is a major issue in my eyes.

**Comment by jacobbednarz** [comment]
@marcwieland95 @markjaquith are either of you open to providing a PR for what you'd like to see change here? I'm happy to review/test it but my knowledge of how this expected to work is pretty limited in the WordPress ecosystem.

**Comment by marcwieland95** [comment]
I had a quick look into it when I had the issue. But it doesn't seem too simple since there are multiple classes fired at the wrong time (as far as I remember).

I can't guarantee if and when I can make time to create a PR. But since this is a big issue I should be definitely solved ;-) I created a super ugly workaround, so in my projects, it's working for now.

**Comment by weezer311** [comment]
I too am having an issue with this. I'm trying to hook update_option.

**Comment by ivptr** [comment]
Please be so kind to reopen this issue.

@marcwieland95 What does your workaround look like?

**Comment by marcwieland95** [comment]
Here you go. Not proud, but it's solving this issue since I created it 2.5 years ago.

```
protected static $purgeActions = [
        'deleted_post', // Delete a post
        'edit_post', // Edit a post - includes leaving comments
        'delete_attachment', // Delete an attachment - includes re-uploading
        'post_updated', // Update a post
        'comment_post', // Post a comment
        'acf/save_post', // ACF Data saved (including option pages)
];

public function __construct()
{
    // This is a super hacky way to trigger a hook from a third-party plugin which is preregistered
    foreach (static::$purgeActions as $action) {
        add_action($action, [$this, 'hackyForceClearCache'], 80);
    }
}

public function hackyForceClearCache()
{
    do_action('autoptimize_action_cachepurged');

    if (WP_DEBUG) {
        error_log('CloudFlare Cache purged (timestamp: ' . time());
    }
}

**Comment by ivptr** [comment]
Where do you insert this code? In some plugin file directly?

**Comment by marcwieland95** [comment]
In my theme. I do have a class for it. That's why the constructor is there.
But you could also inline it and just dump it into the `functions.php`

**Comment by ivptr** [comment]
Yeah, but that code doesn't seem related to this plugin?

For example, I would like to add some URLs to plugin's clear request.

**Comment by marcwieland95** [comment]
I think they have some hooks where you can filter based on the url (never used it). If you run those hooks within a normal `init` hook, that doesn't work I think. So you can run it within the `hackyForceClearCache` method.

It's been a long time since I worked on that. I'm not aware of the details by now.
