### ISSUE TITLE
Incorrect domains when activated

### ISSUE THREAD

**Issue by jamesduffy** [cloudflare/Cloudflare-WordPress#347]
Due to a legacy issue we currently have www and non-www domains going to different servers. https://example.com going to wordpress and https://www.example.com going to another service (non-wordpress). When we enable APO in the plugin it adds both www and non-www domains to the active domains, but we only want one of them.

Is there some combination of this plugin with Page Rules to make sure that the non-wordpress domain is not served from APO? Is there an update to the plugin we can make to force a single domain and not both?

![Screen Shot 2021-01-13 at 11 38 25 AM](https://user-images.githubusercontent.com/613313/104500927-e413fa00-5593-11eb-8994-108a7b8cf94a.png)

**Comment by sejoker** [comment]
@jamesduffy I'm in the process of documenting API for public usage. Once it will be live you will be able to configure APO for only www subdomain. I don't recommend Page Rules setup for the root domain as it will bypass all caching including static assets.

**Comment by sejoker** [comment]
the API are available, please follow: https://github.com/cloudflare/Cloudflare-WordPress/issues/372#issuecomment-801829196
