### ISSUE TITLE
Hook to perform a prefix cache purge

### ISSUE THREAD

**Issue by michaelsimon** [cloudflare/Cloudflare-WordPress#349]
Looking to be able to add a hook into Wordpress so that if a specified post type is updated, a prefix purge is performed on a subpath.

For example, I have different banners (posttype) I display on different subsites- banner 1 displays on /site1, banner 2 displays on /site2, etc. If Banner 1 is updated, a prefix purge for /site1 is performed, if banner 2 is updated, a prefix purge is performed on /site2.

**Comment by sejoker** [comment]
This is blocked on Cache purge by tag availability to [Enterprise customers only](https://support.cloudflare.com/hc/en-us/articles/200169246-Purging-cached-resources-from-Cloudflare#32qtE74mOBqLjQjhTbqd2c). We cant' provide this functionality by default to all plans.
