### ISSUE TITLE
Pagination purging cause server to hang

### ISSUE THREAD

**Issue by frenzis** [cloudflare/Cloudflare-WordPress#351]
After the upgrade to version 3.8.8 we notices lot of errors server-side. We have thousands of published posts and thousands of pages. When a post is updated, hundreds of call is spawn to Cloudflare API and sent in synchronous to Cloudflare server, causing incredible delay to process.

This is is caused by this https://github.com/cloudflare/Cloudflare-WordPress/pull/339  PR

If you would like to introduce pagination purge, you should make it asynchronous or use the [TAG feature](https://support.cloudflare.com/hc/en-us/articles/200169246-Purging-cached-resources-from-Cloudflare#h_6d756ac9-c476-45e8-a5d4-e2a6e45d9dc7) in Cloudflare that can purge cluster of pages in one shot.

**Comment by janvitos** [comment]
I noticed the same thing. Purging the Cloudflare cache now takes close to a minute since the 3.8.8 update. It used to take a few seconds only. Though, there are no errors in my server log.

Rolling back to 3.8.7 fixed the issue for me.

**Comment by lkraav** [comment]
Ouch. #339 does look rather naive. I wonder if background jobs and jumping onto https://github.com/woocommerce/action-scheduler is in order, sooner or later.

Might be a good idea to downgrade plugin for now :thinking:

**Comment by xtuc** [comment]
we are going to revert the latest change and publish a fix.

**Comment by garrettgalow** [comment]
plugin version 3.8.9 just went out which reverts the changes that caused this issue
