### ISSUE TITLE
Cloudflare APO Edge Cache TTL & nonce in page rules?

### ISSUE THREAD

**Issue by ericger** [cloudflare/Cloudflare-WordPress#364]
I very much welcome the development of Cloudflare APO to speed up TTFB. 

However, my contact form uses nonces that require a low cache time for the HTML.

Now my question: how can I set the cache TTL for the HTML from Cloudflare APO separately, without changing the TTL for all other requests. 

At the moment I seem to have to provide all pages where the contact form is used with low TTLvia Page Rule for all elements. This slows down the website on average. 

I'm not a professional unfortunately, but hope someone can help me. Thanks!
warm regards,
Eric

**Comment by ericger** [comment]
Nearly two weeks without a single comment on this? :( That is a bit sad. I love the idea of Cloudflare APO but how is Cloudflare dealing with nonces at the moment? There doesn't need to be an immediate solution.

**Comment by sejoker** [comment]
@ericger setting custom Edge TTL via Page rules is [the only available option](https://support.cloudflare.com/hc/en-us/articles/360049822312-Understanding-Automatic-Platform-Optimization-APO-with-WordPress#h_01ER098Z0DRS95ERCMZRV3022S). That's said each url with contact form is unique, so setting custom Edge TTL for them won't impact Edge caching of any other static resources.

**Comment by sejoker** [comment]
Also Page Rules [support wildcards](https://support.cloudflare.com/hc/en-us/articles/218411427#h_6N5SySNYCjYUUnCKnC1Ea6). So potentially only a single rule is needed to override Edge Cache TTL for pages with contact form.

**Comment by ericger** [comment]
@sejoker Thanks for your answer. So that means if we have a contact form on every page, we would need to overwrite the Edge Cache TTL for all of them to the lifespan of the nonce?

**Comment by sejoker** [comment]
correct.

**Comment by ericger** [comment]
I am thinking about getting rid of the nonce. I will look into that. :D thanks for your help.

**Comment by sejoker** [comment]
you can always ask APO related questions in http://community.cloudflare.com/ there are more than handful number of folks who can help, I generally try to monitor APO questions there as well.
