### ISSUE TITLE
Plugin failed to update to latest version

### ISSUE THREAD

**Issue by ggPixel** [cloudflare/Cloudflare-WordPress#366]
My site went down today after updating to the latest version of the Cloudflare plugin.

`Warning: Cannot declare interface PHPUnit\Framework\MockObject\Invocation, because the name is already in use in /usr/www/users/ctutrygdtj/wp-content/plugins/cloudflare/vendor/php-mock/php-mock-phpunit/autoload.php on line 20 Fatal error: Declaration of phpmock\phpunit\MockDisablerPHPUnit6::endTest(PHPUnit\Framework\Test $test, $time) must be compatible with PHPUnit_Framework_BaseTestListener::endTest(PHPUnit_Framework_Test $test, $time) in /usr/www/users/ctutrygdtj/wp-content/plugins/cloudflare/vendor/php-mock/php-mock-phpunit/classes/MockDisablerPHPUnit6.php on line 44`

**Comment by markjaquith** [comment]
There's no need to ship Composer dev packages in the Plugin Directory version. Anyone who wants to contribute or run the unit tests should come to this GitHub version.

I recommend that the build process for shipping to the WordPress Plugin directory do `composer install --no-dev --optimize-autoloader`

**Comment by jacobbednarz** [comment]
I'm totally on board with you @markjaquith, hence the movements started in #358, #359 and #363 however this was still required for a 1:1 drop in with the existing plugin + repository structure. In the future, this won't be a factor.

**Comment by ggPixel** [comment]
Hi @jacobbednarz ,

WordPress version: 5.6.1
PHP version: 7.4
Previous plugin version: 3.8.9
Update method (UI/FTP/auto-upgrade/etc): Updated via the UI

Not sure if this is related but I am also using the W3Total Cache plugin.

Thank you.

**Comment by jacobbednarz** [comment]
fixed by #359. release is coming today.

**Comment by jacobbednarz** [comment]
Can you please attempt to update to v4.1.0 and let me know if this is resolved for you? The development dependencies should no longer be present.

**Comment by ggPixel** [comment]
Yep that worked like a charm. Thanks for the quick responses! :)
