### ISSUE TITLE
Version ^4 is no longer compatible with older PHP

### ISSUE THREAD

**Issue by stephandesouza** [cloudflare/Cloudflare-WordPress#368]
We're running a Wordpress fixed at PHP 7.0 and since the update to version 4.0 there is a breaking change to older PHP versions, like nullable (introduced at PHP 7.1)

![image](https://user-images.githubusercontent.com/159077/107500628-26216300-6b75-11eb-82a4-0a167430c650.png)

There's no problem with the upgrade at all, but I guess is time to update the PHP min version:

    define('CLOUDFLARE_MIN_PHP_VERSION',` '5.3.10');

**Comment by manatarms** [comment]
Made a PR here https://github.com/cloudflare/Cloudflare-WordPress/pull/370
We'll get this deployed soon. Thanks for the report.

**Comment by jacobbednarz** [comment]
should be fixed by #370

**Comment by jacobbednarz** [comment]
released in v4.1.0
