### ISSUE TITLE
Plugin version 4.0 - MockObject/Rule/InvocationOrder.php on line 27

### ISSUE THREAD

**Issue by saintdle** [cloudflare/Cloudflare-WordPress#369]
Updating to version 4.0 caused my website to go offline. Disabling plugins and re-enabling them, I hit the following for the CloudFlare plugin. 

Error message in WordPress

> Parse error: syntax error, unexpected ':', expecting ';' or '{' in /{root}/{Web_Dir}/public_html/wp-content/plugins/cloudflare/vendor/phpunit/phpunit/src/Framework/MockObject/Rule/InvocationOrder.php on line 27

Inside the referenced file, I have the line;

>     public function getInvocationCount(): int

Which I assume is causing the issue

**Comment by stephandesouza** [comment]
See #368

**Comment by jacobbednarz** [comment]
To confirm we've got the fix covered, what version of PHP and WordPress versions are you running?

**Comment by jacobbednarz** [comment]
🤞 fixed in #359

**Comment by saintdle** [comment]
> To confirm we've got the fix covered, what version of PHP and WordPress versions are you running?

PHP version: 5.6
WordPress: 4.9.16

**Comment by jacobbednarz** [comment]
@saintdle thanks for the update. unfortunately, you're running on an older version of PHP which we don't support anymore. you'll most likely need to stay on an older version of the plugin now. we've made the nessecary changes to the plugin to prevent breaking these installations however to continue benefiting from this plugin, i'd recommend upgrading your version of PHP and wordpress.
