### ISSUE TITLE
Wordpress Plugin does not handle enabling APO for subdomains

### ISSUE THREAD

**Issue by grayfox0014** [cloudflare/Cloudflare-WordPress#372]
Installing Wordpress on a subdomain and attempting to enable APO fails with a 400 Bad Request:

`proxyURL: "https://api.cloudflare.com/client/v4/zones/REDACTED/settings/automatic_platform_optimization"
value: {enabled: true, cf: false, wordpress: false, wp_plugin: false, hostnames: ["wordpress.scottcftest.cf"],…}
cache_by_device_type: true
cf: false
enabled: true
hostnames: ["wordpress.scottcftest.cf"]
wordpress: false
wp_plugin: false`

This fails because of the wp_plugin and wordpress values being set to false despite the WordPress plugin being installed, a workaround is to manually send the request with these values set to true.

Expected behaviour: APO is enabled through Wordpress plugin for WordPress instances installed on subdomains
Actual behaviour: APO is not enabled and fails with 400 bad request

**Comment by garrettgalow** [comment]
did you authorize the plugin with an api key or api token. Currently you need to use an API key in order to use APO with subdomains given some limitations that exist

**Comment by sejoker** [comment]
I can't reproduce the issue, please try to activate APO using API call:
https://api.cloudflare.com/#zone-settings-change-automatic-platform-optimization-for-wordpress-setting

make sure to set hostnames to only subdomain you are interested in, also please not this values should be set to true:
```
{ cf: true, wordpress: true, wp_plugin: true }
```

**Comment by mrw** [comment]
It works for me when sending the API call manually. The API call generated by the plugin UI sets `wp_plugin` to `false` in the API call it generates though, which is why I think it's failing.

**Comment by sejoker** [comment]
@mrw we are addressing the issue you described here: https://github.com/cloudflare/cloudflare-plugin-frontend/pull/169.
Please clear any server plugin cache and make sure your origin starts serving `cf-edge-cache` response header.

**Comment by jacobbednarz** [comment]
v4.3.0 includes the fixes mentioned above. please let me know if you are still experiencing the issue and we can reopen.
