### ISSUE TITLE
Cloudflare plugin not working after installation on latest version of wordpress

### ISSUE THREAD

**Issue by eazolotov** [cloudflare/Cloudflare-WordPress#375]
cloudflare plugin not working after installation on latest version of wordpress, just blank page(
in my console i see js error:
Uncaught TypeError: Cannot read property 'status' of undefined
at compiled.js?ver=4.1.0:35
at d.callback (compiled.js?ver=4.1.0:35)
at d.<anonymous> (compiled.js?ver=4.1.0:35)
at d.r.emit (compiled.js?ver=4.1.0:35)
at XMLHttpRequest.n.onreadystatechange (compiled.js?ver=4.1.0:35)
![2021-02-20 19-15-50](https://user-images.githubusercontent.com/12457572/108616493-57851300-7440-11eb-80fd-64372eee4f99.png)

**Comment by eazolotov** [comment]
it is was trouble with nginx headers

**Comment by sejoker** [comment]
@eazolotov thanks for reporting back 👍 .
