### ISSUE TITLE
v4.2.0 not work

### ISSUE THREAD

**Issue by apkmody** [cloudflare/Cloudflare-WordPress#377]
Hello, after I updated the plugin to 4.2.0 (from 4.1.0), it stops work.

PHP version 8
Wordpress 5.6.2

As you can see. After the update, I cannot see analytics and there is always have a toast show Not Found error when open Cloudflare page.

![2](https://user-images.githubusercontent.com/79179514/109597252-74110180-7b4a-11eb-8993-e99cb792859d.png)

![3](https://user-images.githubusercontent.com/79179514/109597294-868b3b00-7b4a-11eb-8825-f54b23eca57c.jpg)

**Comment by jacobbednarz** [comment]
@apkmody are you able to please check your logs and provide information about your installation? At a minimum information like:

- what version you upgraded from
- what version of PHP you're running
- error logs of the upgrade

The messages you're displaying are warnings, not errors and I don't think they are significant here.

**Comment by jacobbednarz** [comment]
the only not found error that i'm able to see is one that has been there for a while related to the analytics

```
==> /var/log/apache2/error.log <==
[Tue Mar 02 05:05:26.001585 2021] [php7:notice] [pid 823] [client ipv6:30092] [Cloudflare] ERROR: [CLIENT API] Array\n(\n    [type] => request\n    [path] => https://api.cloudflare.com/client/v4/zones/:zone_id/analytics/dashboard?since=-43200&action=cloudflare_proxy\n    [timeout] => 30\n    [method] => GET\n    [headers] => Array\n        (\n            [Content-Type] => application/json\n            [X-Auth-Email] => CF_EMAIL\n            [X-Auth-Key] => CF_API_KEY\n        )\n\n)\n , referer: http://ipv4/wp-admin/options-general.php?page=cloudflare
[Tue Mar 02 05:05:26.001768 2021] [php7:notice] [pid 823] [client ipv6:30092] [Cloudflare] ERROR: [CLIENT API] Array\n(\n    [type] => response\n    [reason] => Not Found\n    [code] => 404\n)\n , referer: http://ipv4/wp-admin/options-general.php?page=cloudflare
[Tue Mar 02 05:05:26.001860 2021] [php7:notice] [pid 823] [client ipv6:30092] [Cloudflare] ERROR: Not Found , referer: http://ipv4/wp-admin/options-general.php?page=cloudflare

```

**Comment by apkmody** [comment]
Hello,

I updated from 4.1.0 to 4.2.0. My PHP is ver 8.

As you can see. After the update, I cannot see analytics and there is always have a toast show Not Found error when open Cloudflare page.

**Comment by jacobbednarz** [comment]
did analytics work previously for you? i haven't dig too deep with PHP 8 and whether this plugin works on it as is.

could you check your PHP error logs for me and provide any errors there?

**Comment by jacobbednarz** [comment]
The REST zone analytics API was also sunset on the 1st of this month which may be why this that isn't showing (unrelated to the upgrade)

**Comment by garrettgalow** [comment]
we will track this in #378
