### ISSUE TITLE
Zone Analytics deprecated

### ISSUE THREAD

**Issue by garrettgalow** [cloudflare/Cloudflare-WordPress#378]
Old zone analytics were deprecated March 1 for GraphQL. We need to update the analytics page to prevent errors from being thrown.

**Comment by garrettgalow** [comment]
short term fix is likely deep link to dash analytics for now, while we determine if we can produce a similar experience in the plugin

**Comment by jacobbednarz** [comment]
changes will be coming through via cloudflare/cloudflare-plugin-frontend#165

**Comment by garrettgalow** [comment]
fixed in #382
