### ISSUE TITLE
Red banner not found in WP plugin (not valid)

### ISSUE THREAD

**Issue by Stirius** [cloudflare/Cloudflare-WordPress#379]
Hello,

we run APO plugin on our WP site. We get successful APO cache hits and it seems to be working well. In Cloudflare dashboard the domain is also connected and found. However, if we go to the plugin in WP then we see always for several seconds the red banner Not found which is weird.

![1](https://user-images.githubusercontent.com/5817246/109795080-d0415780-7c16-11eb-88cb-69ecbb46ea43.PNG)

**Comment by sejoker** [comment]
@Stirius we are aware about the issue, it is discussed here https://github.com/cloudflare/Cloudflare-WordPress/issues/378. I close it as duplicate.

**Comment by Stirius** [comment]
Ok, thanks. Because CF support was not able to answer me and let me know about anything. Just some nonsense not relevant to the issue...
