### ISSUE TITLE
Bug: Warning: file_get_contents of composer.json

### ISSUE THREAD

**Issue by kevinmrl** [cloudflare/Cloudflare-WordPress#380]
Latest version of CF plugin, when visiting WP admin Settings->Cloudflare dashboard.. You can see a red bar below in a page, and getting an error each time:

```
wp-content/plugins/cloudflare/src/WordPress/composer.json): failed to open stream: No such file or directory
```

**Comment by garrettgalow** [comment]
hm I'm not able to reproduce this, can you provide more details about your environment.
