### ISSUE TITLE
CloudFlare Messes Up Post Updates On WordPress Website

### ISSUE THREAD

**Issue by fidividi32** [cloudflare/Cloudflare-WordPress#381]
Hi guys,
We're trying to use CloudFlare APO with WordPress. When we completely disable CloudFlare/APO and route the DNS directly to the origin server, everything works ok. New articles are posted, updates/new articles can be seen across different browsers and different devices.

As soon as we enable CloudFlare APO with recommended settings, we start having random and weird delays (sometimes for a very long time - like hours) before we can see the new posts/articles in news sections or other areas of the website.
This is a very busy blog type website with hundreds of articles on daily basis, and sometimes new articles in matter of minutes. So delays as such are completely unacceptable.
We tried updating CloudFlare plugin to the latest version, disabling/enabling the recommended option (to be off) "Auto Purge Content On Update", nothing gives us the results we're after. The problem is resolved as soon as we Purge Everything and only then all browsers on all devices show the latest and most up-to-date content.
When we have the issue, the CF-Status is HIT, so we're confident this is not an issue from our end or whatever..
Any ideas?

**Comment by jacobbednarz** [comment]
@fidividi32 I would recommend you open a support ticket with Cloudflare to chat about this further as they will be able to advise on your specific zone configuration. If you determine something isn't behaving correctly following that, we can have a dig into a test reproduction case.

**Comment by apkmody** [comment]
Hey, after update the plugin to 4.2.0, the APO cache didn't purged after editing a post.

**Comment by fidividi32** [comment]
> Hey, after update the plugin to 4.2.0, the APO cache didn't purged after editing a post.

Interesting, yesterday before having these issues we updated the plugin to 4.2.0 as well, we were on 3.8.X..

Makes me think this is a bug with the new version then?

**Comment by fidividi32** [comment]
@jacobbednarz More than one person is reporting this issue, is it valid to still keep this issue closed? Just asking :-)

**Comment by sejoker** [comment]
@fidividi32  this is an issue with APO tiered cache rollout, unrelated to WordPress plugin version 4.2.0. We are reverting the change that introduced the problem, sorry for a regression.

**Comment by fidividi32** [comment]
> @fidividi32 this is an issue with APO tiered cache rollout, unrelated to WordPress plugin version 4.2.0. We are reverting the change that introduced the problem, sorry for a regression.

Thanks for your reply.

Is this issue resolved now? Where can I see more info on this regression and it's change/release note just to build confidence before we re-enable CF/plugin/etc...?

**Comment by sejoker** [comment]
The issue was resolved over the weekends. Other customers confirmed it's working for them: https://community.cloudflare.com/t/wordpress-apo-not-purging-cache/249502/10.

**Comment by fidividi32** [comment]
Hello,

But an that forum thread people are saying it's not working for them still..

fidividi@gmail.com
