### ISSUE TITLE
Unable to activate subdomains

### ISSUE THREAD

**Issue by Shadowsong87** [cloudflare/Cloudflare-WordPress#385]
I have installed the plugin on my multisite network, containing a primary and two secondary sites (subdomains). 

I have used the API token with the primary site and the global API key with the two secondary sites. If I try to turn on Automatic Platform Optimization, it does not save the setting. Refreshing the page shows it as not enabled. 

If I enable it from the Cloudflare portal, the primary domain shows as being active but not the subdomains.

If I view the console when clicking on the Cloudflare menu item in settings, I can see this error being displayed. It's the same for the main and subdomains. A repeat of the error happens if I click the on/off APO option. 

`compiled.js?ver=4.2.2:6 PATCH https://example.com/wp-admin/admin-ajax.php?action=cloudflare_proxy 405
d.end @ compiled.js?ver=4.2.2:6
Show 48 more frames
VM2337:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.callback (compiled.js?ver=4.2.2:2)
    at compiled.js?ver=4.2.2:6
    at d.callback (compiled.js?ver=4.2.2:6)
    at d.<anonymous> (compiled.js?ver=4.2.2:6)
    at d.r.emit (compiled.js?ver=4.2.2:6)
    at XMLHttpRequest.n.onreadystatechange (compiled.js?ver=4.2.2:6)`

**Comment by sejoker** [comment]
Please use API for activating APO on subdomains as a workaround as explained here: https://github.com/cloudflare/Cloudflare-WordPress/issues/372#issuecomment-801829196
