### ISSUE TITLE
Cache Purge for Menus and Widgets

### ISSUE THREAD

**Issue by Plinpod** [cloudflare/Cloudflare-WordPress#386]
Hello,

I was wondering how users have been handling the caching when changes are made to the header/footer menus and also to widgets such as Latest Posts that are site-wide. 

Thank you!

**Comment by sejoker** [comment]
We have plugin hooks to purge all cache on theme change: https://github.com/cloudflare/Cloudflare-WordPress/blob/master/cloudflare.loader.php#L67-L68
I think in similar fashion we should do on header/footer menus change, I haven't tested it, but I assume it could be already the case. If not feel free to make a PR for purging cache on menus change.

**Comment by sejoker** [comment]
please join the conversation  https://github.com/cloudflare/Cloudflare-WordPress/issues/275#issuecomment-804823964, closing as a duplicate.
