### ISSUE TITLE
Can't Detect Wordpress

### ISSUE THREAD

**Issue by trevordbc** [cloudflare/Cloudflare-WordPress#388]
My station's site is built on wordpress, the cloudflare plugin is enabled, I've connected it to the API key. This morning I decided to go ahead and upgrade to $20 / month as we're getting a tone of traffic and the site is getting incredibly slow in the mornings. When I go to enable APO - it tells me that it's not a Wordpress website...

**Comment by sejoker** [comment]
Hi @trevordbc  please try following the steps: ["What if my Cloudflare dashboard says it can't detect the WordPress plugin?"](https://support.cloudflare.com/hc/en-us/articles/360049822312-Understanding-Automatic-Platform-Optimization-APO-with-WordPress#h_01EEZY0SBQ8PFGVYGHS3H6B2BY). 
If it won't help please raise the support ticket and post the number here (I will have a look).

**Comment by sejoker** [comment]
please install the latest version of the plugin and navigate to APO card in the plugin, it should fix automatically your APO settings.
