### ISSUE TITLE
Cloudflare plugin saving account email and API Global Key at plain text php_errolog file

### ISSUE THREAD

**Issue by claudiobrandt** [cloudflare/Cloudflare-WordPress#389]
Hi,

I've recently noticed a php_errorlog file in one of my WordPress installations with JSON-formatted errors inserted into the system php_errorlog file that seems to come from the Cloudflare plugin. It seems this is a similar issue to the one addressed in [266](https://github.com/cloudflare/Cloudflare-WordPress/issues/266), but it may have crept back up somehow. 

```[06-Mar-2021 15:12:35 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => request
    [path] => https://api.cloudflare.com/client/v4/zones/ZONE-ID-STRING/purge_cache
    [timeout] => 30
    [method] => DELETE
    [headers] => Array
        (
            [Content-Type] => application/json
            [X-Auth-Email] => MY CLOUDFLARE ACCOUNT EMAIL
            [X-Auth-Key] => GLOBAL API KEY
        )

    [body] => {"files":["","http:\/\/dicio.eauladeingles.com\/"],"cfCSRFToken":null}
)

```
In the same php_errolog file there were several other Cache Purge errors that did not contain the account's email and the global API key. 

My sites are hosted by A2 Hosting:

Apache Version | 2.4.46
PHP Version | 7.2.34
MySQL Version | 10.3.24-MariaDB-cll-lve
Architecture | x86_64
Operating System | linux

I do not know what caused that error and therefore cannot provide steps to make it happen again. 

Thank you for your attention.

**Comment by jacobbednarz** [comment]
Thanks for this @claudiobrandt ! Unfortunately #266 didn't fix anything for the logging as it was focused on another fix however I've put together a fix for this one via cloudflare/cloudflare-plugin-backend#52. Once we merge that, we can pull into this repository and cut a release addressing the issue.
