### ISSUE TITLE
WordPress APO Returns Bad Request Message

### ISSUE THREAD

**Issue by cfmandon** [cloudflare/Cloudflare-WordPress#392]
I am tyring to enable APO from the wordpress cf plugin but get a bad request message. I am following what is outline in this guide: https://support.cloudflare.com/hc/en-us/articles/360049822312-Understanding-Automatic-Platform-Optimization-APO-with-WordPress?source=search for a subdomain setup. When the Bad request message is returned, I see no 500 request under the network tab. I have tried disabling all other plugins to see if it may be an interference issue but see the same result. Is there a way to further debug this kind of issue?

**Comment by sejoker** [comment]
I suggest API route to enable APO on subdomain: https://github.com/cloudflare/Cloudflare-WordPress/issues/372#issuecomment-801829196 while we are investigating the root cause of the problem.
