### ISSUE TITLE
APO not clearing category and tag pagination caches when posts are created

### ISSUE THREAD

**Issue by scottbuscemi** [cloudflare/Cloudflare-WordPress#394]
When a new post is added, blog category and tag pagination caches (ie `/category/:name/page/2`) are not cleared automatically.

**Comment by Plinpod** [comment]
Yep, this is an issue for me as well. It seems like an internal Cloudflare solution would be to use the Cache-Tags feature which is only available to Enterprise users. If it can be bundled into the APO package that would fix most of these issues since you can put a category tag on all of the pages the that require it.

**Comment by girirajnet** [comment]
Even if I edited a post also cache is not refreshing in the APO but without APO cloudflare is working fine .

It's fine in desktop but not in Mobile.

**Comment by mnwalker** [comment]
Related to this issue, but possibly needing a separate solution is the usecase of having a Page (not post) that has had a list of grid of recent posts inserted into it.
This suffers the exact same issue in here, that cache is not cleared after a new post added.
Hopefully (just implemented, waiting to verify) can have impact reduced to 1 hour through pagerule fix at https://github.com/cloudflare/Cloudflare-WordPress/issues/337

Ideal solution could be a custom box to list pages that are cleared after any post update in the APO plugin settings section.
Plus automatic detection of category/paging patterns so those require no effort.

**Comment by geeknotnerd** [comment]
Any update on this issue?

**Comment by asadkn** [comment]
Weird that the issue has been unresolved for years. Very odd to ignore paying customers like this.

**Comment by scottbuscemi** [comment]
This is still not in an acceptable state for use with most news sites...

**Comment by scottbuscemi** [comment]
This is still a thing AFAIK
