### ISSUE TITLE
Bad Request / ZONE_UPDATE_SETTING_ERROR for APO on Settings page

### ISSUE THREAD

**Issue by galbaras** [cloudflare/Cloudflare-WordPress#401]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.6.2

### Cloudflare-WordPress version

4.4.0

### PHP version

7.4.15

### Expected result

Green banner with success notifications

### Actual result

Red banner with "Bad request" and browser console showing `ZONE_UPDATE_SETTING_ERROR` notification with `id: "automatic_platform_optimization"` in the details.

### Steps to reproduce

1. Load settings page
2. Wait a few seconds for banner to appear
3. Check browser console

### Additional factoids

This is related to APO and from memory, started when APO was added to the plugin. I'm on the free plan, where APO isn't even available, so shouldn't even be attempted.

**Comment by jacobbednarz** [comment]
@sejoker this is similar to the issue I raised following the last round of testing I performed post release.

**Comment by sejoker** [comment]
@galbaras thanks for the report. Could you elaborate on  your site setup? Did you update your nameservers to point to Cloudflare? The error could be displayed if the site is not activated on Cloudflare.

**Comment by galbaras** [comment]
My nameservers have been pointing to Cloudflare for years. This seems to indicate that APO isn't activated, but the rest of the Cloudflare functions are OK.

My wp-admin/error_log is showing 3 instances of `[Cloudflare] ERROR: [CLIENT API] Array` after loading the settings page once.

I've also saved the full console log for your review, but it's probably best if I share it privately. Please advise.

**Comment by galbaras** [comment]
https://support.cloudflare.com/hc/requests/2123339

**Comment by galbaras** [comment]
@sejoker @garrettgalow Can you guys confirm you've received my console log? Any thoughts yet?

**Comment by sejoker** [comment]
@galbaras yes we did, here are Easter holidays in EMEA, I will look into it tomorrow.

**Comment by sejoker** [comment]
I'm working on the fix.

**Comment by sejoker** [comment]
The fix is live, please try again, it's addressed on API level.

**Comment by galbaras** [comment]
I'm not seeing any progress bars anymore, and no errors in the browser console. I think we're good.

Thank you!
