### ISSUE TITLE
Wordpress multilingual (with subdomains) and APO

### ISSUE THREAD

**Issue by rmollema** [cloudflare/Cloudflare-WordPress#406]
Dear all,

I'm struggling with APO in combination with a multilingual Wordpress setup, configured with a subdomain per language. 

To figure things out i've created a **testing** environment:

In CF DNS i've pointed these domains (proxied through CF) to the vps via A-records. 
https://webspecials.nl, 
https://german.webspecials.nl and 
https://spanish.webspecials.nl 

A brand new Wordpress install
WPML multilingual plugin, subdomain per language, 
APO plugin connected to a CF-account with APO-api-key.

All working like a charm.

BUT:  APO only picks up webspecials.com. caching for the subdomains is bypassed.

This is the output for main domain - webspecials.nl:
cf-apo-via: tcache
cf-cache-status: HIT
cf-edge-cache: cache,platform=wordpress

This is the output for german language - german.webspecials.nl
cf-apo-via: origin,host
cf-cache-status: BYPASS
cf-edge-cache: cache,platform=wordpress

In Cloudflare APO config screen i don't see subdomains, either: 
"Note: APO runs against the following list of hostnames:
webspecials.nl, www.webspecials.nl"

"WordPress plugin successfully detected on webspecials.nl, www.webspecials.nl."

Any help is highly appreciated!

Have a nice day all.

**Comment by sejoker** [comment]
I recommend to install Cloudflare WordPress plugin and activate APO in each of the sites:
- https://webspecials.nl,
- https://german.webspecials.nl
- https://spanish.webspecials.nl

**Comment by rmollema** [comment]
> I recommend to install Cloudflare WordPress plugin and activate APO in each of the sites:
> 

Thank you Sejoker. However: there is only one Wordpress instance in place. handling german and spanish is done via the WPML plugin.

**Comment by sejoker** [comment]
ok, than API call is your best option: https://api.cloudflare.com/#zone-settings-change-automatic-platform-optimization-for-wordpress-setting

pass all the subdomains to the list of hostnames: ["webspecials.nl", "german.webspecials.nl", "spanish.webspecials.nl"]

**Comment by rmollema** [comment]
It turned out that - even if it's just one instance of wordpress, you should still login to each language (read: subdomain) to be able to enable APO for that particular language. So after logging in via https://german.webspecials.nl  instead of https://webspecials.nl i was able to enable APO for German, too.

Problem solved!

Thanks again, @sejoker, for trying to help me out. Appreciated.
