### ISSUE TITLE
the plugin Cloudflare runs in the void

### ISSUE THREAD

**Issue by filmeur1970** [cloudflare/Cloudflare-WordPress#408]
Hello, I have activated APO several times in the plugin Cloudflare. On the one hand when I return to the plugin page the option has become inactive again (while I had activated it) and on the other hand the analysis runs hours in the void, it does not manage to finish at all. Can you please help me?

**Comment by jacobbednarz** [comment]
@filmeur1970 please follow the [issue template](https://github.com/cloudflare/Cloudflare-WordPress/issues/new?assignees=&labels=kind%2Fbug%2Cneeds-triage&template=bug.yml) when reporting bugs. it includes information that helps us help you.
