### ISSUE TITLE
The plugin runs in loop, without stopping

### ISSUE THREAD

**Issue by filmeur1970** [cloudflare/Cloudflare-WordPress#409]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.1

### Cloudflare-WordPress version

4.4.0

### PHP version

7.4

### Expected result

I want the plug-in to work for the site on OVH, I tried to disable DNSSEC on OVH but no result. I don’t know how to get Cloudflare to work on the setup.

### Actual result

The plugin installs normally, but it runs in a loop, it cannot initialize properly. From the Cloudflare page, on the account, he cannot fully test the plugin.

### Steps to reproduce

by activating the plugin under wordpress, it opens but loops indefinitely.

**Comment by jacobbednarz** [comment]
Are you able to try this again? We made some changes to the DNSSEC service to address an underlying issue which might be to blame here.

**Comment by filmeur1970** [comment]
Ultimately, it was because of the built-in security protocol that prevented him from working. Thank you.
