### ISSUE TITLE
Cannot install or update to 4.5.0

### ISSUE THREAD

**Issue by phamquangbaoplus** [cloudflare/Cloudflare-WordPress#415]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.0

### PHP version

8.0.5

### Expected result

The plugin will works

### Actual result

Error Details
=============
An error of type E_ERROR was caused in line 15 of the file /home/xxx/public_html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php. Error message: Uncaught Error: Failed opening required '/home/xxx/public_html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php' (include_path='.:/usr/local/lsws/lsphp80/share/pear:/usr/local/lsws/lsphp80/share/php') in /home/xxx/public_html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15
Stack trace:
#0 /home/xxx/public_html/wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(69): require()
#1 /home/xxx/public_html/wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(59): composerRequire386a6fce91e17b37d63cb251597d5bd5()
#2 /home/xxx/public_html/wp-content/plugins/cloudflare/vendor/autoload.php(7): ComposerAutoloaderInit386a6fce91e17b37d63cb251597d5bd5::getLoader()
#3 /home/xxx/public_html/wp-content/plugins/cloudflare/cloudflare.loader.php(3): require_once('...')
#4 /home/xxx/public_html/wp-content/plugins/cloudflare/cloudflare.php(49): require_once('...')
#5 /home/xxx/public_html/wp-admin/update.php(100): include('...')
#6 {main}
  thrown

### Steps to reproduce

Update from 4.4.0  to 4.5.0 from dashboard

**Comment by jacobbednarz** [comment]
Apologies but we don't officially support PHP 8 as of yet. CI runs with it and we have plans on adding full support but we're not quite there yet.

**Comment by phamquangbaoplus** [comment]
Hey, you guys should come up with a fix as soon as possible.

It is a popular plugin and a lot of people are getting the same error.

It requires minimum php 7.2, but doesn't support php 8. How many people can use your plugin with that requires?

Thanks.

**Comment by jacobbednarz** [comment]
I'm afraid it's as simple as that. 

Regardless of whether or not we want to support PHP 8, the WordPress plugin release process doesn't allow linting of PHP 8 and subsequently fails the SVN release. 

Until that is fixed, we cannot release PHP 8 compatible plugins.

**Comment by jacobbednarz** [comment]
I would also recommend following WordPress's [own advice](https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/) that PHP 8 in WordPress should be considered beta quality while they are working on upgrading core, infrastructure and the ecosystem to support it.

**Comment by garrettgalow** [comment]
A most recent link showing effectively the same in a nice table: https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

For WordPress 5.6 & 5.7 PHP 8 is beta

**Comment by Reforced** [comment]
In this [commit](https://github.com/cloudflare/Cloudflare-WordPress/commit/59784aef8871ff77d0f10867c5b833bb6dbd7d5a) it seems the bootstrapper for PHP 8 was removed, causing all the failures now. The missing bootstrap file is `/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php`. As fix you can manually add it again, it's available in the [Symfony respiratory](https://raw.githubusercontent.com/symfony/polyfill-intl-normalizer/main/bootstrap80.php). If you do roll-back to v4.4.0, make sure to disable auto-updating for the plugin.

**Comment by Wounded19** [comment]
We're on PHP 7.4 at the Pantheon, the same thing happened after the latest update. Had to revert to the previous version. I suppose it's not just 8.0 related.
