### ISSUE TITLE
Fatal error: missing Symfony polyfill bootstrap file for PHP 8.0.

### ISSUE THREAD

**Issue by jmichaelward** [cloudflare/Cloudflare-WordPress#416]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.0

### PHP version

8.0.6

### Expected result

I expected my site to continue to load after updating to the latest version of the Cloudflare plugin.

### Actual result

My site crashed.

### Steps to reproduce

1. Set up a WordPress instance using Composer with a repository for WPackagist on an environment running PHP 8+.
2. Run `composer require wpackagist-plugin/cloudflare` and make sure you've required your Composer autoload files.
3. Activate the Cloudflare plugin and try to load your site.

### Additional factoids

Here's the pertinent error:

```
PHP Fatal error:  Uncaught Error: Failed opening required '[my-path-to-my-install]/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php' (include_path='.:/usr/local/Cellar/php/8.0.6_1/share/php/pear') in [my-path-to-my-install]/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15
```
Reviewing the plugin files, I see there's a vendor directory in the Cloudflare plugin itself containing the symfony/polyfill-intl-normalizer package, and the bootstrap file attemps to load bootstrap80.php relative to the file path, but the file does not exist.

Edit: it appears there's a script in the composer.json file that intends to remove bootstrap80.php files, so this behavior seems to be intentional; however, the Symfony bootstrap.php file explicitly requires bootstrap80.php if on PHP 8.0 or above, which causes the fatal error. Is this plugin no longer PHP 8 compatible?

### References
The [symfony/polyfill-intl-normalizer](https://github.com/symfony/polyfill-intl-normalizer) package contains a bootstrap80.php file which is missing from Cloudflare's vendor directory. 

[commit#59784a](https://github.com/cloudflare/Cloudflare-WordPress/commit/59784aef8871ff77d0f10867c5b833bb6dbd7d5a) explicitly removes these files, and it looks like it was added just a few hours ago.

**Comment by jacobbednarz** [comment]
Duplicates #415
