### ISSUE TITLE
Wordpress Plugin 4.5.0 fails with php 8

### ISSUE THREAD

**Issue by desmccarthy** [cloudflare/Cloudflare-WordPress#418]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.0

### PHP version

8..05

### Expected result

Generates error, and can view website - from logs

=========

[Wed Jun 02 09:51:34.413253 2021] [php:warn] [pid 25409] [client 172.68.102.165:30114] PHP Warning:  require(/home/website/html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/bootstrap80.php): Failed to open stream: No such file or directory in /home/website/html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/bootstrap.php on line 19, referer: https://www.cellartours.com/wp-admin/plugins.php?plugin=cloudflare%2Fcloudflare.php
[Wed Jun 02 09:51:34.413392 2021] [php:error] [pid 25409] [client 172.68.102.165:30114] PHP Fatal error:  Uncaught Error: Failed opening required '/home/website/html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/bootstrap80.php' (include_path='.:/usr/share/php') in /home/website/html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/bootstrap.php:19\nStack trace:\n#0 /home/website/html/wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(69): require()\n#1 /home/website/html/wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(59): composerRequire386a6fce91e17b37d63cb251597d5bd5()\n#2 /home/website/html/wp-content/plugins/cloudflare/vendor/autoload.php(7): ComposerAutoloaderInit386a6fce91e17b37d63cb251597d5bd5::getLoader()\n#3 /home/website/html/wp-content/plugins/cloudflare/cloudflare.loader.php(3): require_once('...')\n#4 /home/website/html/wp-content/plugins/cloudflare/cloudflare.php(49): require_once('...')\n#5 /home/website/html/wp-admin/includes/plugin.php(2300): include('...')\n#6 /home/website/html/wp-admin/plugins.php(191): plugin_sandbox_scrape()\n#7 {main}\n  thrown in /home/website/html/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/bootstrap.php on line 19, referer: https://www.cellartours.com/wp-admin/plugins.php?plugin=cloudflare%2Fcloudflare.php

===========

### Actual result

see above

### Steps to reproduce

install version 4.5.0 cloudflare plugin

**Comment by jacobbednarz** [comment]
Duplicates #415
