### ISSUE TITLE
whole site went down after new upgrade version in wordpress 

### ISSUE THREAD

**Issue by cadentic** [cloudflare/Cloudflare-WordPress#420]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.0

### PHP version

8.0.5

### Expected result

activation

### Actual result

symphony vendor directories are missing

Cloudflare speeds up and protects your WordPress site.

Version 4.5.0 | By Cloudflare, Inc. 

### Steps to reproduce

1. upgrading the plugin

### Additional factoids

plugins failed to update and can not be activated within wordpress 

Operating System: | Linux | &nbsp;
-- | -- | --
Software: | Apache/2.4.41 (Ubuntu) | &nbsp;
MySQL version: | Source distribution v8.0.23 | &nbsp;
PHP Version: | 8.0.5 | &nbsp;
PHP Max Input Vars: | 1000 | &nbsp;
PHP Max Post Size: | 256M | &nbsp;
GD Installed: | Yes | &nbsp;
ZIP Installed: | Yes | &nbsp;
Write Permissions: | All right | &nbsp;
Elementor Library: | Connected

<div class="elementor-system-info-section elementor-system-info-wordpress" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 241, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; user-select: auto;">
Version: | 5.7.2 | &nbsp;
-- | -- | --\
WP Multisite: | No | &nbsp;
Max Upload Size: | 256 MB | &nbsp;
Memory limit: | 512M | &nbsp;
Permalink Structure: | /%postname%/ | &nbsp;
Language: | en-US | &nbsp;
Timezone: | 5.5 | &nbsp;
Admin Email: | 

Debug Mode: | Inactive | &nbsp;

</div><div class="elementor-system-info-section elementor-system-info-theme" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 241, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; user-select: auto;">
Theme | &nbsp; | &nbsp;
-- | -- | --
Name: | Twenty Twenty-One | &nbsp;
Version: | 1.3 | &nbsp;
Author: | the WordPress team | &nbsp;
Child Theme: | No | If you want to modify the source code of your theme, we recommend using a child theme.

</div><div class="elementor-system-info-section elementor-system-info-user" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 241, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; user-select: auto;">
User | &nbsp; | &nbsp;
-- | -- | --
Role: | administrator | &nbsp;
WP Profile lang: | en_US | &nbsp;
User Agent: | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

</div>

### References

wp-content/plugins/cloudflare/cloudflare.loader.php(3): require_once('...')\n#4 /var/www/wp-content/plugins/cloudflare/cloudflare.php(49): require_once('...')\n#5 /var/www/wp-admin/includes/plugin.php(2300): include('...')\n#6 /var/www/somepath', referer: plugins.php?plugin=cloudflare%2Fcloudflare.php

**Comment by gboudreau** [comment]
The whole stack for the error, on my site, was :

```
Uncaught Error: Failed opening required '/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php' (include_path='.:/usr/local/lib/php') in /wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15
Stack trace:
#0 /wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(69): require()
#1 /wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(59): composerRequire386a6fce91e17b37d63cb251597d5bd5()
#2 /wp-content/plugins/cloudflare/vendor/autoload.php(7): ComposerAutoloaderInit386a6fce91e17b37d63cb251597d5bd5::getLoader()
#3 /wp-content/plugins/cloudflare/cloudflare.loader.php(3): require_once('...')
#4 /wp-content/plugins/cloudflare/cloudflare.php(49): require_once('...')
#5 /wp-settings.php(391): include_once('...')
#6 /wp-config.php(114): require_once('...')
#7 /wp-load.php(37): require_once('...')
#8 /wp-login.php(12): require('...')
#9 {main}
```

And indeed, there is no `vendor/symfony/polyfill-intl-normalizer/bootstrap80.php` file...

**Comment by gboudreau** [comment]
Duplicates #415
