### ISSUE TITLE
Cloudflare Plugin 4.4.1 Has Problems with PHP 7

### ISSUE THREAD

**Issue by craigkeefner** [cloudflare/Cloudflare-WordPress#424]
I doublechecked today and 4.4.1 still has the problem on saving posts with Wordpress.
My system is Apache/2.2.15 (CentOS) , PHP 7.3.25, MySQL version: 5.6.41-log

Cloudflare suggested I report the bug

yevgen
Cloudflare Team

craig.keefner
9d
yes, seems like 4.5.0 was causing problems even on PHP 7, so 4.5.1 should make it compatible with PHP 7 but not PHP 8. Please report a bug: https://github.com/cloudflare/Cloudflare-WordPress/issues/new/choose if 4.5.1 causes issues with PHP 7.

**Comment by jacobbednarz** [comment]
Can you please explain the bug, a reproduction test case and any additional information? I'm afraid as is, this isn't enough for us to go on

**Comment by craigkeefner** [comment]
When you edit a post and then go to save it, Wordpress displays error.  This problem was identified on the Support forum (see yevgen thread). The problem was fixed with 4.4.1, but only for PHP 8. Yevgen suggested I post here. An error log is as follows:
Error Details
=============
An error of type E_ERROR was caused in line 290 of the file /var/www/html/sites/kioskindustry.org/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/Idn.php. Error message: Uncaught Error: Call to undefined function Symfony\Polyfill\Intl\Idn\mb_chr() in /var/www/html/sites/kioskindustry.org/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/Idn.php:290
Stack trace:
#0 /var/www/html/sites/kioskindustry.org/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/Idn.php(335): Symfony\Polyfill\Intl\Idn\Idn::mapCodePoints('kioskindustry.o...', Array, Object(Symfony\Polyfill\Intl\Idn\Info))
#1 /var/www/html/sites/kioskindustry.org/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/Idn.php(163): Symfony\Polyfill\Intl\Idn\Idn::process('kioskindustry.o...', Array, Object(Symfony\Polyfill\Intl\Idn\Info))
#2 /var/www/html/sites/kioskindustry.org/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-idn/bootstrap.php(133): Symfony\Polyfill\Intl\Idn\Idn::idn_to_ascii('kioskindustry.o...', Array, 1, NULL)
#3 /var/www/html/sites/kioskindustry.org/wp-content/plugins/cloudflare/src/WordPress/WordPressClientAPI.php(18): idn_to_ascii('kioskindustry.o...', 0, 1)

https://community.cloudflare.com/t/update-cf-plugin-wordpress/274280/3

Presumably 7.2 or higher should work. I am on 7.3.5

Ok?

**Comment by jacobbednarz** [comment]
Closing this out as it is unactionable in it's current state. If you'd like to submit a bug report, please follow the template which includes testing the latest stable release.
