### ISSUE TITLE
Wp-Cron not running as usual...

### ISSUE THREAD

**Issue by erikdemarco** [cloudflare/Cloudflare-WordPress#425]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5

### Cloudflare-WordPress version

4

### PHP version

7

### Expected result

Cron should run every minute, because woocommerce will run 'action_scheduler_run_queue' every minute. action scheduler is very important to run every minute if not some woocommerce task will run very very late.

### Actual result

Cron will not run every minute.

### Steps to reproduce

1. Install Wordpress
2. Install Woocommerce
3. Logout. Clear browser's site data including cookies.
4. Open browser's developer console, and move to network tab, and filter it using 'cron' as a keyword
5. Keep refreshing until wp-cron.php shows up (which will never happen until cloudflare TTL timeout)

**Comment by jacobbednarz** [comment]
Thanks for raising this @erikdemarco however I'm not quite sure how this is related to the plugin's functionality. I suspect this is more a configuration issue that has been enabled on your domain and isn't related to the plugin itself. I'd suggest you review your cache settings within the Cloudflare Dashboard (not WordPress) and work through it from there.

Please let me know if I've misunderstood the issue here however if I have, can you please elaborate more on why this a bug in the plugin?

**Comment by erikdemarco** [comment]
> Thanks for raising this @erikdemarco however I'm not quite sure how this is related to the plugin's functionality. I suspect this is more a configuration issue that has been enabled on your domain and isn't related to the plugin itself. I'd suggest you review your cache settings within the Cloudflare Dashboard (not WordPress) and work through it from there.
> 
> Please let me know if I've misunderstood the issue here however if I have, can you please elaborate more on why this a bug in the plugin?

Hi @jacobbednarz 

The way WP-Cron works is like this:
Every time a person calls one of your page. Every time WordPress goes to work, it checks to see if there are any cron jobs that need done.
If cloudflare makes every single call/pageload not hitting our server. How can WP-Cron know its time to run? Because there is nothing triggering the WP itself to run.

How to fix this is, Cloudflare plugin needs to check what it the smallest interval of wp-cron event. And then it should make 1 pageload for 1 visitor to hit our server. So WP-Cron can be triggered.

**Comment by jacobbednarz** [comment]
I still don't think that is an issue for the plug-in to solve. Have you had a look at overriding cache options for that path via the dashboard?
