### ISSUE TITLE
No cache when added to cart

### ISSUE THREAD

**Issue by erikdemarco** [cloudflare/Cloudflare-WordPress#427]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.8

### Cloudflare-WordPress version

4.5

### PHP version

8

### Expected result

The correct behaviour should be:
-) Cache invalidate only when origin server send cookie header.
-) Cookie exist in request header shouldn't invalidate cache. If you do it will make hit ratio so low. 

### Actual result

When "woocommerce_" cookie exist in request header it invalidate cache

### Steps to reproduce

1. Install woocommerce
2. Browse page when logged out
3. Add something to cart
4. Browse any page, cache will be bypassed

### Additional factoids

1. Woocommerce is already smart enough, when you request a page. It will refresh the minicart automatically with no cache header.
2. What is the first purpose people installing cloudflare plugin? To cache most of the request, so it will save bandwidth and resources of origin server. But if you invalidate cache just because there is a "wp_" or "woocommerce_" cookie in the request header. It's very wrong. We only need to invalidate cache when origin server send response header containing a cookie.
3. Compare cloudflare official plugin with WP cloudflare and litespeed cache. Or any disk cache plugin Or any static CDN . All of them works like I mention. They invalidate cache if the origin site have cookie in response header or the user is logged in. Not invalidate cache when request header contain cookie for logged out user. Nothing works like cloudflare do. Can you please tell me the reasoning CF developer do this? 
4. What is the advantage of paying $5/month for APO. But getting much more lower cache hit ratio than using WP cloudflare plugin with free plan?

**Comment by jacobbednarz** [comment]
I don't think this is something the plugin should be solving as the use cases vary greatly and I don't think we could cover all use cases (plugin, themes). Instead, you can adjust your own Page Rules to handle cache negotiation on particular routes. Generally, I recommend using the "respect origin cache control" setting for most pages and setting your cache TTLs and directives in the application side for full control.

**Comment by jacobbednarz** [comment]
> What is the first purpose people installing cloudflare plugin? To cache most of the request, so it will save bandwidth and resources of origin server. But if you invalidate cache just because there is a "wp_" or "woocommerce_" cookie in the request header. It's very wrong. We only need to invalidate cache when origin server send response header containing a cookie.

You can see the [features list in the readme.txt](https://github.com/cloudflare/Cloudflare-WordPress#features)

> Compare cloudflare official plugin with WP cloudflare and litespeed cache. Or any disk cache plugin Or any static CDN . All of them works like I mention. They invalidate cache if the origin site have cookie in response header or the user is logged in. Not invalidate cache when request header contain cookie for logged out user. Nothing works like cloudflare do. Can you please tell me the reasoning CF developer do this?

Cloudflare can be configured to work however you need it to. The decision of _how_ is up to you and how your system works.

> What is the advantage of paying $5/month for APO. But getting much more lower cache hit ratio than using WP cloudflare plugin with free plan?

Check out https://developers.cloudflare.com/automatic-platform-optimization/. It has the explanation, feature list and ways to confirm it works for you.

**Comment by erikdemarco** [comment]
@jacobbednarz Hi, Yes I tried "respect origin cache control" before, And doesnt work. Maybe APO have more priority than this setting?

**Comment by sejoker** [comment]
@erikdemarco thanks for bringing this topic for discussion. 

> I tried "respect origin cache control" before, And doesnt work. Maybe APO have more priority than this setting?

Correct APO TTL has higher priority that cache-control header. For this use case I'm planning to work on adding support for `cdn-cache-control` and `cloudflare-cnd-cache-control` that could override APO TTL:
https://community.cloudflare.com/t/cache-everything-json-expiring-at-00h-utc-everyday/285269/17?u=yevgen

> Compare cloudflare official plugin with WP cloudflare and litespeed cache. Or any disk cache plugin Or any static CDN . All of them works like I mention. They invalidate cache if the origin site have cookie in response header or the user is logged in. Not invalidate cache when request header contain cookie for logged out user. Nothing works like cloudflare do. Can you please tell me the reasoning CF developer do this?

With APO we tried to be cautious. Caching something that shouldn't be cached is the worst result for a product as APO. I will research your claims here, maybe we can support your suggested idea.

**Comment by erikdemarco** [comment]
> For this use case I'm planning to work on adding support for cdn-cache-control and cloudflare-cnd-cache-control that could override APO TTL:

@sejoker This is very nice feature. So for example I want cloudflare to cache product page. I just place "cdn-cache-control" in response header and CF will respect this even if user have "woocommerce_" in request header. Right? And how to make APO cache product page only for logged out user and do not cache for logged in user? Because as far as I know the cache key for KV storage is 'a combination of a zone identifier and the URL'

**Comment by sejoker** [comment]
I think this is a valid use case we should investigate for APO.

**Comment by pjv** [comment]
Unstaling the issue because this would make a pretty big performance difference on busy woocommerce sites.

**Comment by pjv** [comment]
bump.

**Comment by pjv** [comment]
How did the bot mark this issue as completed when there has not been a commit in this repo in almost a year?

**Comment by jordantrizz** [comment]
> With APO we tried to be cautious. Caching something that shouldn't be cached is the worst result for a product as APO. I will research your claims here, maybe we can support your suggested idea.

Look to other caching plugins; as mentioned before, they don't act the same. Furthermore, there should be options within the plugin for excluding URI's from APO cache and force URI's to be cached by APO via the headers mentioned above by @sejoker. Moving the control closer to WordPress would be a better overall user experience versus having to make changes to Cloudflare rules.

> How did the bot mark this issue as completed when there has not been a commit in this repo in almost a year?

Pretty should they have it automated that if an issue is set to stale, it's closed as completed after a specific number of days.

Unfortunately, there isn't a huge amount of resources from Cloudflare to improve this plugin, so it's simply getting one-off updates and maintenance releases.
