### ISSUE TITLE
No way to change API key after it's been entered

### ISSUE THREAD

**Issue by galbaras** [cloudflare/Cloudflare-WordPress#428]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.1

### PHP version

7.4

### Expected result

The API token field should always be displayed on the settings tab, even when there's an error connecting to Cloudflare.

### Actual result

403 from https://api.cloudflare.com/client/v4/zones?action=cloudflare_proxy causing 500 for the calling script and the contents of the settings page never load.

### Steps to reproduce

1. Configure the plugin with a valid API key
2. Move the site to another account
3. Once the site is moved (new nameservers verified), display the plugin's page

### Additional factoids

This happened to me after moving a site to another domain. Fortunately, I could just edit the API token setting in wp_options using phpMyAdmin, but this also exposes the issue of the token not being encrypted, which could be a separate issue.

**Comment by sejoker** [comment]
This is possible to do, by going to Plugins and deactivating Cloudflare, then you can activate it again and enter the token:
<img width="110" alt="Screenshot 2021-08-04 at 11 14 23" src="https://user-images.githubusercontent.com/125466/128164501-cd6cb369-4a53-48b9-8145-b3e8b189bacb.png">

**Comment by galbaras** [comment]
Thank you. I've just confirmed this and it works, but I still think this should be possible to trigger without deactivating the plugin.

Most plugins retain their settings when they are deactivated. Therefore, I had no reason to expect yours to be any different, and I didn't even try. This is a rare case, but still.
