### ISSUE TITLE
v4.5.1 admin interface broken

### ISSUE THREAD

**Issue by robertnabbe** [cloudflare/Cloudflare-WordPress#430]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.1

### PHP version

7.3

### Expected result

I expected the plugin interface to load.

### Actual result

Instead, I'm getting an infinite loading animation.

### Steps to reproduce

Navigate to `/wp-admin/options-general.php?page=cloudflare#/home` (Settings > Cloudflare)

On page load, the first Ajax call to `/wp-admin/admin-ajax.php?action=cloudflare_proxy&proxyURL=zones&proxyURLType=CLIENT` returns data just fine.

However, the 2nd call, to `/wp-admin/admin-ajax.php?action=cloudflare_proxy&proxyURL=zones&proxyURLType=CLIENT` fails with a 500 error. The debug.log reads:

```php
[04-Aug-2021 21:33:43 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => request
    [path] => https://api.cloudflare.com/client/v4/zones?action=cloudflare_proxy
    [timeout] => 30
    [method] => GET
    [headers] => Array
        (
            [Content-Type] => application/json
            [X-Auth-Email] => REDACTED
            [X-Auth-Key] => REDACTED
        )

)

[04-Aug-2021 21:33:43 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => response
    [reason] => Forbidden
    [code] => 403
)

[04-Aug-2021 21:33:43 UTC] [Cloudflare] ERROR: Forbidden
[04-Aug-2021 21:33:43 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CF\API\Request::__construct(), 3 passed in /{server-path-redacted}/wp-content/plugins/cloudflare/src/WordPress/ClientActions.php on line 47 and exactly 4 expected in /{server-path-redacted}/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/API/Request.php:19
Stack trace:
#0 /{server-path-redacted}/wp-content/plugins/cloudflare/src/WordPress/ClientActions.php(47): CF\API\Request->__construct('GET', 'zones/', Array)
#1 /{server-path-redacted}/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Router/DefaultRestAPIRouter.php(62): CF\WordPress\ClientActions->returnWordPressDomain()
#2 /{server-path-redacted}/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Router/RequestRouter.php(59): CF\Router\DefaultRestAPIRouter->route(Object(CF\API\Request))
#3 /{server-path-redacted}/wp-content/plugins/cloudflare/src/WordPress/Pro in /{server-path-redacted}/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/API/Request.php on line 19
```

(**edit**: forgot to add the JS errors)
As a result of this 500 error, the JS function handling the return of the ajax call fails to handle the 500 response properly, and prevents the interface from loading further:

```js
compiled.js?ver=4.5.1:20 GET https://{redacted}/wp-admin/admin-ajax.php?action=cloudflare_proxy&proxyURL=zones&proxyURLType=CLIENT 500
compiled.js?ver=4.5.1:20 Uncaught TypeError: Cannot read property 'status' of undefined
    at compiled.js?ver=4.5.1:20
    at d.callback (compiled.js?ver=4.5.1:20)
    at d.<anonymous> (compiled.js?ver=4.5.1:20)
    at d.r.emit (compiled.js?ver=4.5.1:20)
    at XMLHttpRequest.n.onreadystatechange (compiled.js?ver=4.5.1:20)
```

The debug.log almost seem to imply an issue with the our credentials, which would be very odd as the plugin worked fine in the past (and presumably API keys don't expire?). Granted, it was a few weeks ago since I had to purge the CF cache, so I'm unsure _when_ exactly this issue started happening.

### Additional factoids

This site is the 'main' site of a multi-site setup.

Also, the reason why I'm creating a new ticket (as https://github.com/cloudflare/Cloudflare-WordPress/issues/423 seems similar), is because downgrading the plugin to 4.5.0 does **NOT** fix the issue.

### References

https://github.com/cloudflare/Cloudflare-WordPress/issues/423

**Comment by conversionclan** [comment]
Same here:
![cloudflare](https://user-images.githubusercontent.com/78951939/129371175-d94af560-bbe8-4c92-901f-b8cd7308eb72.png)

**Comment by brandonkramer** [comment]
Got this problem as well.
[
![Cloudflare+Configuration+%E2%80%B9+Pool+Cleaner+Planet+%E2%80%94+WordPress+2021-08-30+21-52-08](https://user-images.githubusercontent.com/17217494/131397289-c19fbb19-d487-44bf-81e9-022aa7b99002.png)
](url)


Logs:
`[30-Aug-2021 19:50:52 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => request
    [path] => https://api.cloudflare.com/client/v4/zones?action=cloudflare_proxy
    [timeout] => 30
    [method] => GET
    [headers] => Array
        (
            [Content-Type] => application/json
            [X-Auth-Email] => REDACTED
            [X-Auth-Key] => REDACTED
        )

)
 
[30-Aug-2021 19:50:52 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => response
    [reason] => Forbidden
    [code] => 403
)
 
[30-Aug-2021 19:50:52 UTC] [Cloudflare] ERROR: Forbidden 
[30-Aug-2021 19:50:52 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CF\API\Request::__construct(), 3 passed in /home/403928.cloudwaysapps.com/anzheajkzs/public_html/wp-content/plugins/cloudflare/src/WordPress/ClientActions.php on line 47 and exactly 4 expected in /home/403928.cloudwaysapps.com/anzheajkzs/public_html/wp-content/plugins/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/API/Request.php:19
Stack trace:`

Temporary fix:
1. Deactivate plugin
2. Activate the plugin
3. Enter email + API
4. Seems to work again

**Comment by nooblag** [comment]
Reporting same behaviour: "I'm getting an infinite loading animation."

Cloudflare plugin 4.5.1, using PHP 8 on Wordpress 5.8.1, console log for Firefox 92.0:

```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
compiled.js:41  action @@router/LOCATION_CHANGE @ 18:42:25.965
compiled.js:41  action CONFIG_FETCH @ 18:42:25.971
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:25.973
compiled.js:41  action @@router/LOCATION_CHANGE @ 18:42:26.003
compiled.js:41  action CONFIG_FETCH_SUCCESS @ 18:42:29.609
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.609
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.609
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.610
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.610
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.611
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.611
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.611
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.612
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.612
compiled.js:41  action CONFIG_UPDATE_BY_KEY @ 18:42:29.613
compiled.js:41  action INTL_FETCH_TRANSLATIONS @ 18:42:29.613
compiled.js:41  action INTL_FETCH_TRANSLATIONS_SUCCESS @ 18:42:29.664
compiled.js:41  action APPLICATION_INIT @ 18:42:29.664
compiled.js:41  action @@router/LOCATION_CHANGE @ 18:42:31.351
compiled.js:41  action @@router/LOCATION_CHANGE @ 18:42:31.368
DevTools failed to load source map: Could not load content for https://DOMAIN.COM/wp-content/plugins/cloudflare/stylesheets/components.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
compiled.js:41  action USER_LOGIN @ 18:42:42.604
compiled.js:41  action USER_LOGIN_SUCCESS @ 18:42:46.584
compiled.js:41  action @@router/CALL_HISTORY_METHOD @ 18:42:46.614
compiled.js:41  action ZONES_FETCH @ 18:42:46.631
compiled.js:41  action @@router/CALL_HISTORY_METHOD @ 18:42:46.636
compiled.js:41  action @@router/LOCATION_CHANGE @ 18:42:46.643
compiled.js:41 GET https://DOMAIN.COM/wp-admin/admin-ajax.php?action=cloudflare_proxy&proxyURL=zones&proxyURLType=CLIENT 500
d.end @ compiled.js:41
o @ compiled.js:41
a @ compiled.js:41
f @ compiled.js:6
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:41
dispatch @ compiled.js:41
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:41
dispatch @ compiled.js:41
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:6
(anonymous) @ compiled.js:41
d.callback @ compiled.js:41
(anonymous) @ compiled.js:41
r.emit @ compiled.js:41
n.onreadystatechange @ compiled.js:41
XMLHttpRequest.send (async)
d.end @ compiled.js:41
o @ compiled.js:41
i @ compiled.js:41
a @ compiled.js:30
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:41
value @ compiled.js:41
onClick @ compiled.js:41
r @ compiled.js:16
i @ compiled.js:16
u @ compiled.js:16
d @ compiled.js:6
v @ compiled.js:6
r @ compiled.js:30
processEventQueue @ compiled.js:6
r @ compiled.js:41
handleTopLevel @ compiled.js:41
a @ compiled.js:41
perform @ compiled.js:6
batchedUpdates @ compiled.js:41
a @ compiled.js:6
dispatchEvent @ compiled.js:41
compiled.js:41 Uncaught TypeError: Cannot read property 'status' of undefined
    at compiled.js:41
    at d.callback (compiled.js:41)
    at d.<anonymous> (compiled.js:41)
    at d.r.emit (compiled.js:41)
    at XMLHttpRequest.n.onreadystatechange (compiled.js:41)
(anonymous) @ compiled.js:41
d.callback @ compiled.js:41
(anonymous) @ compiled.js:41
r.emit @ compiled.js:41
n.onreadystatechange @ compiled.js:41
XMLHttpRequest.send (async)
d.end @ compiled.js:41
o @ compiled.js:41
a @ compiled.js:41
f @ compiled.js:6
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:41
dispatch @ compiled.js:41
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:41
dispatch @ compiled.js:41
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:6
(anonymous) @ compiled.js:41
d.callback @ compiled.js:41
(anonymous) @ compiled.js:41
r.emit @ compiled.js:41
n.onreadystatechange @ compiled.js:41
XMLHttpRequest.send (async)
d.end @ compiled.js:41
o @ compiled.js:41
i @ compiled.js:41
a @ compiled.js:30
(anonymous) @ compiled.js:30
(anonymous) @ compiled.js:41
value @ compiled.js:41
onClick @ compiled.js:41
r @ compiled.js:16
i @ compiled.js:16
u @ compiled.js:16
d @ compiled.js:6
v @ compiled.js:6
r @ compiled.js:30
processEventQueue @ compiled.js:6
r @ compiled.js:41
handleTopLevel @ compiled.js:41
a @ compiled.js:41
perform @ compiled.js:6
batchedUpdates @ compiled.js:41
a @ compiled.js:6
dispatchEvent @ compiled.js:41
```

**Comment by Evert-Arends** [comment]
I'm running php8.0-fpm, @sethtregenna's answer works.

1. sudo apt install php8.0-mbstring
2. sudo systemctl restart php8.0-fpm.service

Fixed it for me

**Comment by lkhrs** [comment]
I have the same issue (error 500 on `/wp-admin/admin-ajax.php?action=cloudflare_proxy&proxyURL=zones&proxyURLType=CLIENT` when loading the plugin page) on WordPress.com where I am unable to install PHP extensions like mbstring. I have disabled all plugins and themes on 4 sites, and switched PHP versions between 7.4, 8.0, and 8.1.

**Comment by arbitrarily** [comment]
> 

thank you for posting this - this was it for me as well

**Comment by joris2110** [comment]
I have the same issue on 4.11.0 aswell
mbstring is installed and im running on php 7.4
