### ISSUE TITLE
APO is causing AJAX requests to fail

### ISSUE THREAD

**Issue by RaeesBhatti** [cloudflare/Cloudflare-WordPress#432]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.8

### Cloudflare-WordPress version

4.5.1

### PHP version

7.4.22 (Supports 64bit values)

### Expected result

[WordPress Nonces](https://codex.wordpress.org/WordPress_Nonces) are not cached so that API requests relying on them work correctly.

### Actual result

WordPress Nonces are cached and API requests start to fail on cached pages with 403 status code.

### Steps to reproduce

It's a bit tricky to reproduce but here's the flow:

1. Create an `nopriv` [AJAX endpoint in WordPress](https://codex.wordpress.org/AJAX_in_Plugins)
2. Turn on Cloudflare APO
3. Visit the page as a guest to make sure it's cached (incognito or another browser) and verify that the API call is working
4. Visit the page after 24 hours with the same browser as guest and make the API call
5. Observe 403 response code for API request

### Additional factoids

My website is running on [WordPress.com](https://www.wordpress.com) platform with premium Jetpack on.

**Comment by RaeesBhatti** [comment]
Is this the right platform for this issue or should I contact Cloudflare support?

**Comment by sejoker** [comment]
@RaeesBhatti please use Cloudflare Page rule [Edge Cache TTL](https://developers.cloudflare.com/automatic-platform-optimization/reference/page-rule-integration) to limit caching for the page (based on TTL of the nonce), APO will respect it and won't cache page longer.

**Comment by sejoker** [comment]
I mentioned it here as well: https://blog.cloudflare.com/apo-post-launch-report/#plugins-that-generate-html.

**Comment by RaeesBhatti** [comment]
Thank you!
