### ISSUE TITLE
4.7.0: allow short-circuiting Hooks::getPostRelatedLinks(), reduce dead-end work

### ISSUE THREAD

**Issue by lkraav** [cloudflare/Cloudflare-WordPress#449]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.8.2

### Cloudflare-WordPress version

4.7.0

### PHP version

7.4

### Expected result

ISBAT short-circuit an expensive operation like `Hooks::getPostRelatedLinks()` for posts that I know should never trigger a cache purge. #197 is a useful start, but it doesn't allow skipping dead work altogether.

We should follow [WP Core principles](https://core.trac.wordpress.org/browser/tags/5.8.2/src/wp-includes/class-wp-oembed.php#L374) here.

### Actual result

`Hooks::getPostRelatedLinks()` always runs, and then we often have to throw the whole result away with `add_filter cloudflare_purge_by_url __return_empty_array`.

### Steps to reproduce

Implementation should be something like

```php
        ...
        $pre = apply_filters( 'pre_cloudflare_purge_by_url', null, $postId);

        if (null !== $pre) {
            return $pre;
        }

        $urls = $this->getPostRelatedLinks($postId);
        $urls = apply_filters('cloudflare_purge_by_url', $urls, $postId);
        ...
```

**Comment by jacobbednarz** [comment]
can you please elaborate on what sort of dead work you're referring to? #454 improves the efficiency of what we are sending to the cache purge service but i'm interested to hear what isn't covered by this.

**Comment by lkraav** [comment]
#454 is a great start.

This issue could would help solve anything remaining, that upstream either doesn't know or doesn't care about in individual apps.

Currently, the most important thing indeed is to stop cache purges on non-public post types.
