### ISSUE TITLE
High number of calls to wp-cron.php causing CPU spike

### ISSUE THREAD

**Issue by dipens** [cloudflare/Cloudflare-WordPress#451]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.8.1

### Cloudflare-WordPress version

Reproducable on both 3.4.1 and 4.7.0

### PHP version

7.4

### Expected result

There are negligible calls to wp-cron.php which doesn't cause CPU spike.

### Actual result

There are high number of calls to wp-cron.php causing CPU spike.

### Steps to reproduce

1. Install Wordpress 5.8.1
2. Install CF plugin 4.7.0.
3. Generate random traffic on the site.
4. Notice there is a spike on CPU.

### Additional factoids

There are a bunch of other stuff installed on my Docker file. I can provide them if required.

This issue was confirmed by CF support. (Ticket number can be provided upon request)

**Comment by jacobbednarz** [comment]
apologies for missing this one but there isn't enough information here for me to replicate or diagnose the issue. are you able to elaborate on the conditions that are causing this? it doesn't happen with a vanilla wordpress install with just the cloudflare plugin present.
