### ISSUE TITLE
Wordpress APO Category Pages Not Being Purged

### ISSUE THREAD

**Issue by dreamjobma** [cloudflare/Cloudflare-WordPress#453]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

Latest

### Cloudflare-WordPress version

Latest

### PHP version

8.0

### Expected result

Related Categories cache must be cleared when updating a post

### Actual result

Related Categories cache are not cleared when updating a post

### Steps to reproduce

Create new post.
Related categorie does not contain the new post, meaning categorie cache is not cleared.

### References

When a new post is published, the Cloudflare cache is not being purged for the related category pages. A manual purge does work, but my understanding is that the category pages are supposed to be purged automatically and re-cached when there is new content published.

**Comment by jacobbednarz** [comment]
from reading the code, i don't think categories are included for cache purges - https://github.com/cloudflare/Cloudflare-WordPress/blob/4fe29a799f6b73abf55c5569f5f132cbc45d9b17/src/WordPress/Hooks.php#L218

**Comment by Jineshpanchal** [comment]
We are also facing similar issues.

**Comment by Jineshpanchal** [comment]
We are facing this issue since long time and sharing once more time here...
we have also raised on official channel but no resolution "

https://support.cloudflare.com/hc/en-us/requests/2530764?page=1

Kindly check the above link for every minute details.

**Comment by negrusti** [comment]
Debugging this now - one issue is that the parent categories are not handled in the code. For example:
This will be flushed for the post belonging to category "mexico"
https://example.com/category/world/mexico/
but this one won't be flushed
https://example.com/category/world/
This requires some recursive code
