### ISSUE TITLE
Page cache isn't purged when updated with APO

### ISSUE THREAD

**Issue by Dalias96** [cloudflare/Cloudflare-WordPress#464]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.9.2

### Cloudflare-WordPress version

4.8.3

### PHP version

7.4.28

### Expected result

Page Cache should be purged when page is updated.

### Actual result

Page cache is not purged when page is updated.

### Steps to reproduce

1. Modify Page
2. Update page
3. Visit page on incognito - changes are not made

Now Purge Cache manually from settings - updated content is present.

### Additional factoids

Post are purged fine.

**Comment by Dalias96** [comment]
Since i cannot create branch in this repo, here is possible solution:

![image](https://user-images.githubusercontent.com/84038002/161704824-25e0a747-4ec5-488d-888b-6c5d84640056.png)

[WP reference for that function](https://developer.wordpress.org/reference/functions/is_post_type_viewable/)

Locally tested - saving page triggers cache purge.

**Comment by lkraav** [comment]
Condition should test for "not viewable", right? `if ! is_post_type_viewable()`

We're also experiencing APO cache purge issues since recent Hooks refactoring.

**Comment by Dalias96** [comment]
> Condition should test for "not viewable", right? `if ! is_post_type_viewable()`
> 
> We're also experiencing APO cache purge issues since recent Hooks refactoring.

Yeah, You're right, there should be negation.

**Comment by jacobbednarz** [comment]
if you would like to submit a fix for this @Dalias96, you can fork the repository and send a pull request. check out https://docs.github.com/en/get-started/quickstart/fork-a-repo for a guide on doing it.

**Comment by Dalias96** [comment]
@jacobbednarz thanks! Here's link for PR https://github.com/cloudflare/Cloudflare-WordPress/pull/466

**Comment by Dalias96** [comment]
@lkraav did live patching made purging work?

**Comment by lkraav** [comment]
> did live patching made purging work?

I enabled debug in config.json, and all page updates have triggered appropriate purge URL lists.
