### ISSUE TITLE
Update psr/log to 3.0

### ISSUE THREAD

**Issue by Log1x** [cloudflare/Cloudflare-WordPress#470]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

Latest

### Cloudflare-WordPress version

Latest

### PHP version

8.0

### Expected result

I currently have a project that uses `psr/log` but upon updating to 3.0 I'm getting an error thrown from Cloudflare's implementation due to the `::debug` declaration when extending `AbstractLogger`.

I'd like to request that `psr/log` be updated to 3.0 on the plugin to resolve the conflict if possible.

I'm open to doing a PR for this.

### Actual result

```sh
2022/05/03 07:40:24 [error] 11363#11363: *29714057 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CF\Integration\DefaultLogger::debug($message, array $context = []) must be compatible with Psr\Log\AbstractLogger::debug(Stringable|string $message, array $context = []): void in /home/example/webapps/example-staging/releases/20220503073807/web/app/plugins/cloudflare/src/Integration/DefaultLogger.php on line 42"
```

### Steps to reproduce

1. Require psr/log into your site/project (e.g. through composer).
2. Get thrown the error above due to declaration incompatibility.

**Comment by jacobbednarz** [comment]
you're welcome to submit a PR to address this if you'd like it upgraded. just note our requirements for php 7.x and 8.x in your testing.

**Comment by Log1x** [comment]
ahh wasn't thinking about `psr/log`'s support of php 7.x. i guess that kills this issue then. ill figure out another way, thanks!
