### ISSUE TITLE
Hooks.php bug crash site on delete things...

### ISSUE THREAD

**Issue by anhphammody** [cloudflare/Cloudflare-WordPress#475]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.9.3

### Cloudflare-WordPress version

4.9.1

### PHP version

8.0

### Expected result

Delete media

### Actual result

An error of type E_ERROR was caused in line 172 of the file /www/wwwroot/[DOMAIN/wp-content/plugins/cloudflare/src/WordPress/Hooks.php](http://DOMAIN/wp-content/plugins/cloudflare/src/WordPress/Hooks.php). Error message: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /www/wwwroot/[DOMAIN/wp-content/plugins/cloudflare/src/WordPress/Hooks.php:172](http://DOMAIN/wp-content/plugins/cloudflare/src/WordPress/Hooks.php:172)
Stack trace:
#0 /www/wwwroot/[DOMAIN/wp-content/plugins/cloudflare/src/WordPress/Hooks.php(172)](http://DOMAIN/wp-content/plugins/cloudflare/src/WordPress/Hooks.php(172)): array_merge()
#1 /www/wwwroot/[DOMAIN/wp-includes/class-wp-hook.php(309)](http://DOMAIN/wp-includes/class-wp-hook.php(309)): CF\WordPress\Hooks->purgeCacheByRelevantURLs()
#2 /www/wwwroot/[DOMAIN/wp-includes/class-wp-hook.php(331)](http://DOMAIN/wp-includes/class-wp-hook.php(331)): WP_Hook->apply_filters()
#3 /www/wwwroot/[DOMAIN/wp-includes/plugin.php(474)](http://DOMAIN/wp-includes/plugin.php(474)): WP_Hook->do_action()
#4 /www/wwwroot/[DOMAIN/wp-includes/post.php(6390)](http://DOMAIN/wp-includes/post.php(6390)): do_action()
#5 /www/wwwroot/[DOMAIN/wp-admin/upload.php(197)](http://DOMAIN/wp-admin/upload.php(197)): wp_delete_attachment()
#6 {main}
  thrown

### Steps to reproduce

Delete media

**Comment by midweste** [comment]
By any chance are you using the hook 'cloudflare_purge_by_url'?  If so, can you verify it's not returning a null value?
