### ISSUE TITLE
Cache should be purged after nav menu update

### ISSUE THREAD

**Issue by Dalias96** [cloudflare/Cloudflare-WordPress#478]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.9.2

### Cloudflare-WordPress version

4,9,1

### PHP version

7.4.28

### Expected result

After update of nav-menu entire cache should be purged

### Actual result

Cache is not purged after nav menu edit.

### Steps to reproduce

1. Enter page to create cache (check if have HIT status)
2. Edit nav menu
3. Check page again, you will get old version with HIT status and new with BYPASS status.

**Comment by Dalias96** [comment]
Added possible solution in [PR](https://github.com/cloudflare/Cloudflare-WordPress/pull/479)

**Comment by Jineshpanchal** [comment]
We are also facing similar issue, where in one of our project https://www.brahmakumaris.com/kalp-taruh/
, whenever we are making changes in the menu, it is not automatically reflecting on all the pages where we have the menu.

Everytime we have to manually purge all the pages which has same menu strcuture.

We are using APO.

**Comment by Jineshpanchal** [comment]
We are facing this issue since long time and sharing once more time here...
we have also raised on official channel but no resolution "

https://support.cloudflare.com/hc/en-us/requests/2530764?page=1

Kindly check the above link for every minute details.
