### ISSUE TITLE
admin page shows my site is not provisioned by cloudflare

### ISSUE THREAD

**Issue by vickfan** [cloudflare/Cloudflare-WordPress#480]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.9

### Cloudflare-WordPress version

4.9.1

### PHP version

7.4

### Expected result

able to login to or link to my cloudflare account and config settings

### Actual result

buttons not responding in the admin panel and the following message shown 
```
It looks like your domain stg.i-cable.com is not provisioned with Cloudflare. Please continue to [Cloudflare](https://dash.cloudflare.com/?to=/:account/add-site) to secure and speed up your website.
```

### Steps to reproduce

1. install the plugin
2. activate the plugin
3. go to setting -> cloudflare

### Additional factoids

I have tried adding WP_HOME and WP_SITEURL into my wp-config.php according to #240 but the problem still not being solved

### References

#240

**Comment by jacobbednarz** [comment]
I'm afraid this isn't an issue with the plugin but your site or usage and there is very little I can do to help other than direct you to the documentation we have. I'd recommend checking your site is setup on Cloudflare, and then try to install the plugin (keeping in mind things like domains have to match and be provisioned on Cloudflare to be used)
