### ISSUE TITLE
Plugin tries to clear cache after each image upload unnecessarily which causes Too Many Requests errors

### ISSUE THREAD

**Issue by rafaucau** [cloudflare/Cloudflare-WordPress#481]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.0

### Cloudflare-WordPress version

4.9.1

### PHP version

8.0

### Expected result

The plugin should only clear the cache of resources that require it.

### Actual result

For example, when e.g. 100 images are uploaded, Cloudflare clears the cache of author pages, feeds, etc. after each image uploaded. This causes errors and possibly unnecessary load on the server.

I see thousands of such errors in `debug.log`:
```
[31-May-2022 19:43:42 UTC] [Cloudflare] ERROR: Too Many Requests 
[31-May-2022 19:43:42 UTC] [Cloudflare] ERROR: [CLIENT API] Array
(
    [type] => request
    [path] => https://api.cloudflare.com/client/v4/zones/****************/purge_cache
    [timeout] => 30
    [method] => DELETE
    [headers] => Array
        (
            [Content-Type] => application/json
            [User-Agent] => wordpress/6.0; cloudflare-wordpress-plugin/4.9.1
            [Authorization] => REDACTED
        )

    [body] => {"files":["https:\/\/example.com\/author\/name\/","https:\/\/example.com\/author\/name\/feed\/","https:\/\/example.com\/?attachment_id=489024","https:\/\/example.com\/feed\/rdf\/","https:\/\/example.com\/feed\/rss\/","https:\/\/example.com\/feed\/","https:\/\/example.com\/feed\/atom\/","https:\/\/example.com\/comments\/feed\/","https:\/\/example.com\/?attachment_id=489024\/feed\/","https:\/\/example.com\/","https:\/\/example.com\/page\/1\/","https:\/\/example.com\/page\/2\/","https:\/\/example.com\/page\/3\/","https:\/\/static.example.com\/uploads\/2022\/05\/IMG20220521145906-150x150.jpg","https:\/\/static.example.com\/uploads\/2022\/05\/IMG20220521145906-768x576.jpg","https:\/\/static.example.com\/uploads\/2022\/05\/IMG20220521145906-1280x960.jpg","https:\/\/static.example.com\/uploads\/2022\/05\/IMG20220521145906-1536x1152.jpg","https:\/\/static.example.com\/uploads\/2022\/05\/IMG20220521145906-2048x1536.jpg","https:\/\/static.example.com\/uploads\/2022\/05\/IMG20220521145906-360x270.jpg"]}
)
```

### Steps to reproduce

1. Enable `WP_DEBUG_LOG`.
2. Upload a lot of images in a short time (preferably in bulk)
3. You will probably also see some server sluggishness
3. Check `debug.log`.

**Comment by jordantrizz** [comment]
This happens in many other instances within the Cloudflare plugin, such as #434.

Implement logic that doesn't purge the entire cache on each interaction, instead purge on the last event or if another purge request hasn't been received after 15/30 seconds.

**Comment by rafaucau** [comment]
.

**Comment by jordantrizz** [comment]
Not stale.
