### ISSUE TITLE
Cloudflare using APO - Always served from Cache, even after update, create post. (Home page is exception)

### ISSUE THREAD

**Issue by Jineshpanchal** [cloudflare/Cloudflare-WordPress#487]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.0

### Cloudflare-WordPress version

4.10.1

### PHP version

7.4.13 

### Expected result

Whenever we are making any changes to the post, or adding new post, it should be available on respective sections based on category assigned.

Also while changing menu struture, pages should purge cached automatically

### Actual result

For an instance,

Today we have updated 2 post on our website

1. Soul Sustenance
2. Thought For Today
Now both are visible on home pages section of www.brahmakumaris.com

But in other page, it is showing yesterdays post only…and not of today.
https://www.brahmakumaris.com/soul-sustenance/

https://www.brahmakumaris.com/thought-for-today/

Now if you press Ctrl+Shift+R on above page, then it will load and show the data of today as well…but again if we do the normal refresh then it is serving data of yesterday from cache.

Settings are default only…after enalbing APO.

If we deactivating APO then website is updating properly. 

APO is helping a lot to improve speed but at the same time it is adding lot of manual effort to purge page each time adding/updating post or pages or menus.

### Steps to reproduce

Everyday we are facing this challenge on our site.

**Comment by jacobbednarz** [comment]
did you enable APO through the wordpress plugin? what is in the debug logs?

**Comment by Jineshpanchal** [comment]
> did you enable APO through the wordpress plugin? what is in the debug logs?

How do we get the debug logs ?

We have tried enable from cloudflare website also tried from wordpress plugin.

**Comment by Jineshpanchal** [comment]
We have enable APO via wordpress plugin only. Below are the url where we have sent multiple messages.
https://community.cloudflare.com/t/latest-cloudflare-plugin-update-cache-issues/388638/7

Regarding, Debug log, we dont have any...

Do we have alternative way to check and fix the issue.

**Comment by Jineshpanchal** [comment]
Can someone help to fix the issue.

**Comment by Jineshpanchal** [comment]
Kindly help
