### ISSUE TITLE
Cannot clear cache of a URL defined as an array

### ISSUE THREAD

**Issue by conorriches** [cloudflare/Cloudflare-WordPress#488]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.9.3

### Cloudflare-WordPress version

4.9.1

### PHP version

7.4.29

### Expected result

When adding or updating a post, I expect all URL caches to be cleared, including URLs defined as an array which have been added in, e.g. through the `cloudflare_purge_by_url` hook, or some other method.

### Actual result

URLs which are defined as an array with headers are filtered out, meaning that when a new post is added or updated, services which consume our wordpress content do not have their cache cleared, and stale content continues to be served until a manual cache clear.

### Steps to reproduce

1. Use the `cloudflare_purge_by_url` filter to add a URL that needs it's cache cleared.
```
<?php

/**
 * @param array $urls A list of post related URLs
 * @param integer $post_id the post ID that was modified
 */
function external_service_homepage_cloudflare_url_filter($urls, $post_id) {
    $urls[] = array(
        'url' => 'https://website.com/',
        'headers' => array(
            'x-forwarded-host' => 'www.website.com'
        )
    );
    return $urls;

}

add_filter('cloudflare_purge_by_url', 'external_service_homepage_cloudflare_url_filter', 10, 2);

```

2. Note that the new URL exists in https://github.com/cloudflare/Cloudflare-WordPress/blame/a2a56c4523165969ae3b76b40374d027f52126ea/src/WordPress/Hooks.php#L165
3. Note that the URL is now filtered out https://github.com/cloudflare/Cloudflare-WordPress/blame/a2a56c4523165969ae3b76b40374d027f52126ea/src/WordPress/Hooks.php#L181

This now means that any URL defined as an array which is needing a cache clear on an update won't work.

### Additional factoids

I understand that [this recent update](https://github.com/cloudflare/Cloudflare-WordPress/commit/5e93746b318ab4fd2ed49254aefeae9824aae022) has intentionally removed the ability to clear URL caches outside of the current zone. However, this now means that we can't automatically clear the cache on sites which consume the data out of wordpress as it has to be defined as an array due to the headers.

Being able to have external site cache cleared from a post being added or updated is important as we are using the `wp-json` data to load in content from wordpress onto an external site. Therefore being able to refresh both caches is important. 

### References

https://github.com/cloudflare/Cloudflare-WordPress/commit/5e93746b318ab4fd2ed49254aefeae9824aae022

**Comment by jacobbednarz** [comment]
can you provide examples of the two domains you would be using here? are they both owned by you and on Cloudflare?

**Comment by jacobbednarz** [comment]
> Just as a side note, using `$wpDomain` in this filter might not be best, as it'd prevent a WP hosted on blog.example.com from purging cache on example.com, depsite being in the same zone.

you're right the check is somewhat naive as it assumes you have the WP install at the root or above the other subdomain you are attempting to purge for. i'm open to improvements with this however, it's a way down my list as the reported impact has been nil so far.
