### ISSUE TITLE
Dependency on Psr/log breaks sites using different versions

### ISSUE THREAD

**Issue by rmilesson** [cloudflare/Cloudflare-WordPress#490]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.0

### Cloudflare-WordPress version

4.10.1

### PHP version

8

### Expected result

A fatal error should not occur.

### Actual result

A fatal error with the following message occurs.

```
Fatal error: Declaration of Psr\Log\NullLogger::log($level, Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::log($level, $message, array $context = []) in /app/public/wp-content/themes/site.tld/vendor/psr/log/src/NullLogger.php on line 26
```

### Steps to reproduce

1. Install 4.10.1 version of Cloudflare for WordPress.
2. Create a theme which depends on and uses Psr/log 3.0.0

### References

A similar issue has occured and has been dealt with in https://github.com/cloudflare/Cloudflare-WordPress/issues/445.

**Comment by jacobbednarz** [comment]
duplicate of #470

**Comment by rmilesson** [comment]
Altough I agree that it would fix this issue, I also think it's a short-sighted fix. Would it be possible to do some namespace scoping with Mozart or PHP-Scoper instead?

**Comment by jacobbednarz** [comment]
I'm yet to find an example of either of these projects where it doesn't a) increase release/maintenance burden or b) impact local development/testing. right now, this isn't enough of an issue to warrant introducing a higher barrier to running and maintaining this plugin. 

if we can find a solution to those, I'm open to the possibility.

**Comment by graham73may** [comment]
@jacobbednarz I've run in to exactly this dependency issue just now. 

It seems Psr/Log can't be updated to maintain PHP 7 compatibility, so namespacing your use of it might be the only option left? 

Would you accept a PR adding Mozart and adding a namespace?

**Comment by graham73may** [comment]
Just to add incase this is helpful for anyone else, check what versions your other packages accept, you might get lucky.

In my case, I'm installing `chrome-php`, this allows: `"psr/log": "^1.1 || ^2.0 || ^3.0"`

**Before:**
```json
{
  "require": {
	"chrome-php/chrome": "^1.9"
  }
}
```

**After:**
Force it to use v1, to match the Cloudflare plugin:
```json
{
  "require": {
	"chrome-php/chrome": "^1.9",
	"psr/log": "^1.0"
  }
}

```

**Comment by dalepgrant** [comment]
@jacobbednarz Hi 👋 , adding another voice here, we're experiencing this issue with all sites built using [roots/acorn](https://github.com/roots/acorn) as they're requiring `psr/log` v3 (link to their [docs on compatibility](https://roots.io/acorn/docs/compatibility/)).

Totally understand the need to keep a WP plugin supporting 7.4 and you're not alone in this dependency conflict (same issue [reported to WPML](https://wpml.org/forums/topic/fatal-error-declaration-of-monolog/) for example), however it seems this issue will grow the longer it's left. Is #541 an option? If not (or better: to prevent similar issues in future), is it time to reconsider namespacing?
