### ISSUE TITLE
"Auto Purge Content On Update" no longer working

### ISSUE THREAD

**Issue by physixfan** [cloudflare/Cloudflare-WordPress#496]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.0.2

### Cloudflare-WordPress version

4.11.0

### PHP version

7.4

### Expected result

The CloudFlare WordPress plugin should purge a post's cache on CloudFlare after a post is updated. It worked before when "Auto Purge Content On Update" was available and “Automatic Platform Optimization for WordPress” was not introduced.

### Actual result

After “Automatic Platform Optimization for WordPress” was introduced and "Auto Purge Content On Update" was discontinued, the plugin no longer purge cache automatically for an updated post.

> `Auto Purge Content On Update
>
> Purge Cloudflare cache automatically when you update the appearance of your site.
> 
> Note: This feature is superseded by Automatic Platform Optimization for WordPress. If you are using APO, then this setting should be disabled.`

### Steps to reproduce

Update an existing post, and see whether cached user can see the new contents immediately. Previously they can, but now they can't until I purge all cache on CloudFlare.

**Comment by physixfan** [comment]
Oh i realized maybe this is the same issue as the following one:

https://github.com/cloudflare/Cloudflare-WordPress/issues/248

We always use REST API in our mobile app, and i checked the cache for the direct url is correctly purged after post updating, but its REST API is not working properly.

**Comment by johnaps94** [comment]
I am having the same problem, no page purge when updating content on site...
Tried many things, nothing triggers it even after an hour is passed...

Do you have (for example) a specific product page cache purged when you updated that product's price?

**Comment by Jineshpanchal** [comment]
We are also facing this issue since past few months after using APO in site.

Seriously cloudflre needs to fix this bug

**Comment by johnaps94** [comment]
What are we going to do to get this attention???
This is basic functionality, of course apo has very good caching mechanisms, that you cant find anywhere else, but without auto purge working the whole cloudflare service is useless... and i am on a pro account for god's sake...
I dont even want to know for how long my site is like this... and its an eshop....

How are we gonna get attention? I am gonna post to facebook groups as well to get attention as much as possible...

**Comment by TommyBloom** [comment]
Any updates on this?
