### ISSUE TITLE
How does cloudflare detect the plugin is installed?

### ISSUE THREAD

**Issue by peixotorms** [cloudflare/Cloudflare-WordPress#513]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.2

### Cloudflare-WordPress version

4.1.2.0

### PHP version

8.1

### Expected result

N/A

### Actual result

N/A

### Steps to reproduce

When I go to Cloudflare and want to enable APO, it says the Cloudflare plugin is not detected or installed.
After installing it, it starts detecting it and I can install it.

However, I want to use the Cloudflare API with custom PHP coding, so I don't need the plugin to be installed.
How do I make it so that Cloudflare thinks that the Cloudflare plugin is installed?

Is it some api call, some html markup, or something else?

Thanks

### Additional factoids

N/A

### References

N/A

**Comment by markjaquith** [comment]
The plugin tells WordPress to add an HTTP header:

`cf-edge-cache: cache,platform=wordpress` (if the response should use the cache)

or

`cf-edge-cache: no-cache` (if the response should not use the cache)

https://github.com/cloudflare/Cloudflare-WordPress/blob/4ad24c88c9a1ed58b2aa288ce3ca587ba873566c/src/WordPress/Hooks.php#L436-L442

I suspect that when enabling APO on the Cloudflare side it just looks for this `cf-edge-cache` header to be present and have an expected value.
