### ISSUE TITLE
WAF toggle doesn't make sense with the new Managed Rules

### ISSUE THREAD

**Issue by piperswe** [cloudflare/Cloudflare-WordPress#522]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.3

### Cloudflare-WordPress version

4.12.2

### PHP version

8.0.27

### Expected result

WAF configuration should control managed rules

### Actual result

WAF configuration consists of a single on/off toggle, which no longer exists with the new Managed Rules. Toggling it causes a "Bad Request" error.

### Steps to reproduce

See "Security" section of Cloudflare plugin's "Settings" tab. If your zone has new Managed Rules enabled, toggling the WAF toggle will result in a "Bad Request" error.

### Environment
- WordPress: 6.3
- PHP: 8.0.27
- Server: Apache/2.4.53 (AlmaLinux) OpenSSL/3.0.7
- Database: mysqli (Server: 8.0.32 / Client: mysqlnd 8.0.27)
- Browser: Safari 16.2 (macOS)
- Theme: Twenty Twenty-Three 1.2
- MU-Plugins: None activated
- Plugins:
  * Akismet Anti-Spam: Spam Protection 5.2
  * All in One SEO 4.4.3
  * Cloudflare 4.12.2
  * Cloudflare Image Resizing 1.5.2
  * Code Syntax Block 3.1.1
  * Custom Fonts 2.0.2
  * DreamHost Panel Login 1.0.0
  * File Upload Types 1.3.0
  * Health Check & Troubleshooting 1.7.0
  * Jetpack 12.4
  * Jetpack Boost 2.0.0
  * Jetpack Protect 1.4.1
  * Jetpack Search 1.4.1
  * JSON Feed 1.4.3
  * Performance Lab 2.5.0
  * Redirection 5.3.10
  * Simple Cloudflare Turnstile 1.22.1
  * WebSub (FKA. PubSubHubbub) 3.1.3
  * WordPress Beta Tester 3.5.3
  * WPForms Lite 1.8.3.1
  * WP Mail SMTP 3.8.2
  * Zotpress 7.3.4

### References

https://developers.cloudflare.com/waf/reference/migration-guides/waf-managed-rules-migration/

May be related to #507

**Comment by jordantrizz** [comment]
.
