### ISSUE TITLE
Will this work with a Partial CNAME setup?

### ISSUE THREAD

**Issue by josh-coderpad** [cloudflare/Cloudflare-WordPress#525]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.3.1

### Cloudflare-WordPress version

4.12.2

### PHP version

7.3

### Expected result

An error message in the settings page, or the plugin to continue working.

### Actual result

[500 errors](https://github.com/cloudflare/Cloudflare-WordPress/issues/423#issuecomment-892982762) and [js errors](https://github.com/cloudflare/Cloudflare-WordPress/issues/430#issuecomment-898491192) in the console.

### Steps to reproduce

I believe this came up because I disabled the plugin and re-enabled it, but it now happens on every install, so I'm not sure exactly. It appears to be the same issue previously reported twice (links above).

### Additional factoids

I opened a support ticket about this, but after some confusion was pointed to [this page](https://developers.cloudflare.com/automatic-platform-optimization/get-started/change-nameservers/), which (per support) implies Partial CNAME setups are not supported. Is this true? I'm almost positive that the plugin was previously working, but unfortunately I don't have proof of that, so I wanted to confirm here because I found the docs ambiguous on this point (to me they just indicate your Wordpress site needs to be behind Cloudflare's Proxy, which it is in my Partial CNAME setup).

### References

- https://github.com/cloudflare/Cloudflare-WordPress/issues/423
- https://github.com/cloudflare/Cloudflare-WordPress/issues/430

**Comment by jordantrizz** [comment]
A partial cname setup should function just like a full zone, there shouldn't be a difference.
