### ISSUE TITLE
Bad Request on Cloudflare Option page

### ISSUE THREAD

**Issue by ctekk7** [cloudflare/Cloudflare-WordPress#534]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

Newest

### Cloudflare-WordPress version

Newest

### PHP version

8.1 FPM

### Expected result

No Bad Request

### Actual result

Bad Request Error Message shown. Images and other users reporting it:
https://community.cloudflare.com/t/cloudflare-wordpress-plugin-for-apo-giving-error-of-bad-request/612602/21

### Steps to reproduce

Open Option Page

### References

https://community.cloudflare.com/t/cloudflare-wordpress-plugin-for-apo-giving-error-of-bad-request/612602/21

**Comment by aseure** [comment]
Hello @ctekk7, thanks for the report. We've opened a ticket internally and we'll keep you posted.
