### ISSUE TITLE
What does "One-click WordPress-optimized settings" mean?

### ISSUE THREAD

**Issue by pjv** [cloudflare/CloudFlare-Wordpress#61]
I have to say that you guys are lately ranking near the top of my list of poor communicators.

I know that the majority of WordPress installs out there on the interwebs are on cheap, shared hosting and managed by bloggers who don't know what PHP is, much less which version they are running. And a hide-the-details, "don't worry - it just works" attitude might be best for them.

But there are more than a few of us out here who are running WordPress behind CloudFlare that have carefully tuned, non-standard WP stacks to maximize performance and reliability for whom pressing a button in a plugin whose only documentation is "The easiest way to setup CloudFlare for your WordPress site" is an absolute non-starter.

Is it really too much to ask that you guys document what actually happens when someone presses that button? Do I really have to read through the source code of the plugin in order to have any idea at all what it does?

I know that CloudFlare has someone on staff that is capable of producing good [documentation](https://api.cloudflare.com/#). Can you borrow them from the API team for a couple days to let us know what the plugin is doing?

**Comment by pjv** [comment]
Wow, is this (CloudFlare-Wordpress/src/WordPress/PluginActions.php) really what happens when someone pushes that button?

With zero documentation you are going to change all of the carefully selected (for me anyway) settings in the cloudflare account for the domain?

That seems fairly amazing -- in a negative way -- to me.

**Comment by thellimist** [comment]
Sorry for the inconvenience you are having.

We've documented "One-click WordPress-optimized settings" in FAQ.

https://en-gb.wordpress.org/plugins/cloudflare/faq/
