### ISSUE TITLE
Minify compiled.js

### ISSUE THREAD

**Issue by XhmikosR** [cloudflare/CloudFlare-Wordpress#73]
Not sure how the file is generated, I couldn't find any info, but I tested it with `uglifyjs --compress --mangle` and it went from **2.89 MB** to **1.06 MB** which is a huge improvement.

The numbers are without gzip/br compression.

**Comment by jwineman** [comment]
We'll be minifying the JS in 3.0.4 of the WordPress plugin.

**Comment by jwineman** [comment]
Also, to give you some context.  The front end for all our plugins lives at [cloudflare/cloudflare-frontend](https://github.com/cloudflare/CloudFlare-Frontend).  So all the front end changes to this plugin will likely end up occurring there.

**Comment by XhmikosR** [comment]
Should I make the remaining PRs to that repo then?

Also, you should use submodules or something to make this clear.

**Comment by XhmikosR** [comment]
I meant, should I close the remaining PRs from this repo and make them to https://github.com/cloudflare/CloudFlare-Frontend?

**Comment by XhmikosR** [comment]
@jwineman: I tried 3.0.4 and compiled.js is still not minified.

**Comment by XhmikosR** [comment]
@jwineman: ^^ bump in case you missed the notification.
