### ISSUE TITLE
Attempting to change settings fails with "CSRF Token not valid" error message

### ISSUE THREAD

**Issue by jb510** [cloudflare/CloudFlare-Wordpress#82]
Any attempt to change settings in the new interface fails with a "CSRF Token not valid" error shown across the bottom of the window. I tried Purge, Full Cache Management, WAF and Image Optimization none of it works.

Site was connected fine with CF plugin v 1.3.35, upgraded directly to v3.0.3, I've since reverted.

FYI, the new interface reports the active zone correctly, but I don't see anywhere to reset/reconnect the API key and set the account.

**Comment by thellimist** [comment]
Hi @jb510 

This is known issue with users who has InfiniteWP plugin installed in their server. Unfortunately this is a bug on their side and to use the Cloudflare Plugin you must delete InfiniteWP server files and deactivate the plugin.

We've submitted a bug ticket to them but feel free to submit another ticket.

**Comment by jb510** [comment]
I can confirm these sites have InfiniteWP installed.  I've reached out InfiniteWP support.

**Comment by jwineman** [comment]
A summary of the issue is here as well: https://wordpress.org/support/topic/invalid-csrf-token-on-3-0-1/page/3/#post-8223329

**Comment by Betawolf1213** [comment]
I'm dealing with this problem and I don't have InfiniteWP installed. So what gives?

**Comment by thellimist** [comment]
@Betawolf1213 Do you have any other plugins installed? If so you should try to turn them on and off one by one to figure out which of those is causing the issue.

**Comment by rowatt** [comment]
The [WP-SpamShield](https://wordpress.org/plugins/wp-spamshield/) also has the same issue. I'll report it to the plugin author and hopefully he can fix.
