### ISSUE TITLE
Synchronize nomenclature with CloudFlare dashboard 

### ISSUE THREAD

**Issue by jb510** [cloudflare/CloudFlare-Wordpress#83]
It's confusing to call have a section called "Image Optimization" under Speed. This is different nomenclature than used in the CloudFlare Dashboard which used Polish and Mirage.  Is this feature on of those, or both at the same time?  

v3.0.3 (and prior versions)

**Comment by thellimist** [comment]
Both at the same time. This was a conscious choice on our end to simplify the features for non-tech users.
