### ISSUE TITLE
Active Zone should not show as a dropdown w/ arrow if it's not actually dropdown.

### ISSUE THREAD

**Issue by jb510** [cloudflare/CloudFlare-Wordpress#84]
Per issue 60 it was stated that the Active Zone "dropdown" should only show one site and this was intended behavior. This is extremely confusing UI.

I have 10+ domains in the CF account I'm connected to. I'd expect to either:
A) see them all w/ the active one highlighted
B) not see a drop down arrow suggesting I should see something more here...

I also don't see any way to change it, which is going to be a problem when someone migrates their site to a new domain.

**Comment by thellimist** [comment]
You are absolutely correct. This is an extremely confusing UI. We will have a solution for it in the near feature.

> I also don't see any way to change it, which is going to be a problem when someone migrates their site to a new domain.

The Active Zone gets the domain your wp-admin is opened in so this shouldn't be a problem in the current version.
