### ISSUE TITLE
"return" in cloudflare.loader.php stops the plugin from functioning properly

### ISSUE THREAD

**Issue by mike503** [cloudflare/CloudFlare-Wordpress#89]
The "return true" in here stops the plugin from actually working properly - it won't display the CloudFlare settings menu or anything. The minute I uncomment the "return" line out, things function properly. Not sure why it's even in there.

```php
$is_cf = $ipRewrite->isCloudFlare();
if ($is_cf) {
    // Fixes Flexible SSL
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
        $_SERVER['HTTPS'] = 'on'; 
        return true;
    }
}
```

**Comment by thellimist** [comment]
Thanks. While refactoring the code somehow I missed this. 

https://github.com/cloudflare/CloudFlare-Wordpress/pull/90

**Comment by jwineman** [comment]
Hey,

To give more detail here - this code used to live in a function and returned `true` if it executed the flexible SSL fix.  Because WordPress is procedural we ended up having to move this fix out of the function into a different file so it would load sooner.  We missed the return when we switched the file.  Sorry about that.

Thanks,
John

**Comment by mike503** [comment]
Makes sense - I'm glad I'm not crazy!

Unrelated note - I didn't look but do you have a generic "purge entire site" (or zone, rather) simple function or method in the code? I wrote my own plugin but piggybacking on yours would be much better. :)

**Comment by jwineman** [comment]
Hey @mike503,

The purge cache functionality is implemented [here](https://github.com/cloudflare/CloudFlare-Wordpress/blob/master/src/WordPress/WordPressClientAPI.php#L49).  Pass it the zone id you want to purge and it will make the API call.

Thanks,
John
