### ISSUE TITLE
Purging cache throws TypeError

### ISSUE THREAD

**Issue by XhmikosR** [cloudflare/Cloudflare-WordPress#92]
Using v3.0.5, choosing Purge Everything throws the following TypeError:

```
18:39:12.961 TypeError: response is undefined[Learn More]compiled.js:84313:5
v4ResponseOkhttps://foo.bar/wp-content/plugins/cloudflare/compiled.js:84313:5[540]</asyncZonePurgeCacheEverything/</<https://foo.bar/wp-content/plugins/cloudflare/compiled.js:77225:18[150]</request/<https://foo.bar/wp-content/plugins/cloudflare/compiled.js:7020:7[157]</Request.prototype.callbackhttps://foo.bar/wp-content/plugins/cloudflare/compiled.js:8411:3[157]</Request/<https://foo.bar/wp-content/plugins/cloudflare/compiled.js:8134:5[161]</Emitter.prototype.emithttps://foo.bar/wp-content/plugins/cloudflare/compiled.js:9036:7[157]</Request.prototype.end/xhr.onreadystatechangehttps://foo.bar/wp-content/plugins/cloudflare/compiled.js:8493:5
```

**Comment by jwineman** [comment]
I'm not able to reproduce this.  Are you able to change other settings for this domain without error?

**Comment by XhmikosR** [comment]
I can reproduce it with 3 of my sites that I tried.

I can change other stuff without any TypeError, like Automatic Full Cache Management.

**Comment by XhmikosR** [comment]
Still getting this with 3.0.6.

On a side note, perhaps when updating the plugin, the CF cache should be purged automatically. When I have a page rule to cache everything, I need to do this manually otherwise I still get the old one.

**Comment by thellimist** [comment]
@XhmikosR https://github.com/cloudflare/Cloudflare-WordPress/pull/106 should fix the caching issues. 

>  I have a page rule to cache everything

Please add another Page Rule to bypass cache for `wp-admin` area. Applying Default Settings will also try to add this page rule.

**Comment by XhmikosR** [comment]
I'm pretty sure that's irrelevant to the issue (let alone it changes some of my zone settings which I don't want), but I did and the same TypeError is being thrown.

**Comment by thellimist** [comment]
Just to be clear I responded to the side note you mentioned.

> On a side note, perhaps when updating the plugin, the CF cache should be purged automatically. When I have a page rule to cache everything, I need to do this manually otherwise I still get the old one.

For `TypeError` we still don't have enough information to figure out the problem.

Could you provide a HAR file with the error and submit a support ticket to cloudflare.com?

**Comment by XhmikosR** [comment]
Cool no worries.

I'll try to make an issue tomorrow.

**Comment by XhmikosR** [comment]
Request #1274095

**Comment by thellimist** [comment]
@XhmikosR I've checked your HAR file. Is there any settings which blocks HTTP DELETE methods? It looks like your server responds to `DELETE` method as a `GET` method.

**Comment by XhmikosR** [comment]
@thellimist: it's iThemes Security's option "Filter Request Methods: *Filter out hits with the trace, delete, or track request methods.*"

**Comment by thellimist** [comment]
@XhmikosR I downloaded https://wordpress.org/plugins/better-wp-security/ but it doesn't have the option you mentioned

**Comment by XhmikosR** [comment]
It's in System Tweaks.

**Comment by thellimist** [comment]
@XhmikosR You are correct. The reason is `iThemes`. Currently we are not planning to edit the plugin to avoid iThames security option. I'll let you know if we decide to change this. 

Thanks.

**Comment by XhmikosR** [comment]
@thellimist: how about showing an error in the case where you can't use DELETE or GET. Failing silently is bad,..

**Comment by jwineman** [comment]
It shouldn't be failing silently, we can definitely fix that.

**Comment by jwineman** [comment]
Tracking internally PI-902
