### ISSUE TITLE
Feature request: "Varnish HTTP Purge" type event handling

### ISSUE THREAD

**Issue by mike503** [cloudflare/Cloudflare-WordPress#94]
I began making my own plugin, but it looks like the official CF plugin is starting to pave ways for this...
https://github.com/mike503/cloudflare-full-page-caching/

Essentially setting up approriate triggers (WP action hooks) for the various types of activities. As can be used when page rules are enabled to cache the entire site (using CF like a distributed Varnish)

This is functional currently in my plugin for a couple things. But reusing your existing library and zone awareness would be much more beneficial. :) This is just a couple snippets to show how to compile a list of possible URLs to purge, and a list of the actions that should trigger one.

However, there is no "queue" mechanism so if two posts got published and triggered purges while the API is still not accepting another purge will fail silently, probably, instead of being a little more intelligent.

These are some of the actions I was able to find

``` php
// PER-PAGE EVENT PURGING
add_action('wp_scheduled_delete', '_cloudflare_full_page_caching_purge_urls');
add_action('transition_post_status', '_cloudflare_full_page_caching_purge_urls', 10, 3);
/* look at leveraging these - first param is the post ID on some of these
add_action('save_post', '_cloudflare_full_page_caching_purge_urls');
add_action('deleted_post', '_cloudflare_full_page_caching_purge_urls');
add_action('trashed_post', '_cloudflare_full_page_caching_purge_urls');
add_action('edit_post', '_cloudflare_full_page_caching_purge_urls');
add_action('delete_attachment', '_cloudflare_full_page_caching_purge_urls');
*/
```

This is the beginning of the function I was using, it seems to work properly.

``` php
function _cloudflare_full_page_caching_purge_urls($a, $b, $post) {
  if (!$zone_id = _cloudflare_full_page_caching_zone_id()) {
// could add message
    return FALSE;
  }
  // borrowed heavily from varnish-http-purge
  $urls = array();
  if ($categories = get_the_category($post->ID)) {
    foreach ($categories as $cat) {
      array_push($urls, get_category_link($cat->term_id));
    }
  }
  if ($tags = get_the_tags($post->ID)) {
    foreach ($tags as $tag) {
      array_push($urls, get_tag_link( $tag->term_id));
    }
  }
  array_push($urls,
    get_author_posts_url(get_post_field('post_author', $post->ID)),
    get_author_feed_link(get_post_field('post_author', $post->ID))
  );
  if (get_post_type_archive_link(get_post_type($post->ID)) == true) {
    array_push($urls,
      get_post_type_archive_link(get_post_type($post->ID)),
      get_post_type_archive_feed_link(get_post_type($post->ID))
    );
  }
  array_push($urls, get_permalink($post->ID));
  array_push($urls,
    get_bloginfo_rss('rdf_url') ,
    get_bloginfo_rss('rss_url') ,
    get_bloginfo_rss('rss2_url'),
    get_bloginfo_rss('atom_url'),
    get_bloginfo_rss('comments_rss2_url'),
    get_post_comments_feed_link($post->ID)
  );
  array_push($urls, home_url('/'));
  if (get_option('show_on_front') == 'page') {
    array_push($urls, get_permalink(get_option('page_for_posts')));
  }
  $result = _cloudflare_full_page_caching_request('DELETE', 'zones/' . $zone_id . '/purge_cache', array('files' => $urls));
  if (isset($result['success']) || intval($result['success']) == 1) {
    return TRUE;
  }
  return FALSE;
}
```

**Comment by mike503** [comment]
Should also note that if using CF as a "full page cache" you'll want to make sure to not show admin options or menus on the frontend. So these are helpful:
```php
// CLEAN CROSS-SITE "MIXED ROLE" ISSUES - don't allow "logged in" options to display to anonymous users
add_filter('show_admin_bar', '__return_false');
add_filter('edit_post_link', '__return_null');
```

These were events that should trigger full site purges:
```php
// FULL-SITE EVENT PURGES
add_action('autoptimize_action_cachepurged', '_cloudflare_full_page_caching_purge_zone');
add_action('switch_theme', '_cloudflare_full_page_caching_zone');
```

And in the case of doing full page caching, it's helpful to have a purge button available on the top menu bar:
```php`
add_action('admin_bar_menu', '_cloudflare_full_page_caching_adminbar', 100);
```

**Comment by jwineman** [comment]
Hey!

I haven't forgot about this, I read it when you submitted it over the weekend and haven't had time to look at it in depth yet.  CloudFlare doesn't cache HTML by default so for people with "default configurations" these hooks may do nothing but we can still add them.  Give me a few days to look this over and I'll come back with more specifics around what we can and can't do.  This looks reasonable though.

Thanks,
John

**Comment by mike503** [comment]
I've been advising a lot of clients to do this if they can. CloudFlare makes a few bucks on it too sometimes, as a normal WP site requires more than the 3 free page rules to work properly :p 

````
1) the "cache everything rule"
2) wp-admin*
3) wp-login* or possibly *wp-*.php*
4) *?preview=true* (because post previews have to be out of the root of the site, sigh)
5) *feed*
```

**Comment by jwineman** [comment]
Hi @mike503,

Just to update you we recently merged https://github.com/cloudflare/Cloudflare-WordPress/pull/112 which covers some of the functionality you've mentioned.  On Friday we have our sprint planning and we'll be going over the rest of your suggestions with our product manager.

I'll keep this open until we have a decision.

Thanks,
John

**Comment by mike503** [comment]
Awesome! Yeah there are a lot of hooks that could be trapped for updating various things. Having more robust stuff in the official plugin for full page rule based caching will make it a lot easier to sell a solution that requires $5+/month to CF, so it is good for business too!

**Comment by giddyupgrp** [comment]
Hello; I just wanted to throw my $0.02 on this topic. Needless to say, it is something that would be fantastically useful, and something that I was going to start implementing myself.

I think there's an extremely useful subset of this functionality that addresses the most common use case -  a WP site where new articles are frequently posted, new pages are frequently created, and old posts/pages are never deleted. In this scenario, the only requirement is that if the user *changes* an existing post or page causes that URL to be purged from the CF cache.

Implementing just this functionality would be a fit for the majority of sites that would even want to do full-page caching, and be a much smaller effort to start off with...

Thanks for your consideration! I'd be very happy to discuss this in more depth if you'd like...

Steve

**Comment by jwineman** [comment]
Hi @giddyupgrp,

This is how automatic cache purge is implemented right now in #112.  We hook on [save_post](https://developer.wordpress.org/reference/hooks/save_post/) which will only fire on changes to a post.  

@mike503 other hook suggestions are for other wordpress actions which also indicate posts/url based content have changed.  

Do you have specific hooks you are concerned about? Or new hooks you would like us to consider adding?

Thanks,
John

**Comment by giddyupgrp** [comment]
Hey, John.

Does hitting "Apply Default Settings"in the plugin turn this behavior on?

**Comment by jwineman** [comment]
Hi @giddyupgrp,

Nope - this functionality hasn't been released yet.  Eventually it will be part of the "Automatic Full Cache Management" card on the homepage of the plugin.

Thanks,
John

**Comment by giddyupgrp** [comment]
Does save_post also get called when someone previews a post or page? That's the only other use case I can think of...

**Comment by jwineman** [comment]
No it does not.

**Comment by giddyupgrp** [comment]
That's a big deal. We are actually running full page caching right now, and this is the biggest complaints we're seeing from content authors. They really like to build a post or a page incrementally, doing lots of previews as they go. Of course, the preview URL gets cached after the first time it's used, so they are not happy campers.

So, it would be really good if Preview URLs could get purged each time the post/page was previewed; but is there even a WP hook for that?

**Comment by jwineman** [comment]
Apply Default settings will set a page rule which bypasses the cache for wp-admin.  This should solve that use case correct?

**Comment by giddyupgrp** [comment]
Unfortunately, no. Previewing URLs are not inside of wp-admin; they are on the main site domain. I just did a preview of a new page; here's the URL that the preview is using: http://mydailydiscovery.com/?p=3043&preview=true

I did bypass wp-admin, and that is working great for everything else...

**Comment by jwineman** [comment]
Ah my mistake, @mike503 covered this edge case with another page rule:
`*?preview=true*`

**Comment by mike503** [comment]
Yes. Sadly it costs a page rule for that (would be nice if Wordpress had designed it to be part of the admin area...) but the unstructured way the Wordpress ecosystem approaches things wreaks havoc on truly universal approaches. I was just working with another site that uses Beaver Page Builder or something and it has a query string of ?fl_builder as well. I've seen "cornerstone" I believe as another page layout thing and it has its own query string too.

**Comment by giddyupgrp** [comment]
Honestly, using a few page rules in order to get this functionality is such a non-issue. Doing this will save thousands of dollars when you are hosted on any "WordPress as a Service" host, since they bill per user session.

I just tried Mike's page rule; it didn't quite work. I modified it as follows, which works like a charm: 
yourdomainhere.com/?*&preview=true

**Comment by mike503** [comment]
This should work just fine. I wish that WP didn't do things this way, I understand why they did (in a twisted way) but it basically just blows right through page cache protections against the origin :/
```
*domain.com/*?preview=true*
```

There isn't a way to properly use full page caching with a free CloudFlare account if you want post previews and the full WP admin experience. If you can live with understanding that CF is caching your site and you can purge the cache when necessary by hand, you can do it under the free account.

My recipe for that is:
```
*domain.com/wp-login* - always online = off, cache level = bypass
*domain.com/wp-admin* - always online = off, cache level = bypass
*domain.com* - always online = on, cache level = cache everything, edge cache TTL = 1 day, browser cache TTL = 1 day
```

For sites willing to pay $5 for extra rules (or more) then you can add in:
```
*domain.com/*?preview=true* - always online = off, cache level = bypass
*domain.com/*?fl_builder* - always online = off, cache level = bypass (if using "Beaver Builder" page builder plugin)
*domain.com/*?cornerstone=true* - always online = off, cache level = bypass (if using "Cornerstone" theme, if I recall)
```

If you have enough rules, doing this stuff at CF's edge is always nice - enforcing SSL and a single canonical hostname. Not WP specific.
```
http://*domain.com* - always use SSL (first rule, will cover all CDN-enabled subdomains too, FYI)
https://www.domain.com* - redirect 301 to https://domain.com/$1 (good second rule)
```

**Comment by giddyupgrp** [comment]
Hi, Mike.

Nice to meet you. I didn't catch that the post before last was from you :-) Thanks for the CF rules tips; I forgot about "always on". 

We see a whole lot of benefit in using CF as an all-page cache for the types of WP sites we are building, so we would be happy to do anything we can to help make this happen. 

Thanks,
Steve

**Comment by mike503** [comment]
Nice to meet you as well. Yeah it definitely is a huge benefit to use CloudFlare like a distributed varnish. It'll only work for specific types of sites. Storefronts and other things that are highly dynamic can't be served properly. Everything must be pushed to AJAX / after page delivery DOM manipulation.

I'd also love if CF allowed just another 1-2 free rules... :)

@jwineman not sure why but it seems like the purging functionality in CF doesn't always take for me the first time, and in my code for my little plugin I made I don't always seem to get a success reply (and not sure why, it's not a "wait for a little bit you've sent too many purge requests" reply) - one thing that I would find useful is a notice that shows when a purge is successfully sent (for whatever reason - full site trigger or post specific...) to know that yes, a request was sent and yes it was received successfully. Also if not successful possibly a retry option?

**Comment by thellimist** [comment]
Hi guys,

@mike503 Thanks for your suggestion. I've added the most of the features you suggested.
https://github.com/cloudflare/Cloudflare-WordPress/commit/c3f904e6e4bee0e3743fc1d5690e82daf57ed010 https://github.com/cloudflare/Cloudflare-WordPress/commit/e62b4eb6a16b12b39724dbdccadd21f0076daa5c

Currently we're purging the following URL's dynamically
```
    [0] => http://domain.com/category/uncategorized/
    [1] => http://domain.com/author/furkan/
    [2] => http://domain.com/author/furkan/feed/
    [3] => http://domain.com
    [4] => http://domain.com?feed=rss2
    [5] => http://domain.com/2016/10/27/mypost/
    [6] => http://domain.com/feed/rdf/
    [7] => http://domain.com/feed/rss/
    [8] => http://domain.com/feed/
    [9] => http://domain.com/feed/atom/
    [10] => http://domain.com/comments/feed/
    [11] => http://domain.com/2016/10/27/mypost/feed/
    [12] => http://domain.com/
```

The hooks we integrated are 
```
$cloudflarePurgeActions = array(
    'autoptimize_action_cachepurged',   // Compat with https://wordpress.org/plugins/autoptimize
    'deleted_post',                     // Delete a post
    'edit_post',                        // Edit a post - includes leaving comments
    'delete_attachment',                // Delete an attachment - includes re-uploading
);
```

**Comment by thellimist** [comment]
@mike503 

> one thing that I would find useful is a notice that shows when a purge is successfully sent

In our implementation we return a boolean regarding if the request was successful or not https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/WordPressClientAPI.php#L52-L58

We do not check this in Automatic Cache Purge functionality. It'd make sense to show a simple error to the users if the request failed for whatever reason.

**Comment by giddyupgrp** [comment]
Ideally, the error dialog would include a button that retries the purge request and dismisses the dialog. Otherwise the user is stuck - there's nothing they can do other than log into Cloudflare and purge the cache manually (or purge the entire cache; yikes!). 

We are super excited about this functionality! But the users will ultimately be very non-technical people focused on producing content...

**Comment by jwineman** [comment]
I agree this is the idea scenario.  I'm not sure if WordPress lets us add errors to the front end from a hook if it fails.

**Comment by mike503** [comment]
@thellimist I would also trap comments... heck, you could just look at all of these[1] and see which make sense. Maybe make something smart and only send one purge request (currently if you have an add_action I would expect it to fire for each matching hook) perhaps some sort of boolean and only executes one action and if it's a site-wide purge, the individual one doesn't need fired either (if for some reason both got called)

1. https://developer.wordpress.org/reference/hooks/

**Comment by mike503** [comment]
I would say that there should be recommendations to deliver ads, trackers, comments, etc through the client side - Disqus for example is a great drop-in replacement which alleviates the server-side comment needs. That way, there are no server-side events to respond to, and the origin could literally be offline and still appear functional, as no origin requests would be required for something like Disqus to work. The "feel" of serverless, without actually doing anything (assuming everything is already cached at CF edge)

**Comment by thellimist** [comment]
Hi @mike503 and @brandomeniconi,

I've released a new version of Cloudflare WordPress Plugin with your suggestions and changes.

https://en-gb.wordpress.org/plugins/cloudflare/changelog/

Thanks

**Comment by thellimist** [comment]
We don't plan to add a to the admin bar to purge cache. The main issue Automatic Cache Management like Varnish HTTP Purge has been added  c3f904e e62b4eb.

**Comment by mike503** [comment]
@thellimist can I ask why no admin bar button? There's plenty of cases where automatic cache management stuff won't trigger and often have to tell clients to purge the cache, and it's much easier than having to go to Settings > CloudFlare > pressing the cache button and making sure it's "purge everything" ...

I appreciate all the work though, this is awesome.

**Comment by thellimist** [comment]
@mike503 We've talked with our PM and decided that the button adds additional complexity to the UI and to the users since most of them are not tech savvy. We're open to PR's adding this feature only if it is behind a condition which is disabled by default.
